/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input [3:0] cfg_last_stage;
  wire [3:0] cfg_last_stage;
  input [3:0] cfg_first_span_log2;
  wire [3:0] cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output [3:0] stage_count;
  wire [3:0] stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output [7:0] lane_valid;
  wire [7:0] lane_valid;
  output [79:0] coeff_addr_a;
  wire [79:0] coeff_addr_a;
  output [79:0] coeff_addr_b;
  wire [79:0] coeff_addr_b;
  output [71:0] butterfly_index;
  wire [71:0] butterfly_index;
  output [3:0] batch_stage;
  wire [3:0] batch_stage;
  output [3:0] batch_span_log2;
  wire [3:0] batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire [3:0] _318_;
  wire [3:0] _319_;
  wire [3:0] _320_;
  wire [3:0] _321_;
  wire [5:0] _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire [4:0] _347_;
  wire descending_q;
  wire [3:0] first_span_q;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire [3:0] \u_controller.cfg_last_stage ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire [3:0] \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire [3:0] \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.clk ;
  wire [3:0] \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire [3:0] \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire [5:0] \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire [3:0] \u_scheduler.batch_span_log2 ;
  wire [3:0] \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [71:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [79:0] \u_scheduler.coeff_addr_a ;
  wire [79:0] \u_scheduler.coeff_addr_b ;
  wire [9:0] \u_scheduler.decode_lanes.ordinal ;
  wire [9:0] \u_scheduler.distance_mask ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire [7:0] \u_scheduler.lane_valid ;
  wire [9:0] \u_scheduler.low_mask ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.rst_n ;
  wire [3:0] \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire [3:0] \u_scheduler.span_q ;
  wire [3:0] \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire [3:0] \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _348_ (
    .A(rst_n),
    .ZN(_054_)
  );
  INV_X1 _349_ (
    .A(\u_controller.state [6]),
    .ZN(_055_)
  );
  INV_X1 _350_ (
    .A(\u_controller.state [4]),
    .ZN(_064_)
  );
  NAND3_X1 _351_ (
    .A1(first_span_q[0]),
    .A2(_321_[2]),
    .A3(_321_[1]),
    .ZN(_150_)
  );
  AOI21_X1 _352_ (
    .A(first_span_q[2]),
    .B1(_321_[2]),
    .B2(first_span_q[1]),
    .ZN(_151_)
  );
  NAND2_X1 _353_ (
    .A1(first_span_q[3]),
    .A2(_150_),
    .ZN(_152_)
  );
  OAI21_X1 _354_ (
    .A(_063_),
    .B1(_151_),
    .B2(_152_),
    .ZN(_153_)
  );
  AOI21_X1 _355_ (
    .A(_153_),
    .B1(_149_),
    .B2(_147_),
    .ZN(_154_)
  );
  OAI221_X1 _356_ (
    .A(_154_),
    .B1(_146_),
    .B2(_144_),
    .C1(_140_),
    .C2(_141_),
    .ZN(_155_)
  );
  AOI21_X1 _357_ (
    .A(_106_),
    .B1(_105_),
    .B2(_063_),
    .ZN(_156_)
  );
  AOI221_X1 _358_ (
    .A(_156_),
    .B1(_155_),
    .B2(stage_start),
    .C1(batch_retired),
    .C2(_111_),
    .ZN(_157_)
  );
  NOR2_X1 _359_ (
    .A1(_054_),
    .A2(_057_),
    .ZN(zeroize_req)
  );
  NOR2_X1 _360_ (
    .A1(_103_),
    .A2(zeroize_req),
    .ZN(_158_)
  );
  INV_X1 _361_ (
    .A(batch_retired),
    .ZN(_065_)
  );
  OAI21_X1 _362_ (
    .A(_102_),
    .B1(_057_),
    .B2(_054_),
    .ZN(_159_)
  );
  NAND2_X1 _363_ (
    .A1(_112_),
    .A2(_158_),
    .ZN(_160_)
  );
  OAI22_X1 _364_ (
    .A1(_112_),
    .A2(_113_),
    .B1(_157_),
    .B2(_160_),
    .ZN(_161_)
  );
  INV_X1 _365_ (
    .A(_161_),
    .ZN(_162_)
  );
  NAND2_X1 _366_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_163_)
  );
  INV_X1 _367_ (
    .A(_163_),
    .ZN(_164_)
  );
  OAI221_X1 _368_ (
    .A(_164_),
    .B1(_160_),
    .B2(_157_),
    .C1(_112_),
    .C2(_113_),
    .ZN(_165_)
  );
  NOR2_X1 _369_ (
    .A1(_109_),
    .A2(_165_),
    .ZN(scheduler_quiescent)
  );
  OAI21_X1 _370_ (
    .A(_061_),
    .B1(cfg_last_stage[1]),
    .B2(cfg_last_stage[0]),
    .ZN(_166_)
  );
  XNOR2_X1 _371_ (
    .A(cfg_last_stage[2]),
    .B(_166_),
    .ZN(_167_)
  );
  INV_X1 _372_ (
    .A(batch_ready),
    .ZN(_066_)
  );
  NOR2_X1 _373_ (
    .A1(_076_),
    .A2(_167_),
    .ZN(_168_)
  );
  OR3_X1 _374_ (
    .A1(cfg_span_descending),
    .A2(cfg_last_stage[1]),
    .A3(_078_),
    .ZN(_169_)
  );
  OAI21_X1 _375_ (
    .A(cfg_last_stage[1]),
    .B1(_078_),
    .B2(cfg_span_descending),
    .ZN(_170_)
  );
  AND3_X1 _376_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_169_),
    .A3(_170_),
    .ZN(_171_)
  );
  NAND3_X1 _377_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_169_),
    .A3(_170_),
    .ZN(_172_)
  );
  OR2_X1 _378_ (
    .A1(_078_),
    .A2(cfg_first_span_log2[0]),
    .ZN(_173_)
  );
  INV_X1 _379_ (
    .A(_173_),
    .ZN(_174_)
  );
  AOI21_X1 _380_ (
    .A(cfg_first_span_log2[1]),
    .B1(_169_),
    .B2(_170_),
    .ZN(_175_)
  );
  NOR2_X1 _381_ (
    .A1(_171_),
    .A2(_175_),
    .ZN(_176_)
  );
  OAI21_X1 _382_ (
    .A(_172_),
    .B1(_174_),
    .B2(_175_),
    .ZN(_177_)
  );
  INV_X1 _383_ (
    .A(\u_controller.state [1]),
    .ZN(_067_)
  );
  XNOR2_X1 _384_ (
    .A(cfg_first_span_log2[2]),
    .B(_167_),
    .ZN(_178_)
  );
  AOI21_X1 _385_ (
    .A(_168_),
    .B1(_177_),
    .B2(_178_),
    .ZN(_179_)
  );
  NOR3_X1 _386_ (
    .A1(cfg_last_stage[2]),
    .A2(cfg_last_stage[1]),
    .A3(cfg_last_stage[0]),
    .ZN(_180_)
  );
  NOR2_X1 _387_ (
    .A1(cfg_span_descending),
    .A2(_180_),
    .ZN(_181_)
  );
  XNOR2_X1 _388_ (
    .A(cfg_last_stage[3]),
    .B(_181_),
    .ZN(_182_)
  );
  NOR2_X1 _389_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_182_),
    .ZN(_183_)
  );
  NAND2_X1 _390_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_182_),
    .ZN(_184_)
  );
  XNOR2_X1 _391_ (
    .A(cfg_first_span_log2[3]),
    .B(_182_),
    .ZN(_185_)
  );
  XNOR2_X1 _392_ (
    .A(_173_),
    .B(_176_),
    .ZN(_186_)
  );
  XNOR2_X1 _393_ (
    .A(_177_),
    .B(_178_),
    .ZN(_187_)
  );
  INV_X1 _394_ (
    .A(\u_scheduler.batch_index_q [5]),
    .ZN(_068_)
  );
  AOI22_X1 _395_ (
    .A1(_179_),
    .A2(_185_),
    .B1(_186_),
    .B2(_187_),
    .ZN(_188_)
  );
  OAI21_X1 _396_ (
    .A(_188_),
    .B1(_185_),
    .B2(_179_),
    .ZN(_189_)
  );
  AOI21_X1 _397_ (
    .A(_181_),
    .B1(cfg_last_stage[3]),
    .B2(_061_),
    .ZN(_190_)
  );
  INV_X1 _398_ (
    .A(_190_),
    .ZN(_191_)
  );
  AOI21_X1 _399_ (
    .A(_183_),
    .B1(_184_),
    .B2(_179_),
    .ZN(_192_)
  );
  OAI21_X1 _400_ (
    .A(_189_),
    .B1(_191_),
    .B2(_192_),
    .ZN(_193_)
  );
  NAND2_X1 _401_ (
    .A1(_191_),
    .A2(_192_),
    .ZN(_194_)
  );
  OAI21_X1 _402_ (
    .A(cfg_last_stage[3]),
    .B1(cfg_last_stage[2]),
    .B2(cfg_last_stage[1]),
    .ZN(_195_)
  );
  OAI21_X1 _403_ (
    .A(cfg_first_span_log2[3]),
    .B1(cfg_first_span_log2[2]),
    .B2(cfg_first_span_log2[1]),
    .ZN(_196_)
  );
  NAND3_X1 _404_ (
    .A1(_194_),
    .A2(_195_),
    .A3(_196_),
    .ZN(_197_)
  );
  INV_X1 _405_ (
    .A(\u_scheduler.stage_q [3]),
    .ZN(_069_)
  );
  OR2_X1 _406_ (
    .A1(_193_),
    .A2(_197_),
    .ZN(_198_)
  );
  NAND2_X1 _407_ (
    .A1(enable),
    .A2(\u_controller.state [0]),
    .ZN(_199_)
  );
  NOR4_X1 _408_ (
    .A1(backend_flushed),
    .A2(_103_),
    .A3(_198_),
    .A4(_199_),
    .ZN(_200_)
  );
  AND2_X1 _409_ (
    .A1(scheduler_quiescent),
    .A2(_200_),
    .ZN(ready)
  );
  AND3_X1 _410_ (
    .A1(start),
    .A2(scheduler_quiescent),
    .A3(_200_),
    .ZN(_016_)
  );
  NAND3_X1 _411_ (
    .A1(enable),
    .A2(\u_controller.state [0]),
    .A3(_102_),
    .ZN(_201_)
  );
  NOR3_X1 _412_ (
    .A1(backend_flushed),
    .A2(_198_),
    .A3(_201_),
    .ZN(_202_)
  );
  NAND3_X1 _413_ (
    .A1(start),
    .A2(scheduler_quiescent),
    .A3(_202_),
    .ZN(_203_)
  );
  NAND4_X1 _414_ (
    .A1(rst_n),
    .A2(start),
    .A3(enable),
    .A4(_198_),
    .ZN(_204_)
  );
  NOR3_X1 _415_ (
    .A1(_009_),
    .A2(_103_),
    .A3(_204_),
    .ZN(_205_)
  );
  INV_X1 _416_ (
    .A(\u_scheduler.span_q [3]),
    .ZN(_070_)
  );
  AOI21_X1 _417_ (
    .A(_205_),
    .B1(_203_),
    .B2(error_config),
    .ZN(_206_)
  );
  INV_X1 _418_ (
    .A(_206_),
    .ZN(_053_)
  );
  AOI21_X1 _419_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_203_),
    .ZN(_207_)
  );
  INV_X1 _420_ (
    .A(_207_),
    .ZN(_052_)
  );
  AOI21_X1 _421_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_203_),
    .ZN(_208_)
  );
  INV_X1 _422_ (
    .A(_208_),
    .ZN(_051_)
  );
  AOI21_X1 _423_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_203_),
    .ZN(_209_)
  );
  INV_X1 _424_ (
    .A(_209_),
    .ZN(_050_)
  );
  OAI21_X1 _425_ (
    .A(_098_),
    .B1(_016_),
    .B2(_058_),
    .ZN(_049_)
  );
  NOR2_X1 _426_ (
    .A1(zeroize_req),
    .A2(_016_),
    .ZN(_210_)
  );
  INV_X1 _427_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_071_)
  );
  AOI22_X1 _428_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_016_),
    .B1(_210_),
    .B2(first_span_q[3]),
    .ZN(_211_)
  );
  INV_X1 _429_ (
    .A(_211_),
    .ZN(_048_)
  );
  NOR3_X1 _430_ (
    .A1(_054_),
    .A2(_064_),
    .A3(_103_),
    .ZN(load_start)
  );
  AOI22_X1 _431_ (
    .A1(cfg_span_descending),
    .A2(_016_),
    .B1(_210_),
    .B2(descending_q),
    .ZN(_212_)
  );
  INV_X1 _432_ (
    .A(_212_),
    .ZN(_047_)
  );
  AOI21_X1 _433_ (
    .A(_101_),
    .B1(_094_),
    .B2(_092_),
    .ZN(_213_)
  );
  NAND2_X1 _434_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(_318_[3]),
    .ZN(_214_)
  );
  XOR2_X1 _435_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B(_318_[3]),
    .Z(_215_)
  );
  XOR2_X1 _436_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .B(_318_[2]),
    .Z(_216_)
  );
  NAND2_X1 _437_ (
    .A1(_215_),
    .A2(_216_),
    .ZN(_217_)
  );
  INV_X1 _438_ (
    .A(\u_scheduler.span_q [0]),
    .ZN(_072_)
  );
  OAI22_X1 _439_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_318_[1]),
    .B1(\u_controller.u_stage_counter.stage_count [0]),
    .B2(_318_[0]),
    .ZN(_218_)
  );
  NAND2_X1 _440_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_318_[1]),
    .ZN(_219_)
  );
  AOI21_X1 _441_ (
    .A(_217_),
    .B1(_218_),
    .B2(_219_),
    .ZN(_220_)
  );
  NAND3_X1 _442_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_318_[2]),
    .A3(_215_),
    .ZN(_221_)
  );
  NOR2_X1 _443_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .ZN(_222_)
  );
  NAND4_X1 _444_ (
    .A1(\u_controller.state [1]),
    .A2(_214_),
    .A3(_221_),
    .A4(_222_),
    .ZN(_223_)
  );
  AOI21_X1 _445_ (
    .A(_218_),
    .B1(_318_[0]),
    .B2(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_224_)
  );
  NAND4_X1 _446_ (
    .A1(_215_),
    .A2(_216_),
    .A3(_219_),
    .A4(_224_),
    .ZN(_225_)
  );
  NOR3_X1 _447_ (
    .A1(_213_),
    .A2(_220_),
    .A3(_223_),
    .ZN(_226_)
  );
  OR3_X1 _448_ (
    .A1(_108_),
    .A2(_159_),
    .A3(_165_),
    .ZN(_227_)
  );
  INV_X1 _449_ (
    .A(\u_scheduler.batch_index_q [4]),
    .ZN(_073_)
  );
  INV_X1 _450_ (
    .A(_227_),
    .ZN(stage_done)
  );
  NOR2_X1 _451_ (
    .A1(_055_),
    .A2(_227_),
    .ZN(_011_)
  );
  OAI21_X1 _452_ (
    .A(_226_),
    .B1(_227_),
    .B2(_055_),
    .ZN(_228_)
  );
  NAND2_X1 _453_ (
    .A1(scrub_done),
    .A2(_100_),
    .ZN(_229_)
  );
  NOR3_X1 _454_ (
    .A1(_109_),
    .A2(_165_),
    .A3(_229_),
    .ZN(_230_)
  );
  NAND3_X1 _455_ (
    .A1(scrub_done),
    .A2(_100_),
    .A3(scheduler_quiescent),
    .ZN(_231_)
  );
  NOR2_X1 _456_ (
    .A1(zeroize),
    .A2(_213_),
    .ZN(_232_)
  );
  NAND2_X1 _457_ (
    .A1(\u_controller.state [7]),
    .A2(_232_),
    .ZN(_233_)
  );
  NAND2_X1 _458_ (
    .A1(\u_controller.state [6]),
    .A2(_102_),
    .ZN(_234_)
  );
  OAI21_X1 _459_ (
    .A(_104_),
    .B1(stage_done),
    .B2(_234_),
    .ZN(_017_)
  );
  INV_X1 _460_ (
    .A(zeroize),
    .ZN(_056_)
  );
  INV_X1 _461_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_074_)
  );
  OAI221_X1 _462_ (
    .A(_104_),
    .B1(_230_),
    .B2(_233_),
    .C1(_234_),
    .C2(stage_done),
    .ZN(_235_)
  );
  NOR3_X1 _463_ (
    .A1(_016_),
    .A2(_228_),
    .A3(_235_),
    .ZN(_236_)
  );
  NOR4_X1 _464_ (
    .A1(_079_),
    .A2(_016_),
    .A3(_228_),
    .A4(_235_),
    .ZN(_237_)
  );
  AND2_X1 _465_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_237_),
    .ZN(_238_)
  );
  NAND3_X1 _466_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(\u_controller.u_stage_counter.stage_count [1]),
    .A3(_237_),
    .ZN(_239_)
  );
  NAND2_X1 _467_ (
    .A1(\u_controller.state [1]),
    .A2(_225_),
    .ZN(_240_)
  );
  NAND2_X1 _468_ (
    .A1(_097_),
    .A2(_203_),
    .ZN(_241_)
  );
  AOI21_X1 _469_ (
    .A(_241_),
    .B1(_239_),
    .B2(_060_),
    .ZN(_046_)
  );
  MUX2_X1 _470_ (
    .A(\u_controller.u_stage_counter.last_stage_q [3]),
    .B(cfg_last_stage[3]),
    .S(_016_),
    .Z(_242_)
  );
  AND2_X1 _471_ (
    .A1(_097_),
    .A2(_242_),
    .ZN(_045_)
  );
  INV_X1 _472_ (
    .A(\u_scheduler.batch_index_q [2]),
    .ZN(_075_)
  );
  AOI21_X1 _473_ (
    .A(_054_),
    .B1(_092_),
    .B2(_093_),
    .ZN(active)
  );
  NAND2_X1 _474_ (
    .A1(\u_controller.state [5]),
    .A2(_102_),
    .ZN(_243_)
  );
  NOR2_X1 _475_ (
    .A1(_054_),
    .A2(_243_),
    .ZN(done)
  );
  NAND2_X1 _476_ (
    .A1(backend_flushed),
    .A2(_113_),
    .ZN(_244_)
  );
  AOI21_X1 _477_ (
    .A(_161_),
    .B1(_244_),
    .B2(\u_scheduler.fault_q ),
    .ZN(_245_)
  );
  INV_X1 _478_ (
    .A(_245_),
    .ZN(_044_)
  );
  NAND2_X1 _479_ (
    .A1(batch_retired),
    .A2(_000_),
    .ZN(_246_)
  );
  NAND4_X1 _480_ (
    .A1(\u_scheduler.state [2]),
    .A2(_063_),
    .A3(_113_),
    .A4(_246_),
    .ZN(_247_)
  );
  NOR2_X1 _481_ (
    .A1(batch_retired),
    .A2(_111_),
    .ZN(_248_)
  );
  NAND2_X1 _482_ (
    .A1(backend_flushed),
    .A2(_159_),
    .ZN(_249_)
  );
  INV_X1 _483_ (
    .A(cfg_first_span_log2[2]),
    .ZN(_076_)
  );
  OAI211_X1 _484_ (
    .A(_248_),
    .B(_249_),
    .C1(\u_scheduler.state [2]),
    .C2(_159_),
    .ZN(_250_)
  );
  NAND3_X1 _485_ (
    .A1(_162_),
    .A2(_247_),
    .A3(_250_),
    .ZN(\u_scheduler.next_state [2])
  );
  OAI21_X1 _486_ (
    .A(_222_),
    .B1(_230_),
    .B2(_233_),
    .ZN(_018_)
  );
  NOR4_X1 _487_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(_006_),
    .A4(_159_),
    .ZN(_251_)
  );
  NAND2_X1 _488_ (
    .A1(butterfly_enable),
    .A2(_251_),
    .ZN(_252_)
  );
  NOR2_X1 _489_ (
    .A1(_165_),
    .A2(_252_),
    .ZN(batch_valid)
  );
  NOR3_X1 _490_ (
    .A1(_067_),
    .A2(_103_),
    .A3(_225_),
    .ZN(_013_)
  );
  MUX2_X1 _491_ (
    .A(\u_controller.intt_mode_q ),
    .B(intt_mode),
    .S(_016_),
    .Z(_253_)
  );
  AND2_X1 _492_ (
    .A1(_097_),
    .A2(_253_),
    .ZN(_043_)
  );
  NAND2_X1 _493_ (
    .A1(_000_),
    .A2(_106_),
    .ZN(_254_)
  );
  INV_X1 _494_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_077_)
  );
  OR3_X1 _495_ (
    .A1(_096_),
    .A2(_104_),
    .A3(_254_),
    .ZN(_255_)
  );
  NAND3_X1 _496_ (
    .A1(batch_retired),
    .A2(_110_),
    .A3(_158_),
    .ZN(_256_)
  );
  NOR3_X1 _497_ (
    .A1(_066_),
    .A2(_165_),
    .A3(_252_),
    .ZN(_257_)
  );
  NAND2_X1 _498_ (
    .A1(\u_scheduler.state [0]),
    .A2(_251_),
    .ZN(_258_)
  );
  OAI211_X1 _499_ (
    .A(_255_),
    .B(_256_),
    .C1(_257_),
    .C2(_258_),
    .ZN(_259_)
  );
  AND2_X1 _500_ (
    .A1(_162_),
    .A2(_259_),
    .ZN(\u_scheduler.next_state [0])
  );
  NOR3_X1 _501_ (
    .A1(_004_),
    .A2(_005_),
    .A3(_010_),
    .ZN(_260_)
  );
  NOR4_X1 _502_ (
    .A1(_322_[0]),
    .A2(_065_),
    .A3(_002_),
    .A4(_003_),
    .ZN(_261_)
  );
  NAND4_X1 _503_ (
    .A1(_110_),
    .A2(_158_),
    .A3(_260_),
    .A4(_261_),
    .ZN(_262_)
  );
  NAND3_X1 _504_ (
    .A1(\u_scheduler.state [1]),
    .A2(_158_),
    .A3(_248_),
    .ZN(_263_)
  );
  INV_X1 _505_ (
    .A(cfg_last_stage[0]),
    .ZN(_078_)
  );
  NAND2_X1 _506_ (
    .A1(_262_),
    .A2(_263_),
    .ZN(_264_)
  );
  NOR2_X1 _507_ (
    .A1(_257_),
    .A2(_264_),
    .ZN(_265_)
  );
  NOR3_X1 _508_ (
    .A1(_111_),
    .A2(_257_),
    .A3(_264_),
    .ZN(_266_)
  );
  NAND3_X1 _509_ (
    .A1(_162_),
    .A2(_259_),
    .A3(_266_),
    .ZN(_267_)
  );
  AND4_X1 _510_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_162_),
    .A3(_259_),
    .A4(_266_),
    .ZN(_268_)
  );
  NOR2_X1 _511_ (
    .A1(_075_),
    .A2(_081_),
    .ZN(_269_)
  );
  NOR3_X1 _512_ (
    .A1(_075_),
    .A2(_081_),
    .A3(_083_),
    .ZN(_270_)
  );
  AND3_X1 _513_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(_268_),
    .A3(_270_),
    .ZN(_271_)
  );
  NAND3_X1 _514_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(_268_),
    .A3(_270_),
    .ZN(_272_)
  );
  AND4_X1 _515_ (
    .A1(\u_scheduler.batch_index_q [5]),
    .A2(\u_scheduler.batch_index_q [4]),
    .A3(_268_),
    .A4(_270_),
    .ZN(_273_)
  );
  INV_X1 _516_ (
    .A(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_079_)
  );
  OR2_X1 _517_ (
    .A1(_161_),
    .A2(_255_),
    .ZN(_274_)
  );
  OR3_X1 _518_ (
    .A1(\u_scheduler.next_state [2]),
    .A2(_257_),
    .A3(_264_),
    .ZN(_275_)
  );
  OAI21_X1 _519_ (
    .A(_274_),
    .B1(_275_),
    .B2(_259_),
    .ZN(_276_)
  );
  AOI211_X1 _520_ (
    .A(_273_),
    .B(_276_),
    .C1(_068_),
    .C2(_272_),
    .ZN(_042_)
  );
  OAI22_X1 _521_ (
    .A1(_060_),
    .A2(_274_),
    .B1(_276_),
    .B2(_069_),
    .ZN(_041_)
  );
  OAI22_X1 _522_ (
    .A1(_146_),
    .A2(_274_),
    .B1(_276_),
    .B2(_070_),
    .ZN(_040_)
  );
  OAI22_X1 _523_ (
    .A1(_062_),
    .A2(_274_),
    .B1(_276_),
    .B2(_071_),
    .ZN(_039_)
  );
  AND2_X1 _524_ (
    .A1(_056_),
    .A2(_213_),
    .ZN(_012_)
  );
  AOI21_X1 _525_ (
    .A(_103_),
    .B1(_240_),
    .B2(_064_),
    .ZN(_015_)
  );
  NAND2_X1 _526_ (
    .A1(_008_),
    .A2(_085_),
    .ZN(_277_)
  );
  INV_X1 _527_ (
    .A(_320_[0]),
    .ZN(_080_)
  );
  NAND2_X1 _528_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(_086_),
    .ZN(_278_)
  );
  NOR2_X1 _529_ (
    .A1(_277_),
    .A2(_278_),
    .ZN(_279_)
  );
  NAND2_X1 _530_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_280_)
  );
  NAND2_X1 _531_ (
    .A1(_070_),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_281_)
  );
  NOR2_X1 _532_ (
    .A1(_280_),
    .A2(_281_),
    .ZN(_282_)
  );
  NOR3_X1 _533_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_281_),
    .ZN(_283_)
  );
  NOR2_X1 _534_ (
    .A1(_072_),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_284_)
  );
  NAND2_X1 _535_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(_085_),
    .ZN(_285_)
  );
  NOR2_X1 _536_ (
    .A1(_281_),
    .A2(_285_),
    .ZN(_286_)
  );
  NOR2_X1 _537_ (
    .A1(_277_),
    .A2(_281_),
    .ZN(_287_)
  );
  INV_X1 _538_ (
    .A(\u_scheduler.batch_index_q [1]),
    .ZN(_081_)
  );
  NOR2_X1 _539_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_288_)
  );
  NAND3_X1 _540_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .A3(_288_),
    .ZN(_289_)
  );
  NAND3_X1 _541_ (
    .A1(_008_),
    .A2(\u_scheduler.span_q [1]),
    .A3(_288_),
    .ZN(_290_)
  );
  INV_X1 _542_ (
    .A(_290_),
    .ZN(coeff_addr_b[2])
  );
  AND2_X1 _543_ (
    .A1(_284_),
    .A2(_288_),
    .ZN(coeff_addr_b[1])
  );
  NAND3_X1 _544_ (
    .A1(_008_),
    .A2(_085_),
    .A3(_288_),
    .ZN(coeff_addr_a[10])
  );
  INV_X1 _545_ (
    .A(coeff_addr_a[10]),
    .ZN(coeff_addr_a[11])
  );
  OR2_X1 _546_ (
    .A1(coeff_addr_b[1]),
    .A2(coeff_addr_a[11]),
    .ZN(coeff_addr_b[11])
  );
  INV_X1 _547_ (
    .A(coeff_addr_b[11]),
    .ZN(coeff_addr_b[42])
  );
  NOR2_X1 _548_ (
    .A1(coeff_addr_b[2]),
    .A2(coeff_addr_b[11]),
    .ZN(coeff_addr_a[42])
  );
  INV_X1 _549_ (
    .A(\u_scheduler.batch_index_q [0]),
    .ZN(_082_)
  );
  NAND2_X1 _550_ (
    .A1(_289_),
    .A2(coeff_addr_a[42]),
    .ZN(_291_)
  );
  OR2_X1 _551_ (
    .A1(_287_),
    .A2(_291_),
    .ZN(_292_)
  );
  OR3_X1 _552_ (
    .A1(_283_),
    .A2(_286_),
    .A3(_292_),
    .ZN(_293_)
  );
  OR3_X1 _553_ (
    .A1(_279_),
    .A2(_282_),
    .A3(_293_),
    .ZN(_294_)
  );
  AND2_X1 _554_ (
    .A1(\u_scheduler.batch_index_q [5]),
    .A2(_294_),
    .ZN(coeff_addr_a[9])
  );
  OAI21_X1 _555_ (
    .A(_291_),
    .B1(_290_),
    .B2(_072_),
    .ZN(_295_)
  );
  NAND2_X1 _556_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_295_),
    .ZN(_296_)
  );
  INV_X1 _557_ (
    .A(_296_),
    .ZN(coeff_addr_a[3])
  );
  NAND2_X1 _558_ (
    .A1(coeff_addr_a[42]),
    .A2(_296_),
    .ZN(coeff_addr_a[43])
  );
  NAND3_X1 _559_ (
    .A1(\u_controller.state [0]),
    .A2(_203_),
    .A3(_232_),
    .ZN(_297_)
  );
  INV_X1 _560_ (
    .A(\u_scheduler.batch_index_q [3]),
    .ZN(_083_)
  );
  OAI211_X1 _561_ (
    .A(_243_),
    .B(_297_),
    .C1(_231_),
    .C2(_233_),
    .ZN(_014_)
  );
  NOR2_X1 _562_ (
    .A1(_278_),
    .A2(_285_),
    .ZN(_298_)
  );
  OR2_X1 _563_ (
    .A1(coeff_addr_a[9]),
    .A2(_298_),
    .ZN(coeff_addr_b[9])
  );
  NAND2_X1 _564_ (
    .A1(_284_),
    .A2(coeff_addr_a[11]),
    .ZN(coeff_addr_b[62])
  );
  NAND2_X1 _565_ (
    .A1(coeff_addr_b[11]),
    .A2(coeff_addr_b[62]),
    .ZN(coeff_addr_a[21])
  );
  INV_X1 _566_ (
    .A(coeff_addr_a[21]),
    .ZN(coeff_addr_a[22])
  );
  NAND2_X1 _567_ (
    .A1(_072_),
    .A2(coeff_addr_a[11]),
    .ZN(coeff_addr_b[21])
  );
  OAI22_X1 _568_ (
    .A1(_081_),
    .A2(_292_),
    .B1(_295_),
    .B2(_082_),
    .ZN(coeff_addr_a[4])
  );
  XNOR2_X1 _569_ (
    .A(_286_),
    .B(_292_),
    .ZN(_299_)
  );
  AOI22_X1 _570_ (
    .A1(\u_scheduler.batch_index_q [1]),
    .A2(_292_),
    .B1(_299_),
    .B2(\u_scheduler.batch_index_q [2]),
    .ZN(_300_)
  );
  INV_X1 _571_ (
    .A(\u_controller.state [7]),
    .ZN(_057_)
  );
  INV_X1 _572_ (
    .A(_008_),
    .ZN(_084_)
  );
  INV_X1 _573_ (
    .A(_300_),
    .ZN(coeff_addr_a[5])
  );
  OAI22_X1 _574_ (
    .A1(_083_),
    .A2(_293_),
    .B1(_299_),
    .B2(_075_),
    .ZN(coeff_addr_a[6])
  );
  XNOR2_X1 _575_ (
    .A(_282_),
    .B(_293_),
    .ZN(_301_)
  );
  AOI22_X1 _576_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_293_),
    .B1(_301_),
    .B2(\u_scheduler.batch_index_q [4]),
    .ZN(_302_)
  );
  INV_X1 _577_ (
    .A(_302_),
    .ZN(coeff_addr_a[7])
  );
  OAI22_X1 _578_ (
    .A1(_068_),
    .A2(_294_),
    .B1(_301_),
    .B2(_073_),
    .ZN(coeff_addr_a[8])
  );
  NAND2_X1 _579_ (
    .A1(_084_),
    .A2(coeff_addr_b[1]),
    .ZN(coeff_addr_a[31])
  );
  OAI21_X1 _580_ (
    .A(coeff_addr_a[21]),
    .B1(coeff_addr_b[11]),
    .B2(coeff_addr_b[2]),
    .ZN(coeff_addr_a[62])
  );
  XOR2_X1 _581_ (
    .A(_320_[0]),
    .B(first_span_q[0]),
    .Z(_303_)
  );
  OAI22_X1 _582_ (
    .A1(_072_),
    .A2(_276_),
    .B1(_303_),
    .B2(_274_),
    .ZN(_038_)
  );
  INV_X1 _583_ (
    .A(\u_scheduler.span_q [1]),
    .ZN(_085_)
  );
  OAI22_X1 _584_ (
    .A1(_142_),
    .A2(_274_),
    .B1(_276_),
    .B2(_085_),
    .ZN(_037_)
  );
  OAI22_X1 _585_ (
    .A1(_143_),
    .A2(_274_),
    .B1(_276_),
    .B2(_086_),
    .ZN(_036_)
  );
  OAI22_X1 _586_ (
    .A1(_079_),
    .A2(_274_),
    .B1(_276_),
    .B2(_088_),
    .ZN(_035_)
  );
  OAI22_X1 _587_ (
    .A1(_077_),
    .A2(_274_),
    .B1(_276_),
    .B2(_089_),
    .ZN(_034_)
  );
  OAI22_X1 _588_ (
    .A1(_074_),
    .A2(_274_),
    .B1(_276_),
    .B2(_090_),
    .ZN(_033_)
  );
  NOR2_X1 _589_ (
    .A1(_322_[0]),
    .A2(_267_),
    .ZN(_304_)
  );
  AOI211_X1 _590_ (
    .A(_276_),
    .B(_304_),
    .C1(_082_),
    .C2(_267_),
    .ZN(_032_)
  );
  OAI221_X1 _591_ (
    .A(_274_),
    .B1(_275_),
    .B2(_259_),
    .C1(_268_),
    .C2(\u_scheduler.batch_index_q [1]),
    .ZN(_305_)
  );
  AOI21_X1 _592_ (
    .A(_305_),
    .B1(_268_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_031_)
  );
  AOI21_X1 _593_ (
    .A(\u_scheduler.batch_index_q [2]),
    .B1(\u_scheduler.batch_index_q [1]),
    .B2(_268_),
    .ZN(_306_)
  );
  INV_X1 _594_ (
    .A(\u_scheduler.span_q [2]),
    .ZN(_086_)
  );
  AOI211_X1 _595_ (
    .A(_276_),
    .B(_306_),
    .C1(_268_),
    .C2(_269_),
    .ZN(_030_)
  );
  AOI21_X1 _596_ (
    .A(\u_scheduler.batch_index_q [3]),
    .B1(_268_),
    .B2(_269_),
    .ZN(_307_)
  );
  AOI211_X1 _597_ (
    .A(_276_),
    .B(_307_),
    .C1(_268_),
    .C2(_270_),
    .ZN(_029_)
  );
  AOI21_X1 _598_ (
    .A(\u_scheduler.batch_index_q [4]),
    .B1(_268_),
    .B2(_270_),
    .ZN(_308_)
  );
  NOR3_X1 _599_ (
    .A1(_271_),
    .A2(_276_),
    .A3(_308_),
    .ZN(_028_)
  );
  MUX2_X1 _600_ (
    .A(\u_controller.u_stage_counter.last_stage_q [0]),
    .B(cfg_last_stage[0]),
    .S(_016_),
    .Z(_309_)
  );
  AND2_X1 _601_ (
    .A1(_097_),
    .A2(_309_),
    .ZN(_027_)
  );
  MUX2_X1 _602_ (
    .A(\u_controller.u_stage_counter.last_stage_q [1]),
    .B(cfg_last_stage[1]),
    .S(_016_),
    .Z(_310_)
  );
  AND2_X1 _603_ (
    .A1(_097_),
    .A2(_310_),
    .ZN(_026_)
  );
  MUX2_X1 _604_ (
    .A(\u_controller.u_stage_counter.last_stage_q [2]),
    .B(cfg_last_stage[2]),
    .S(_016_),
    .Z(_311_)
  );
  INV_X1 _605_ (
    .A(first_span_q[1]),
    .ZN(_087_)
  );
  AND2_X1 _606_ (
    .A1(_097_),
    .A2(_311_),
    .ZN(_025_)
  );
  MUX2_X1 _607_ (
    .A(_079_),
    .B(_080_),
    .S(_236_),
    .Z(_312_)
  );
  NOR2_X1 _608_ (
    .A1(_241_),
    .A2(_312_),
    .ZN(_024_)
  );
  NOR2_X1 _609_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_237_),
    .ZN(_313_)
  );
  NOR3_X1 _610_ (
    .A1(_238_),
    .A2(_241_),
    .A3(_313_),
    .ZN(_023_)
  );
  AOI21_X1 _611_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .B1(\u_controller.u_stage_counter.stage_count [1]),
    .B2(_237_),
    .ZN(_314_)
  );
  AOI211_X1 _612_ (
    .A(_241_),
    .B(_314_),
    .C1(\u_controller.u_stage_counter.stage_count [2]),
    .C2(_238_),
    .ZN(_022_)
  );
  AOI22_X1 _613_ (
    .A1(cfg_first_span_log2[0]),
    .A2(_016_),
    .B1(_210_),
    .B2(first_span_q[0]),
    .ZN(_315_)
  );
  INV_X1 _614_ (
    .A(_315_),
    .ZN(_021_)
  );
  AOI22_X1 _615_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_016_),
    .B1(_210_),
    .B2(first_span_q[1]),
    .ZN(_316_)
  );
  INV_X1 _616_ (
    .A(\u_scheduler.stage_q [0]),
    .ZN(_088_)
  );
  INV_X1 _617_ (
    .A(_316_),
    .ZN(_020_)
  );
  AOI22_X1 _618_ (
    .A1(cfg_first_span_log2[2]),
    .A2(_016_),
    .B1(_210_),
    .B2(first_span_q[2]),
    .ZN(_317_)
  );
  INV_X1 _619_ (
    .A(_317_),
    .ZN(_019_)
  );
  NOR2_X1 _620_ (
    .A1(_161_),
    .A2(_265_),
    .ZN(\u_scheduler.next_state [1])
  );
  NAND2_X1 _621_ (
    .A1(_290_),
    .A2(coeff_addr_a[21]),
    .ZN(coeff_addr_b[22])
  );
  NAND2_X1 _622_ (
    .A1(_289_),
    .A2(_296_),
    .ZN(coeff_addr_b[3])
  );
  NAND3_X1 _623_ (
    .A1(_082_),
    .A2(_289_),
    .A3(coeff_addr_a[42]),
    .ZN(coeff_addr_b[43])
  );
  OR2_X1 _624_ (
    .A1(_287_),
    .A2(coeff_addr_a[4]),
    .ZN(coeff_addr_b[4])
  );
  OAI21_X1 _625_ (
    .A(_300_),
    .B1(_285_),
    .B2(_281_),
    .ZN(coeff_addr_b[5])
  );
  OR2_X1 _626_ (
    .A1(_283_),
    .A2(coeff_addr_a[6]),
    .ZN(coeff_addr_b[6])
  );
  INV_X1 _627_ (
    .A(\u_scheduler.stage_q [1]),
    .ZN(_089_)
  );
  OAI21_X1 _628_ (
    .A(_302_),
    .B1(_281_),
    .B2(_280_),
    .ZN(coeff_addr_b[7])
  );
  OR2_X1 _629_ (
    .A1(_279_),
    .A2(coeff_addr_a[8]),
    .ZN(coeff_addr_b[8])
  );
  INV_X1 _630_ (
    .A(\u_scheduler.stage_q [2]),
    .ZN(_090_)
  );
  NOR2_X1 _631_ (
    .A1(_054_),
    .A2(_055_),
    .ZN(butterfly_enable)
  );
  AND2_X1 _632_ (
    .A1(rst_n),
    .A2(_009_),
    .ZN(busy)
  );
  NOR3_X1 _633_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_091_)
  );
  INV_X1 _634_ (
    .A(error_controller),
    .ZN(_058_)
  );
  NOR2_X1 _635_ (
    .A1(\u_controller.state [4]),
    .A2(\u_controller.state [2]),
    .ZN(_092_)
  );
  NOR2_X1 _636_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .ZN(_093_)
  );
  NOR3_X1 _637_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .A3(\u_controller.state [5]),
    .ZN(_094_)
  );
  NAND2_X1 _638_ (
    .A1(_092_),
    .A2(_094_),
    .ZN(_095_)
  );
  NAND2_X1 _639_ (
    .A1(rst_n),
    .A2(_057_),
    .ZN(_096_)
  );
  NOR3_X1 _640_ (
    .A1(\u_controller.state [0]),
    .A2(_095_),
    .A3(_096_),
    .ZN(transform_abort)
  );
  NAND3_X1 _641_ (
    .A1(_059_),
    .A2(_092_),
    .A3(_093_),
    .ZN(_097_)
  );
  OR4_X1 _642_ (
    .A1(\u_controller.state [3]),
    .A2(\u_controller.state [5]),
    .A3(_096_),
    .A4(_097_),
    .ZN(_098_)
  );
  NAND2_X1 _643_ (
    .A1(_091_),
    .A2(_098_),
    .ZN(_099_)
  );
  INV_X1 _644_ (
    .A(_099_),
    .ZN(_100_)
  );
  INV_X1 _645_ (
    .A(\u_controller.state [0]),
    .ZN(_059_)
  );
  NOR2_X1 _646_ (
    .A1(abort_req),
    .A2(_099_),
    .ZN(_101_)
  );
  NOR3_X1 _647_ (
    .A1(abort_req),
    .A2(zeroize),
    .A3(_099_),
    .ZN(_102_)
  );
  NAND2_X1 _648_ (
    .A1(_056_),
    .A2(_101_),
    .ZN(_103_)
  );
  NAND2_X1 _649_ (
    .A1(\u_controller.state [2]),
    .A2(_102_),
    .ZN(_104_)
  );
  NAND3_X1 _650_ (
    .A1(rst_n),
    .A2(\u_controller.state [2]),
    .A3(_102_),
    .ZN(_105_)
  );
  INV_X1 _651_ (
    .A(_105_),
    .ZN(stage_start)
  );
  NOR3_X1 _652_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(\u_scheduler.state [1]),
    .ZN(_106_)
  );
  NOR3_X1 _653_ (
    .A1(\u_scheduler.state [2]),
    .A2(_007_),
    .A3(_006_),
    .ZN(_107_)
  );
  OR3_X1 _654_ (
    .A1(\u_scheduler.state [2]),
    .A2(_007_),
    .A3(_006_),
    .ZN(_108_)
  );
  NOR2_X1 _655_ (
    .A1(_106_),
    .A2(_107_),
    .ZN(_109_)
  );
  INV_X1 _656_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .ZN(_060_)
  );
  NOR3_X1 _657_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_007_),
    .ZN(_110_)
  );
  OR3_X1 _658_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_007_),
    .ZN(_111_)
  );
  AOI221_X1 _659_ (
    .A(\u_scheduler.state [2]),
    .B1(_007_),
    .B2(\u_scheduler.state [1]),
    .C1(_006_),
    .C2(\u_scheduler.state [0]),
    .ZN(_112_)
  );
  NOR3_X1 _660_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(_001_),
    .ZN(_113_)
  );
  AND3_X1 _661_ (
    .A1(_320_[0]),
    .A2(_319_[2]),
    .A3(_319_[1]),
    .ZN(_114_)
  );
  AOI21_X1 _662_ (
    .A(descending_q),
    .B1(_347_[3]),
    .B2(_114_),
    .ZN(_115_)
  );
  OR2_X1 _663_ (
    .A1(_347_[3]),
    .A2(_114_),
    .ZN(_116_)
  );
  AOI22_X1 _664_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(descending_q),
    .B1(_115_),
    .B2(_116_),
    .ZN(_117_)
  );
  NAND2_X1 _665_ (
    .A1(first_span_q[3]),
    .A2(_117_),
    .ZN(_118_)
  );
  NOR2_X1 _666_ (
    .A1(first_span_q[3]),
    .A2(_117_),
    .ZN(_119_)
  );
  INV_X1 _667_ (
    .A(cfg_span_descending),
    .ZN(_061_)
  );
  OR2_X1 _668_ (
    .A1(first_span_q[3]),
    .A2(_117_),
    .ZN(_120_)
  );
  AOI21_X1 _669_ (
    .A(_319_[2]),
    .B1(_319_[1]),
    .B2(_320_[0]),
    .ZN(_121_)
  );
  NOR3_X1 _670_ (
    .A1(descending_q),
    .A2(_114_),
    .A3(_121_),
    .ZN(_122_)
  );
  AOI21_X1 _671_ (
    .A(_122_),
    .B1(\u_controller.u_stage_counter.stage_count [2]),
    .B2(descending_q),
    .ZN(_123_)
  );
  AND2_X1 _672_ (
    .A1(first_span_q[2]),
    .A2(_123_),
    .ZN(_124_)
  );
  NAND2_X1 _673_ (
    .A1(first_span_q[2]),
    .A2(_123_),
    .ZN(_125_)
  );
  XOR2_X1 _674_ (
    .A(_320_[0]),
    .B(_319_[1]),
    .Z(_126_)
  );
  MUX2_X1 _675_ (
    .A(_126_),
    .B(\u_controller.u_stage_counter.stage_count [1]),
    .S(descending_q),
    .Z(_127_)
  );
  NOR2_X1 _676_ (
    .A1(_087_),
    .A2(_127_),
    .ZN(_128_)
  );
  OR2_X1 _677_ (
    .A1(_087_),
    .A2(_127_),
    .ZN(_129_)
  );
  INV_X1 _678_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_062_)
  );
  NOR2_X1 _679_ (
    .A1(_320_[0]),
    .A2(first_span_q[0]),
    .ZN(_130_)
  );
  INV_X1 _680_ (
    .A(_130_),
    .ZN(_131_)
  );
  AND2_X1 _681_ (
    .A1(_087_),
    .A2(_127_),
    .ZN(_132_)
  );
  XNOR2_X1 _682_ (
    .A(first_span_q[1]),
    .B(_127_),
    .ZN(_133_)
  );
  AOI21_X1 _683_ (
    .A(_128_),
    .B1(_131_),
    .B2(_133_),
    .ZN(_134_)
  );
  OAI21_X1 _684_ (
    .A(_129_),
    .B1(_130_),
    .B2(_132_),
    .ZN(_135_)
  );
  OR2_X1 _685_ (
    .A1(first_span_q[2]),
    .A2(_123_),
    .ZN(_136_)
  );
  XNOR2_X1 _686_ (
    .A(first_span_q[2]),
    .B(_123_),
    .ZN(_137_)
  );
  AOI21_X1 _687_ (
    .A(_124_),
    .B1(_135_),
    .B2(_136_),
    .ZN(_138_)
  );
  OAI211_X1 _688_ (
    .A(_118_),
    .B(_125_),
    .C1(_134_),
    .C2(_137_),
    .ZN(_139_)
  );
  INV_X1 _689_ (
    .A(backend_flushed),
    .ZN(_063_)
  );
  AOI221_X1 _690_ (
    .A(descending_q),
    .B1(_347_[3]),
    .B2(_114_),
    .C1(_120_),
    .C2(_139_),
    .ZN(_140_)
  );
  AOI211_X1 _691_ (
    .A(_115_),
    .B(_119_),
    .C1(_138_),
    .C2(_118_),
    .ZN(_141_)
  );
  XNOR2_X1 _692_ (
    .A(_131_),
    .B(_133_),
    .ZN(_142_)
  );
  XNOR2_X1 _693_ (
    .A(_134_),
    .B(_137_),
    .ZN(_143_)
  );
  AND2_X1 _694_ (
    .A1(_142_),
    .A2(_143_),
    .ZN(_144_)
  );
  NAND2_X1 _695_ (
    .A1(_118_),
    .A2(_120_),
    .ZN(_145_)
  );
  XNOR2_X1 _696_ (
    .A(_138_),
    .B(_145_),
    .ZN(_146_)
  );
  NAND3_X1 _697_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_319_[2]),
    .A3(_319_[1]),
    .ZN(_147_)
  );
  AOI21_X1 _698_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .B1(\u_controller.u_stage_counter.stage_count [1]),
    .B2(_319_[2]),
    .ZN(_148_)
  );
  NOR2_X1 _699_ (
    .A1(_060_),
    .A2(_148_),
    .ZN(_149_)
  );
  DFFS_X1 _700_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_controller.state [0]),
    .QN(_009_),
    .SN(rst_n)
  );
  DFFR_X1 _701_ (
    .CK(clk),
    .D(_011_),
    .Q(\u_controller.state [1]),
    .QN(_346_),
    .RN(rst_n)
  );
  DFFR_X1 _702_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_controller.state [2]),
    .QN(_345_),
    .RN(rst_n)
  );
  DFFR_X1 _703_ (
    .CK(clk),
    .D(_012_),
    .Q(\u_controller.state [3]),
    .QN(_344_),
    .RN(rst_n)
  );
  DFFR_X1 _704_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_controller.state [4]),
    .QN(_343_),
    .RN(rst_n)
  );
  DFFR_X1 _705_ (
    .CK(clk),
    .D(_013_),
    .Q(\u_controller.state [5]),
    .QN(_342_),
    .RN(rst_n)
  );
  DFFR_X1 _706_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.state [6]),
    .QN(_341_),
    .RN(rst_n)
  );
  DFFR_X1 _707_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.state [7]),
    .QN(_334_),
    .RN(rst_n)
  );
  DFFR_X1 _708_ (
    .CK(clk),
    .D(_039_),
    .Q(\u_scheduler.intt_q ),
    .QN(_333_),
    .RN(rst_n)
  );
  DFFR_X1 _709_ (
    .CK(clk),
    .D(_038_),
    .Q(\u_scheduler.span_q [0]),
    .QN(_008_),
    .RN(rst_n)
  );
  DFFR_X1 _710_ (
    .CK(clk),
    .D(_037_),
    .Q(\u_scheduler.span_q [1]),
    .QN(_335_),
    .RN(rst_n)
  );
  DFFR_X1 _711_ (
    .CK(clk),
    .D(_036_),
    .Q(\u_scheduler.span_q [2]),
    .QN(_336_),
    .RN(rst_n)
  );
  DFFR_X1 _712_ (
    .CK(clk),
    .D(_040_),
    .Q(\u_scheduler.span_q [3]),
    .QN(_332_),
    .RN(rst_n)
  );
  DFFR_X1 _713_ (
    .CK(clk),
    .D(_035_),
    .Q(\u_scheduler.stage_q [0]),
    .QN(_337_),
    .RN(rst_n)
  );
  DFFR_X1 _714_ (
    .CK(clk),
    .D(_034_),
    .Q(\u_scheduler.stage_q [1]),
    .QN(_338_),
    .RN(rst_n)
  );
  DFFR_X1 _715_ (
    .CK(clk),
    .D(_033_),
    .Q(\u_scheduler.stage_q [2]),
    .QN(_339_),
    .RN(rst_n)
  );
  DFFR_X1 _716_ (
    .CK(clk),
    .D(_041_),
    .Q(\u_scheduler.stage_q [3]),
    .QN(_331_),
    .RN(rst_n)
  );
  DFFR_X1 _717_ (
    .CK(clk),
    .D(_032_),
    .Q(\u_scheduler.batch_index_q [0]),
    .QN(_322_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _718_ (
    .CK(clk),
    .D(_031_),
    .Q(\u_scheduler.batch_index_q [1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _719_ (
    .CK(clk),
    .D(_030_),
    .Q(\u_scheduler.batch_index_q [2]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _720_ (
    .CK(clk),
    .D(_029_),
    .Q(\u_scheduler.batch_index_q [3]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _721_ (
    .CK(clk),
    .D(_028_),
    .Q(\u_scheduler.batch_index_q [4]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _722_ (
    .CK(clk),
    .D(_042_),
    .Q(\u_scheduler.batch_index_q [5]),
    .QN(_010_),
    .RN(rst_n)
  );
  DFFR_X1 _723_ (
    .CK(clk),
    .D(_043_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_330_),
    .RN(rst_n)
  );
  DFFR_X1 _724_ (
    .CK(clk),
    .D(_044_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _725_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_controller.u_stage_counter.last_stage_q [0]),
    .QN(_318_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _726_ (
    .CK(clk),
    .D(_026_),
    .Q(\u_controller.u_stage_counter.last_stage_q [1]),
    .QN(_318_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _727_ (
    .CK(clk),
    .D(_025_),
    .Q(\u_controller.u_stage_counter.last_stage_q [2]),
    .QN(_318_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _728_ (
    .CK(clk),
    .D(_045_),
    .Q(\u_controller.u_stage_counter.last_stage_q [3]),
    .QN(_318_[3]),
    .RN(rst_n)
  );
  DFFR_X1 _729_ (
    .CK(clk),
    .D(_024_),
    .Q(\u_controller.u_stage_counter.stage_count [0]),
    .QN(_320_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _730_ (
    .CK(clk),
    .D(_023_),
    .Q(\u_controller.u_stage_counter.stage_count [1]),
    .QN(_319_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _731_ (
    .CK(clk),
    .D(_022_),
    .Q(\u_controller.u_stage_counter.stage_count [2]),
    .QN(_319_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _732_ (
    .CK(clk),
    .D(_046_),
    .Q(\u_controller.u_stage_counter.stage_count [3]),
    .QN(_347_[3]),
    .RN(rst_n)
  );
  DFFR_X1 _733_ (
    .CK(clk),
    .D(_047_),
    .Q(descending_q),
    .QN(_329_),
    .RN(rst_n)
  );
  DFFR_X1 _734_ (
    .CK(clk),
    .D(_021_),
    .Q(first_span_q[0]),
    .QN(_340_),
    .RN(rst_n)
  );
  DFFR_X1 _735_ (
    .CK(clk),
    .D(_020_),
    .Q(first_span_q[1]),
    .QN(_321_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _736_ (
    .CK(clk),
    .D(_019_),
    .Q(first_span_q[2]),
    .QN(_321_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _737_ (
    .CK(clk),
    .D(_048_),
    .Q(first_span_q[3]),
    .QN(_328_),
    .RN(rst_n)
  );
  DFFR_X1 _738_ (
    .CK(clk),
    .D(_049_),
    .Q(error_controller),
    .QN(_327_),
    .RN(rst_n)
  );
  DFFR_X1 _739_ (
    .CK(clk),
    .D(_050_),
    .Q(error_scheduler),
    .QN(_326_),
    .RN(rst_n)
  );
  DFFR_X1 _740_ (
    .CK(clk),
    .D(_051_),
    .Q(error_datapath),
    .QN(_325_),
    .RN(rst_n)
  );
  DFFR_X1 _741_ (
    .CK(clk),
    .D(_052_),
    .Q(error_ecc),
    .QN(_324_),
    .RN(rst_n)
  );
  DFFR_X1 _742_ (
    .CK(clk),
    .D(_053_),
    .Q(error_config),
    .QN(_323_),
    .RN(rst_n)
  );
  DFFR_X1 _743_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _744_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_007_),
    .RN(rst_n)
  );
  DFFR_X1 _745_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_001_),
    .RN(rst_n)
  );
  assign _322_[5:1] = \u_scheduler.batch_index_q [5:1];
  assign { _347_[4], _347_[2:0] } = { 1'h1, _319_[2:1], _320_[0] };
  assign { _319_[3], _319_[0] } = { \u_controller.u_stage_counter.stage_count [3], \u_controller.u_stage_counter.stage_count [0] };
  assign { _321_[3], _321_[0] } = { first_span_q[3], first_span_q[0] };
  assign \u_scheduler.decode_lanes.ordinal  = { 1'h0, \u_scheduler.batch_index_q , 3'h7 };
  assign \u_scheduler.distance_mask [2:0] = { coeff_addr_b[2:1], coeff_addr_a[11] };
  assign \u_scheduler.low_mask [2:0] = { coeff_addr_a[42], coeff_addr_a[21], coeff_addr_a[10] };
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = { \u_scheduler.batch_index_q , 3'h7, \u_scheduler.batch_index_q , 3'h6, \u_scheduler.batch_index_q , 3'h5, \u_scheduler.batch_index_q , 3'h4, \u_scheduler.batch_index_q , 3'h3, \u_scheduler.batch_index_q , 3'h2, \u_scheduler.batch_index_q , 3'h1, \u_scheduler.batch_index_q , 3'h0 };
  assign \u_scheduler.coeff_addr_b  = { coeff_addr_b[9:4], coeff_addr_b[43], coeff_addr_b[62], 2'h3, coeff_addr_b[9:4], coeff_addr_b[43], coeff_addr_b[62], coeff_addr_b[21], coeff_addr_a[11], coeff_addr_b[9:4], coeff_addr_b[43:42], coeff_addr_b[11], 1'h1, coeff_addr_b[9:4], coeff_addr_b[43:42], coeff_addr_b[1], coeff_addr_a[11], coeff_addr_b[9:3], coeff_addr_b[22], 2'h3, coeff_addr_b[9:3], coeff_addr_b[22:21], coeff_addr_a[11], coeff_addr_b[9:2], coeff_addr_b[11], 1'h1, coeff_addr_b[9:1], coeff_addr_a[11] };
  assign \u_scheduler.coeff_addr_a  = { coeff_addr_a[9:4], coeff_addr_a[43], coeff_addr_a[62], coeff_addr_a[31], coeff_addr_a[10:4], coeff_addr_a[43], coeff_addr_a[62], coeff_addr_a[21], 1'h0, coeff_addr_a[9:4], coeff_addr_a[43:42], coeff_addr_a[11:4], coeff_addr_a[43:42], 2'h0, coeff_addr_a[9:3], coeff_addr_a[22], coeff_addr_a[31], coeff_addr_a[10:3], coeff_addr_a[22:21], 1'h0, coeff_addr_a[9:3], 1'h0, coeff_addr_a[11:3], 3'h0 };
  assign \u_scheduler.lane_valid  = { batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid };
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.next_state [3] = 1'h0;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = { \u_scheduler.batch_index_q , 3'h7, \u_scheduler.batch_index_q , 3'h6, \u_scheduler.batch_index_q , 3'h5, \u_scheduler.batch_index_q , 3'h4, \u_scheduler.batch_index_q , 3'h3, \u_scheduler.batch_index_q , 3'h2, \u_scheduler.batch_index_q , 3'h1, \u_scheduler.batch_index_q , 3'h0 };
  assign { coeff_addr_b[79:63], coeff_addr_b[61:44], coeff_addr_b[41:23], coeff_addr_b[20:12], coeff_addr_b[10], coeff_addr_b[0] } = { coeff_addr_b[9:4], coeff_addr_b[43], coeff_addr_b[62], 2'h3, coeff_addr_b[9:4], coeff_addr_b[43], coeff_addr_b[21], coeff_addr_a[11], coeff_addr_b[9:4], coeff_addr_b[43:42], coeff_addr_b[11], 1'h1, coeff_addr_b[9:4], coeff_addr_b[1], coeff_addr_a[11], coeff_addr_b[9:3], coeff_addr_b[22], 2'h3, coeff_addr_b[9:3], coeff_addr_a[11], coeff_addr_b[9:2], 1'h1, coeff_addr_a[11] };
  assign { coeff_addr_a[79:63], coeff_addr_a[61:44], coeff_addr_a[41:32], coeff_addr_a[30:23], coeff_addr_a[20:12], coeff_addr_a[2:0] } = { coeff_addr_a[9:4], coeff_addr_a[43], coeff_addr_a[62], coeff_addr_a[31], coeff_addr_a[10:4], coeff_addr_a[43], coeff_addr_a[21], 1'h0, coeff_addr_a[9:4], coeff_addr_a[43:42], coeff_addr_a[11:4], 2'h0, coeff_addr_a[9:3], coeff_addr_a[22], coeff_addr_a[10:3], 1'h0, coeff_addr_a[9:3], 4'h0 };
  assign lane_valid = { batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid };
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
