/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input [3:0] cfg_last_stage;
  wire [3:0] cfg_last_stage;
  input [3:0] cfg_first_span_log2;
  wire [3:0] cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output [3:0] stage_count;
  wire [3:0] stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output lane_valid;
  wire lane_valid;
  output [8:0] coeff_addr_a;
  wire [8:0] coeff_addr_a;
  output [8:0] coeff_addr_b;
  wire [8:0] coeff_addr_b;
  output [7:0] butterfly_index;
  wire [7:0] butterfly_index;
  output [3:0] batch_stage;
  wire [3:0] batch_stage;
  output [3:0] batch_span_log2;
  wire [3:0] batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire [3:0] _311_;
  wire [0:0] _312_;
  wire [0:0] _313_;
  wire [7:0] _314_;
  wire [3:0] _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire [4:0] _338_;
  wire descending_q;
  wire [3:0] first_span_q;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire [3:0] \u_controller.cfg_last_stage ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire [3:0] \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire [3:0] \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.clk ;
  wire [3:0] \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire [3:0] \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire [7:0] \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire [3:0] \u_scheduler.batch_span_log2 ;
  wire [3:0] \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [7:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [8:0] \u_scheduler.coeff_addr_a ;
  wire [8:0] \u_scheduler.coeff_addr_b ;
  wire [8:0] \u_scheduler.decode_lanes.ordinal ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire \u_scheduler.lane_valid ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.rst_n ;
  wire [3:0] \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire [3:0] \u_scheduler.span_q ;
  wire [3:0] \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire [3:0] \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _339_ (
    .A(cfg_first_span_log2[3]),
    .ZN(_061_)
  );
  INV_X1 _340_ (
    .A(abort_req),
    .ZN(_062_)
  );
  INV_X1 _341_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_071_)
  );
  XNOR2_X1 _342_ (
    .A(cfg_last_stage[3]),
    .B(_155_),
    .ZN(_156_)
  );
  NAND2_X1 _343_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_156_),
    .ZN(_157_)
  );
  XNOR2_X1 _344_ (
    .A(_061_),
    .B(_156_),
    .ZN(_158_)
  );
  AOI21_X1 _345_ (
    .A(cfg_span_descending),
    .B1(_086_),
    .B2(_094_),
    .ZN(_159_)
  );
  XNOR2_X1 _346_ (
    .A(cfg_last_stage[2]),
    .B(_159_),
    .ZN(_160_)
  );
  OR2_X1 _347_ (
    .A1(cfg_first_span_log2[2]),
    .A2(_160_),
    .ZN(_161_)
  );
  NAND2_X1 _348_ (
    .A1(cfg_last_stage[1]),
    .A2(cfg_last_stage[0]),
    .ZN(_162_)
  );
  AOI22_X1 _349_ (
    .A1(cfg_span_descending),
    .A2(cfg_last_stage[1]),
    .B1(_159_),
    .B2(_162_),
    .ZN(_163_)
  );
  OR2_X1 _350_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_163_),
    .ZN(_164_)
  );
  NAND2_X1 _351_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_163_),
    .ZN(_165_)
  );
  INV_X1 _352_ (
    .A(cfg_first_span_log2[2]),
    .ZN(_072_)
  );
  OAI211_X1 _353_ (
    .A(_164_),
    .B(_165_),
    .C1(cfg_first_span_log2[0]),
    .C2(_094_),
    .ZN(_166_)
  );
  NAND2_X1 _354_ (
    .A1(cfg_first_span_log2[2]),
    .A2(_160_),
    .ZN(_167_)
  );
  NAND3_X1 _355_ (
    .A1(_165_),
    .A2(_166_),
    .A3(_167_),
    .ZN(_168_)
  );
  NAND3_X1 _356_ (
    .A1(_158_),
    .A2(_161_),
    .A3(_168_),
    .ZN(_169_)
  );
  NAND2_X1 _357_ (
    .A1(_157_),
    .A2(_169_),
    .ZN(_170_)
  );
  AOI21_X1 _358_ (
    .A(cfg_span_descending),
    .B1(_079_),
    .B2(_154_),
    .ZN(_171_)
  );
  NOR2_X1 _359_ (
    .A1(_170_),
    .A2(_171_),
    .ZN(_172_)
  );
  NAND3_X1 _360_ (
    .A1(_072_),
    .A2(_081_),
    .A3(_083_),
    .ZN(_173_)
  );
  NAND2_X1 _361_ (
    .A1(_170_),
    .A2(_171_),
    .ZN(_174_)
  );
  AOI21_X1 _362_ (
    .A(_158_),
    .B1(_161_),
    .B2(_168_),
    .ZN(_175_)
  );
  INV_X1 _363_ (
    .A(backend_flushed),
    .ZN(_073_)
  );
  OAI211_X1 _364_ (
    .A(_161_),
    .B(_167_),
    .C1(_081_),
    .C2(cfg_last_stage[0]),
    .ZN(_176_)
  );
  NOR2_X1 _365_ (
    .A1(_166_),
    .A2(_176_),
    .ZN(_177_)
  );
  NOR2_X1 _366_ (
    .A1(_175_),
    .A2(_177_),
    .ZN(_178_)
  );
  AOI221_X1 _367_ (
    .A(_172_),
    .B1(_173_),
    .B2(cfg_first_span_log2[3]),
    .C1(_178_),
    .C2(_169_),
    .ZN(_179_)
  );
  OAI211_X1 _368_ (
    .A(_174_),
    .B(_179_),
    .C1(_079_),
    .C2(_154_),
    .ZN(_180_)
  );
  AND2_X1 _369_ (
    .A1(enable),
    .A2(_110_),
    .ZN(_181_)
  );
  NAND3_X1 _370_ (
    .A1(_073_),
    .A2(\u_controller.state [0]),
    .A3(_181_),
    .ZN(_182_)
  );
  NOR3_X1 _371_ (
    .A1(_153_),
    .A2(_180_),
    .A3(_182_),
    .ZN(ready)
  );
  NAND2_X1 _372_ (
    .A1(start),
    .A2(ready),
    .ZN(_183_)
  );
  INV_X1 _373_ (
    .A(_183_),
    .ZN(_021_)
  );
  INV_X1 _374_ (
    .A(\u_controller.state [1]),
    .ZN(_074_)
  );
  NAND4_X1 _375_ (
    .A1(rst_n),
    .A2(start),
    .A3(_180_),
    .A4(_181_),
    .ZN(_184_)
  );
  OAI22_X1 _376_ (
    .A1(_066_),
    .A2(_021_),
    .B1(_184_),
    .B2(_014_),
    .ZN(_060_)
  );
  AOI21_X1 _377_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_183_),
    .ZN(_185_)
  );
  INV_X1 _378_ (
    .A(_185_),
    .ZN(_059_)
  );
  AOI21_X1 _379_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_183_),
    .ZN(_186_)
  );
  INV_X1 _380_ (
    .A(_186_),
    .ZN(_058_)
  );
  AOI21_X1 _381_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_183_),
    .ZN(_187_)
  );
  INV_X1 _382_ (
    .A(_187_),
    .ZN(_057_)
  );
  AOI21_X1 _383_ (
    .A(_107_),
    .B1(_183_),
    .B2(error_controller),
    .ZN(_188_)
  );
  INV_X1 _384_ (
    .A(_188_),
    .ZN(_056_)
  );
  INV_X1 _385_ (
    .A(cfg_span_descending),
    .ZN(_075_)
  );
  NOR2_X1 _386_ (
    .A1(zeroize_req),
    .A2(_021_),
    .ZN(_189_)
  );
  NAND2_X1 _387_ (
    .A1(first_span_q[3]),
    .A2(_189_),
    .ZN(_190_)
  );
  OAI21_X1 _388_ (
    .A(_190_),
    .B1(_183_),
    .B2(_061_),
    .ZN(_055_)
  );
  NAND2_X1 _389_ (
    .A1(descending_q),
    .A2(_189_),
    .ZN(_191_)
  );
  OAI21_X1 _390_ (
    .A(_191_),
    .B1(_183_),
    .B2(_075_),
    .ZN(_054_)
  );
  NOR4_X1 _391_ (
    .A1(_099_),
    .A2(_149_),
    .A3(_151_),
    .A4(_152_),
    .ZN(stage_done)
  );
  AND2_X1 _392_ (
    .A1(\u_controller.state [6]),
    .A2(stage_done),
    .ZN(_016_)
  );
  AOI21_X1 _393_ (
    .A(_104_),
    .B1(_108_),
    .B2(_062_),
    .ZN(_192_)
  );
  AOI211_X1 _394_ (
    .A(zeroize),
    .B(_104_),
    .C1(_108_),
    .C2(_062_),
    .ZN(_017_)
  );
  XNOR2_X1 _395_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B(_311_[3]),
    .ZN(_193_)
  );
  INV_X1 _396_ (
    .A(\u_controller.state [7]),
    .ZN(_076_)
  );
  NAND2_X1 _397_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_311_[2]),
    .ZN(_194_)
  );
  AOI21_X1 _398_ (
    .A(_193_),
    .B1(_311_[2]),
    .B2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_195_)
  );
  OAI21_X1 _399_ (
    .A(_195_),
    .B1(_311_[2]),
    .B2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_196_)
  );
  OAI22_X1 _400_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_311_[0]),
    .B1(_311_[1]),
    .B2(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_197_)
  );
  NAND2_X1 _401_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_311_[1]),
    .ZN(_198_)
  );
  AOI21_X1 _402_ (
    .A(_196_),
    .B1(_197_),
    .B2(_198_),
    .ZN(_199_)
  );
  AOI211_X1 _403_ (
    .A(zeroize),
    .B(\u_controller.state [3]),
    .C1(_311_[3]),
    .C2(\u_controller.u_stage_counter.stage_count [3]),
    .ZN(_200_)
  );
  OAI211_X1 _404_ (
    .A(\u_controller.state [1]),
    .B(_200_),
    .C1(_194_),
    .C2(_193_),
    .ZN(_201_)
  );
  AOI21_X1 _405_ (
    .A(_197_),
    .B1(_311_[0]),
    .B2(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_202_)
  );
  NAND2_X1 _406_ (
    .A1(_198_),
    .A2(_202_),
    .ZN(_203_)
  );
  INV_X1 _407_ (
    .A(\u_scheduler.batch_index_q [7]),
    .ZN(_077_)
  );
  OR2_X1 _408_ (
    .A1(_196_),
    .A2(_203_),
    .ZN(_204_)
  );
  OR4_X1 _409_ (
    .A1(_016_),
    .A2(_017_),
    .A3(_199_),
    .A4(_201_),
    .ZN(_205_)
  );
  NAND2_X1 _410_ (
    .A1(\u_controller.state [6]),
    .A2(_110_),
    .ZN(_206_)
  );
  OAI21_X1 _411_ (
    .A(_112_),
    .B1(stage_done),
    .B2(_206_),
    .ZN(_022_)
  );
  NOR2_X1 _412_ (
    .A1(zeroize),
    .A2(_192_),
    .ZN(_207_)
  );
  NAND2_X1 _413_ (
    .A1(\u_controller.state [7]),
    .A2(_207_),
    .ZN(_208_)
  );
  NOR3_X1 _414_ (
    .A1(_064_),
    .A2(_107_),
    .A3(_109_),
    .ZN(_209_)
  );
  NAND2_X1 _415_ (
    .A1(scheduler_quiescent),
    .A2(_209_),
    .ZN(_210_)
  );
  AOI21_X1 _416_ (
    .A(_208_),
    .B1(_209_),
    .B2(scheduler_quiescent),
    .ZN(_211_)
  );
  NOR4_X1 _417_ (
    .A1(_021_),
    .A2(_205_),
    .A3(_022_),
    .A4(_211_),
    .ZN(_212_)
  );
  INV_X1 _418_ (
    .A(_313_),
    .ZN(_078_)
  );
  AND3_X1 _419_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(\u_controller.u_stage_counter.stage_count [1]),
    .A3(_212_),
    .ZN(_213_)
  );
  AND2_X1 _420_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_213_),
    .ZN(_214_)
  );
  NAND3_X1 _421_ (
    .A1(\u_controller.state [1]),
    .A2(_110_),
    .A3(_204_),
    .ZN(_215_)
  );
  AOI21_X1 _422_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B1(_213_),
    .B2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_216_)
  );
  NAND2_X1 _423_ (
    .A1(_106_),
    .A2(_183_),
    .ZN(_217_)
  );
  NOR2_X1 _424_ (
    .A1(_216_),
    .A2(_217_),
    .ZN(_053_)
  );
  OAI21_X1 _425_ (
    .A(_106_),
    .B1(_183_),
    .B2(cfg_last_stage[3]),
    .ZN(_218_)
  );
  AOI21_X1 _426_ (
    .A(_218_),
    .B1(_183_),
    .B2(_070_),
    .ZN(_052_)
  );
  AND2_X1 _427_ (
    .A1(rst_n),
    .A2(\u_controller.state [6]),
    .ZN(butterfly_enable)
  );
  NOR4_X1 _428_ (
    .A1(\u_scheduler.state [2]),
    .A2(_011_),
    .A3(\u_scheduler.state [1]),
    .A4(_149_),
    .ZN(_219_)
  );
  INV_X1 _429_ (
    .A(cfg_last_stage[3]),
    .ZN(_079_)
  );
  NAND2_X1 _430_ (
    .A1(butterfly_enable),
    .A2(_219_),
    .ZN(_220_)
  );
  NOR3_X1 _431_ (
    .A1(_151_),
    .A2(_152_),
    .A3(_220_),
    .ZN(batch_valid)
  );
  NOR3_X1 _432_ (
    .A1(_063_),
    .A2(_085_),
    .A3(_111_),
    .ZN(load_start)
  );
  AND2_X1 _433_ (
    .A1(rst_n),
    .A2(_103_),
    .ZN(active)
  );
  NOR2_X1 _434_ (
    .A1(batch_retired),
    .A2(_100_),
    .ZN(_221_)
  );
  OAI21_X1 _435_ (
    .A(_221_),
    .B1(_149_),
    .B2(\u_scheduler.state [2]),
    .ZN(_222_)
  );
  AOI21_X1 _436_ (
    .A(_222_),
    .B1(_149_),
    .B2(backend_flushed),
    .ZN(_223_)
  );
  NAND3_X1 _437_ (
    .A1(\u_scheduler.state [2]),
    .A2(_073_),
    .A3(_102_),
    .ZN(_224_)
  );
  AOI21_X1 _438_ (
    .A(_224_),
    .B1(_000_),
    .B2(batch_retired),
    .ZN(_225_)
  );
  OR3_X1 _439_ (
    .A1(_151_),
    .A2(_223_),
    .A3(_225_),
    .ZN(\u_scheduler.next_state [2])
  );
  INV_X1 _440_ (
    .A(\u_controller.u_stage_counter.last_stage_q [0]),
    .ZN(_080_)
  );
  NAND2_X1 _441_ (
    .A1(backend_flushed),
    .A2(_102_),
    .ZN(_226_)
  );
  AOI21_X1 _442_ (
    .A(_151_),
    .B1(_226_),
    .B2(\u_scheduler.fault_q ),
    .ZN(_227_)
  );
  INV_X1 _443_ (
    .A(_227_),
    .ZN(_051_)
  );
  OAI21_X1 _444_ (
    .A(_106_),
    .B1(_183_),
    .B2(intt_mode),
    .ZN(_228_)
  );
  AOI21_X1 _445_ (
    .A(_228_),
    .B1(_183_),
    .B2(_071_),
    .ZN(_050_)
  );
  NAND2_X1 _446_ (
    .A1(_000_),
    .A2(_097_),
    .ZN(_229_)
  );
  NOR4_X1 _447_ (
    .A1(_105_),
    .A2(_112_),
    .A3(_151_),
    .A4(_229_),
    .ZN(_230_)
  );
  INV_X1 _448_ (
    .A(_230_),
    .ZN(_231_)
  );
  AND2_X1 _449_ (
    .A1(\u_scheduler.state [0]),
    .A2(_219_),
    .ZN(_232_)
  );
  OR4_X1 _450_ (
    .A1(_082_),
    .A2(_151_),
    .A3(_152_),
    .A4(_220_),
    .ZN(_233_)
  );
  INV_X1 _451_ (
    .A(rst_n),
    .ZN(_063_)
  );
  INV_X1 _452_ (
    .A(cfg_first_span_log2[0]),
    .ZN(_081_)
  );
  NOR3_X1 _453_ (
    .A1(_065_),
    .A2(_100_),
    .A3(_149_),
    .ZN(_234_)
  );
  AOI211_X1 _454_ (
    .A(_230_),
    .B(_234_),
    .C1(_233_),
    .C2(_232_),
    .ZN(_235_)
  );
  NOR3_X1 _455_ (
    .A1(_006_),
    .A2(_007_),
    .A3(_015_),
    .ZN(_236_)
  );
  NOR4_X1 _456_ (
    .A1(_002_),
    .A2(_003_),
    .A3(_004_),
    .A4(_005_),
    .ZN(_237_)
  );
  NAND4_X1 _457_ (
    .A1(batch_retired),
    .A2(_067_),
    .A3(_236_),
    .A4(_237_),
    .ZN(_238_)
  );
  NOR3_X1 _458_ (
    .A1(_100_),
    .A2(_149_),
    .A3(_238_),
    .ZN(_239_)
  );
  AND2_X1 _459_ (
    .A1(\u_scheduler.state [1]),
    .A2(_221_),
    .ZN(_240_)
  );
  AOI21_X1 _460_ (
    .A(_239_),
    .B1(_240_),
    .B2(_148_),
    .ZN(_241_)
  );
  NAND2_X1 _461_ (
    .A1(_233_),
    .A2(_241_),
    .ZN(_242_)
  );
  NOR2_X1 _462_ (
    .A1(\u_scheduler.next_state [2]),
    .A2(_242_),
    .ZN(_243_)
  );
  INV_X1 _463_ (
    .A(batch_ready),
    .ZN(_082_)
  );
  AOI21_X1 _464_ (
    .A(_230_),
    .B1(_235_),
    .B2(_243_),
    .ZN(_244_)
  );
  INV_X1 _465_ (
    .A(_244_),
    .ZN(_245_)
  );
  NOR2_X1 _466_ (
    .A1(_151_),
    .A2(_235_),
    .ZN(\u_scheduler.next_state [0])
  );
  NOR4_X1 _467_ (
    .A1(_100_),
    .A2(_151_),
    .A3(_235_),
    .A4(_242_),
    .ZN(_246_)
  );
  AND3_X1 _468_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(\u_scheduler.batch_index_q [1]),
    .A3(_246_),
    .ZN(_247_)
  );
  NOR2_X1 _469_ (
    .A1(_088_),
    .A2(_089_),
    .ZN(_248_)
  );
  AND4_X1 _470_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(\u_scheduler.batch_index_q [1]),
    .A3(_246_),
    .A4(_248_),
    .ZN(_249_)
  );
  AND3_X1 _471_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(\u_scheduler.batch_index_q [5]),
    .A3(_249_),
    .ZN(_250_)
  );
  AOI21_X1 _472_ (
    .A(\u_scheduler.batch_index_q [7]),
    .B1(\u_scheduler.batch_index_q [6]),
    .B2(_250_),
    .ZN(_251_)
  );
  AND3_X1 _473_ (
    .A1(\u_scheduler.batch_index_q [7]),
    .A2(\u_scheduler.batch_index_q [6]),
    .A3(_250_),
    .ZN(_252_)
  );
  INV_X1 _474_ (
    .A(cfg_first_span_log2[1]),
    .ZN(_083_)
  );
  NOR3_X1 _475_ (
    .A1(_245_),
    .A2(_251_),
    .A3(_252_),
    .ZN(_049_)
  );
  AOI22_X1 _476_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(_230_),
    .B1(_244_),
    .B2(\u_scheduler.stage_q [3]),
    .ZN(_253_)
  );
  INV_X1 _477_ (
    .A(_253_),
    .ZN(_048_)
  );
  OAI22_X1 _478_ (
    .A1(_136_),
    .A2(_231_),
    .B1(_245_),
    .B2(_084_),
    .ZN(_047_)
  );
  AOI22_X1 _479_ (
    .A1(\u_controller.intt_mode_q ),
    .A2(_230_),
    .B1(_244_),
    .B2(\u_scheduler.intt_q ),
    .ZN(_254_)
  );
  INV_X1 _480_ (
    .A(_254_),
    .ZN(_046_)
  );
  NAND2_X1 _481_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_255_)
  );
  NAND2_X1 _482_ (
    .A1(_084_),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_256_)
  );
  NOR2_X1 _483_ (
    .A1(_255_),
    .A2(_256_),
    .ZN(_257_)
  );
  NAND2_X1 _484_ (
    .A1(\u_scheduler.span_q [1]),
    .A2(_013_),
    .ZN(_258_)
  );
  INV_X1 _485_ (
    .A(\u_scheduler.span_q [3]),
    .ZN(_084_)
  );
  NOR2_X1 _486_ (
    .A1(_256_),
    .A2(_258_),
    .ZN(_259_)
  );
  NAND2_X1 _487_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(_095_),
    .ZN(_260_)
  );
  NOR2_X1 _488_ (
    .A1(_256_),
    .A2(_260_),
    .ZN(_261_)
  );
  NAND2_X1 _489_ (
    .A1(_095_),
    .A2(_013_),
    .ZN(_262_)
  );
  NOR2_X1 _490_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_263_)
  );
  INV_X1 _491_ (
    .A(_263_),
    .ZN(_264_)
  );
  NOR2_X1 _492_ (
    .A1(_255_),
    .A2(_264_),
    .ZN(_265_)
  );
  NOR2_X1 _493_ (
    .A1(_258_),
    .A2(_264_),
    .ZN(_266_)
  );
  NOR2_X1 _494_ (
    .A1(_262_),
    .A2(_264_),
    .ZN(_267_)
  );
  NAND3_X1 _495_ (
    .A1(_095_),
    .A2(_013_),
    .A3(_263_),
    .ZN(_268_)
  );
  INV_X1 _496_ (
    .A(\u_controller.state [4]),
    .ZN(_085_)
  );
  AOI21_X1 _497_ (
    .A(_264_),
    .B1(_262_),
    .B2(_260_),
    .ZN(_269_)
  );
  NOR2_X1 _498_ (
    .A1(_266_),
    .A2(_269_),
    .ZN(_270_)
  );
  OAI21_X1 _499_ (
    .A(_263_),
    .B1(_013_),
    .B2(\u_scheduler.span_q [0]),
    .ZN(_271_)
  );
  OAI21_X1 _500_ (
    .A(_271_),
    .B1(_262_),
    .B2(_256_),
    .ZN(_272_)
  );
  OR3_X1 _501_ (
    .A1(_259_),
    .A2(_261_),
    .A3(_272_),
    .ZN(_273_)
  );
  XOR2_X1 _502_ (
    .A(_257_),
    .B(_273_),
    .Z(_274_)
  );
  AND2_X1 _503_ (
    .A1(\u_scheduler.batch_index_q [7]),
    .A2(_274_),
    .ZN(coeff_addr_a[8])
  );
  NAND2_X1 _504_ (
    .A1(\u_scheduler.batch_index_q [6]),
    .A2(_273_),
    .ZN(_275_)
  );
  OAI21_X1 _505_ (
    .A(_275_),
    .B1(_274_),
    .B2(_077_),
    .ZN(coeff_addr_a[7])
  );
  NOR3_X1 _506_ (
    .A1(_084_),
    .A2(\u_scheduler.span_q [2]),
    .A3(_262_),
    .ZN(_276_)
  );
  INV_X1 _507_ (
    .A(cfg_last_stage[1]),
    .ZN(_086_)
  );
  NOR2_X1 _508_ (
    .A1(coeff_addr_a[8]),
    .A2(_276_),
    .ZN(_277_)
  );
  INV_X1 _509_ (
    .A(_277_),
    .ZN(coeff_addr_b[8])
  );
  NAND2_X1 _510_ (
    .A1(\u_controller.state [5]),
    .A2(_110_),
    .ZN(_278_)
  );
  NOR2_X1 _511_ (
    .A1(_063_),
    .A2(_278_),
    .ZN(done)
  );
  NAND3_X1 _512_ (
    .A1(\u_controller.state [0]),
    .A2(_183_),
    .A3(_207_),
    .ZN(_279_)
  );
  OAI211_X1 _513_ (
    .A(_278_),
    .B(_279_),
    .C1(_208_),
    .C2(_210_),
    .ZN(_019_)
  );
  OAI21_X1 _514_ (
    .A(_215_),
    .B1(_111_),
    .B2(_085_),
    .ZN(_020_)
  );
  NOR3_X1 _515_ (
    .A1(_074_),
    .A2(_111_),
    .A3(_204_),
    .ZN(_018_)
  );
  OR3_X1 _516_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .A3(_211_),
    .ZN(_023_)
  );
  OAI21_X1 _517_ (
    .A(_269_),
    .B1(_268_),
    .B2(_260_),
    .ZN(_280_)
  );
  INV_X1 _518_ (
    .A(\u_scheduler.batch_index_q [1]),
    .ZN(_087_)
  );
  AOI22_X1 _519_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_267_),
    .B1(_280_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_281_)
  );
  INV_X1 _520_ (
    .A(_281_),
    .ZN(coeff_addr_a[1])
  );
  NAND2_X1 _521_ (
    .A1(\u_scheduler.batch_index_q [2]),
    .A2(_270_),
    .ZN(_282_)
  );
  OAI21_X1 _522_ (
    .A(_282_),
    .B1(_280_),
    .B2(_087_),
    .ZN(coeff_addr_a[2])
  );
  AOI21_X1 _523_ (
    .A(_271_),
    .B1(_266_),
    .B2(\u_scheduler.span_q [0]),
    .ZN(_283_)
  );
  OAI22_X1 _524_ (
    .A1(_088_),
    .A2(_270_),
    .B1(_283_),
    .B2(_089_),
    .ZN(coeff_addr_a[3])
  );
  NAND2_X1 _525_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_283_),
    .ZN(_284_)
  );
  OAI21_X1 _526_ (
    .A(_284_),
    .B1(_272_),
    .B2(_090_),
    .ZN(coeff_addr_a[4])
  );
  INV_X1 _527_ (
    .A(coeff_addr_a[4]),
    .ZN(_285_)
  );
  XNOR2_X1 _528_ (
    .A(_261_),
    .B(_272_),
    .ZN(_286_)
  );
  INV_X1 _529_ (
    .A(\u_scheduler.batch_index_q [2]),
    .ZN(_088_)
  );
  AOI22_X1 _530_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(_272_),
    .B1(_286_),
    .B2(\u_scheduler.batch_index_q [5]),
    .ZN(_287_)
  );
  INV_X1 _531_ (
    .A(_287_),
    .ZN(coeff_addr_a[5])
  );
  OAI22_X1 _532_ (
    .A1(_092_),
    .A2(_273_),
    .B1(_286_),
    .B2(_091_),
    .ZN(coeff_addr_a[6])
  );
  AND2_X1 _533_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_268_),
    .ZN(coeff_addr_a[0])
  );
  NAND2_X1 _534_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(_244_),
    .ZN(_288_)
  );
  OAI21_X1 _535_ (
    .A(_288_),
    .B1(_231_),
    .B2(_138_),
    .ZN(_045_)
  );
  XNOR2_X1 _536_ (
    .A(_122_),
    .B(_124_),
    .ZN(_289_)
  );
  AOI22_X1 _537_ (
    .A1(\u_scheduler.span_q [1]),
    .A2(_244_),
    .B1(_289_),
    .B2(_230_),
    .ZN(_290_)
  );
  INV_X1 _538_ (
    .A(_290_),
    .ZN(_044_)
  );
  NAND2_X1 _539_ (
    .A1(\u_scheduler.span_q [2]),
    .A2(_244_),
    .ZN(_291_)
  );
  INV_X1 _540_ (
    .A(\u_scheduler.batch_index_q [3]),
    .ZN(_089_)
  );
  OAI21_X1 _541_ (
    .A(_291_),
    .B1(_231_),
    .B2(_137_),
    .ZN(_043_)
  );
  AOI22_X1 _542_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_230_),
    .B1(_244_),
    .B2(\u_scheduler.stage_q [0]),
    .ZN(_292_)
  );
  INV_X1 _543_ (
    .A(_292_),
    .ZN(_042_)
  );
  AOI22_X1 _544_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_230_),
    .B1(_244_),
    .B2(\u_scheduler.stage_q [1]),
    .ZN(_293_)
  );
  INV_X1 _545_ (
    .A(_293_),
    .ZN(_041_)
  );
  AOI22_X1 _546_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_230_),
    .B1(_244_),
    .B2(\u_scheduler.stage_q [2]),
    .ZN(_294_)
  );
  INV_X1 _547_ (
    .A(_294_),
    .ZN(_040_)
  );
  NOR2_X1 _548_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_246_),
    .ZN(_295_)
  );
  AOI211_X1 _549_ (
    .A(_245_),
    .B(_295_),
    .C1(_246_),
    .C2(_067_),
    .ZN(_039_)
  );
  AOI21_X1 _550_ (
    .A(\u_scheduler.batch_index_q [1]),
    .B1(_246_),
    .B2(\u_scheduler.batch_index_q [0]),
    .ZN(_296_)
  );
  INV_X1 _551_ (
    .A(\u_scheduler.batch_index_q [4]),
    .ZN(_090_)
  );
  NOR3_X1 _552_ (
    .A1(_245_),
    .A2(_247_),
    .A3(_296_),
    .ZN(_038_)
  );
  OAI21_X1 _553_ (
    .A(_244_),
    .B1(_247_),
    .B2(\u_scheduler.batch_index_q [2]),
    .ZN(_297_)
  );
  AOI21_X1 _554_ (
    .A(_297_),
    .B1(_247_),
    .B2(\u_scheduler.batch_index_q [2]),
    .ZN(_037_)
  );
  AOI21_X1 _555_ (
    .A(\u_scheduler.batch_index_q [3]),
    .B1(_247_),
    .B2(\u_scheduler.batch_index_q [2]),
    .ZN(_298_)
  );
  NOR3_X1 _556_ (
    .A1(_245_),
    .A2(_249_),
    .A3(_298_),
    .ZN(_036_)
  );
  OAI21_X1 _557_ (
    .A(_244_),
    .B1(_249_),
    .B2(\u_scheduler.batch_index_q [4]),
    .ZN(_299_)
  );
  AOI21_X1 _558_ (
    .A(_299_),
    .B1(_249_),
    .B2(\u_scheduler.batch_index_q [4]),
    .ZN(_035_)
  );
  AOI21_X1 _559_ (
    .A(\u_scheduler.batch_index_q [5]),
    .B1(_249_),
    .B2(\u_scheduler.batch_index_q [4]),
    .ZN(_300_)
  );
  NOR3_X1 _560_ (
    .A1(_245_),
    .A2(_250_),
    .A3(_300_),
    .ZN(_034_)
  );
  OAI21_X1 _561_ (
    .A(_244_),
    .B1(_250_),
    .B2(\u_scheduler.batch_index_q [6]),
    .ZN(_301_)
  );
  INV_X1 _562_ (
    .A(scrub_done),
    .ZN(_064_)
  );
  INV_X1 _563_ (
    .A(\u_scheduler.batch_index_q [5]),
    .ZN(_091_)
  );
  AOI21_X1 _564_ (
    .A(_301_),
    .B1(_250_),
    .B2(\u_scheduler.batch_index_q [6]),
    .ZN(_033_)
  );
  OAI21_X1 _565_ (
    .A(_106_),
    .B1(_183_),
    .B2(cfg_last_stage[0]),
    .ZN(_302_)
  );
  AOI21_X1 _566_ (
    .A(_302_),
    .B1(_183_),
    .B2(_080_),
    .ZN(_032_)
  );
  OAI21_X1 _567_ (
    .A(_106_),
    .B1(_183_),
    .B2(cfg_last_stage[1]),
    .ZN(_303_)
  );
  AOI21_X1 _568_ (
    .A(_303_),
    .B1(_183_),
    .B2(_093_),
    .ZN(_031_)
  );
  OAI21_X1 _569_ (
    .A(_106_),
    .B1(_183_),
    .B2(cfg_last_stage[2]),
    .ZN(_304_)
  );
  AOI21_X1 _570_ (
    .A(_304_),
    .B1(_183_),
    .B2(_096_),
    .ZN(_030_)
  );
  MUX2_X1 _571_ (
    .A(\u_controller.u_stage_counter.stage_count [0]),
    .B(_315_[0]),
    .S(_212_),
    .Z(_305_)
  );
  AND3_X1 _572_ (
    .A1(_106_),
    .A2(_183_),
    .A3(_305_),
    .ZN(_029_)
  );
  AOI21_X1 _573_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .B1(_212_),
    .B2(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_306_)
  );
  INV_X1 _574_ (
    .A(\u_scheduler.batch_index_q [6]),
    .ZN(_092_)
  );
  NOR3_X1 _575_ (
    .A1(_213_),
    .A2(_217_),
    .A3(_306_),
    .ZN(_028_)
  );
  NOR2_X1 _576_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_213_),
    .ZN(_307_)
  );
  NOR3_X1 _577_ (
    .A1(_214_),
    .A2(_217_),
    .A3(_307_),
    .ZN(_027_)
  );
  NAND2_X1 _578_ (
    .A1(first_span_q[0]),
    .A2(_189_),
    .ZN(_308_)
  );
  OAI21_X1 _579_ (
    .A(_308_),
    .B1(_183_),
    .B2(_081_),
    .ZN(_026_)
  );
  NAND2_X1 _580_ (
    .A1(first_span_q[1]),
    .A2(_189_),
    .ZN(_309_)
  );
  OAI21_X1 _581_ (
    .A(_309_),
    .B1(_183_),
    .B2(_083_),
    .ZN(_025_)
  );
  NAND2_X1 _582_ (
    .A1(first_span_q[2]),
    .A2(_189_),
    .ZN(_310_)
  );
  OAI21_X1 _583_ (
    .A(_310_),
    .B1(_183_),
    .B2(_072_),
    .ZN(_024_)
  );
  AOI21_X1 _584_ (
    .A(_151_),
    .B1(_233_),
    .B2(_241_),
    .ZN(\u_scheduler.next_state [1])
  );
  INV_X1 _585_ (
    .A(\u_controller.u_stage_counter.last_stage_q [1]),
    .ZN(_093_)
  );
  OR2_X1 _586_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_267_),
    .ZN(coeff_addr_b[0])
  );
  OAI21_X1 _587_ (
    .A(_281_),
    .B1(_264_),
    .B2(_260_),
    .ZN(coeff_addr_b[1])
  );
  OR2_X1 _588_ (
    .A1(_266_),
    .A2(coeff_addr_a[2]),
    .ZN(coeff_addr_b[2])
  );
  OR2_X1 _589_ (
    .A1(_265_),
    .A2(coeff_addr_a[3]),
    .ZN(coeff_addr_b[3])
  );
  OAI21_X1 _590_ (
    .A(_285_),
    .B1(_262_),
    .B2(_256_),
    .ZN(coeff_addr_b[4])
  );
  OAI21_X1 _591_ (
    .A(_287_),
    .B1(_260_),
    .B2(_256_),
    .ZN(coeff_addr_b[5])
  );
  OR2_X1 _592_ (
    .A1(_259_),
    .A2(coeff_addr_a[6]),
    .ZN(coeff_addr_b[6])
  );
  OR2_X1 _593_ (
    .A1(_257_),
    .A2(coeff_addr_a[7]),
    .ZN(coeff_addr_b[7])
  );
  INV_X1 _594_ (
    .A(cfg_last_stage[0]),
    .ZN(_094_)
  );
  INV_X1 _595_ (
    .A(\u_scheduler.span_q [1]),
    .ZN(_095_)
  );
  INV_X1 _596_ (
    .A(\u_controller.u_stage_counter.last_stage_q [2]),
    .ZN(_096_)
  );
  NOR3_X1 _597_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(\u_scheduler.state [0]),
    .ZN(_097_)
  );
  OR3_X1 _598_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(\u_scheduler.state [0]),
    .ZN(_098_)
  );
  OR3_X1 _599_ (
    .A1(\u_scheduler.state [2]),
    .A2(_011_),
    .A3(_012_),
    .ZN(_099_)
  );
  OR3_X1 _600_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_012_),
    .ZN(_100_)
  );
  INV_X1 _601_ (
    .A(batch_retired),
    .ZN(_065_)
  );
  AOI221_X1 _602_ (
    .A(\u_scheduler.state [2]),
    .B1(_011_),
    .B2(\u_scheduler.state [0]),
    .C1(_012_),
    .C2(\u_scheduler.state [1]),
    .ZN(_101_)
  );
  NOR3_X1 _603_ (
    .A1(_001_),
    .A2(\u_scheduler.state [1]),
    .A3(\u_scheduler.state [0]),
    .ZN(_102_)
  );
  OR4_X1 _604_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .A3(\u_controller.state [4]),
    .A4(\u_controller.state [2]),
    .ZN(_103_)
  );
  NOR2_X1 _605_ (
    .A1(\u_controller.state [5]),
    .A2(_103_),
    .ZN(_104_)
  );
  NAND2_X1 _606_ (
    .A1(rst_n),
    .A2(_076_),
    .ZN(_105_)
  );
  OR2_X1 _607_ (
    .A1(\u_controller.state [0]),
    .A2(_103_),
    .ZN(_106_)
  );
  NOR3_X1 _608_ (
    .A1(\u_controller.state [5]),
    .A2(_105_),
    .A3(_106_),
    .ZN(transform_abort)
  );
  NOR4_X1 _609_ (
    .A1(\u_controller.state [5]),
    .A2(\u_controller.state [3]),
    .A3(_105_),
    .A4(_106_),
    .ZN(_107_)
  );
  NOR3_X1 _610_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_108_)
  );
  OR3_X1 _611_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_109_)
  );
  INV_X1 _612_ (
    .A(error_config),
    .ZN(_066_)
  );
  NOR4_X1 _613_ (
    .A1(abort_req),
    .A2(zeroize),
    .A3(_107_),
    .A4(_109_),
    .ZN(_110_)
  );
  INV_X1 _614_ (
    .A(_110_),
    .ZN(_111_)
  );
  NAND2_X1 _615_ (
    .A1(\u_controller.state [2]),
    .A2(_110_),
    .ZN(_112_)
  );
  NOR2_X1 _616_ (
    .A1(_063_),
    .A2(_112_),
    .ZN(stage_start)
  );
  OAI22_X1 _617_ (
    .A1(_073_),
    .A2(_097_),
    .B1(_112_),
    .B2(_063_),
    .ZN(_113_)
  );
  AOI21_X1 _618_ (
    .A(_338_[2]),
    .B1(_315_[0]),
    .B2(_338_[1]),
    .ZN(_114_)
  );
  AND3_X1 _619_ (
    .A1(_338_[2]),
    .A2(_315_[0]),
    .A3(_338_[1]),
    .ZN(_115_)
  );
  NOR3_X1 _620_ (
    .A1(descending_q),
    .A2(_114_),
    .A3(_115_),
    .ZN(_116_)
  );
  AOI21_X1 _621_ (
    .A(_116_),
    .B1(descending_q),
    .B2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_117_)
  );
  NAND2_X1 _622_ (
    .A1(first_span_q[2]),
    .A2(_117_),
    .ZN(_118_)
  );
  INV_X1 _623_ (
    .A(_314_[0]),
    .ZN(_067_)
  );
  XOR2_X1 _624_ (
    .A(_315_[0]),
    .B(_338_[1]),
    .Z(_119_)
  );
  MUX2_X1 _625_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .B(_119_),
    .S(_069_),
    .Z(_120_)
  );
  NOR2_X1 _626_ (
    .A1(_068_),
    .A2(_120_),
    .ZN(_121_)
  );
  NOR2_X1 _627_ (
    .A1(first_span_q[0]),
    .A2(_315_[0]),
    .ZN(_122_)
  );
  INV_X1 _628_ (
    .A(_122_),
    .ZN(_123_)
  );
  XNOR2_X1 _629_ (
    .A(first_span_q[1]),
    .B(_120_),
    .ZN(_124_)
  );
  AOI21_X1 _630_ (
    .A(_121_),
    .B1(_123_),
    .B2(_124_),
    .ZN(_125_)
  );
  XNOR2_X1 _631_ (
    .A(first_span_q[2]),
    .B(_117_),
    .ZN(_126_)
  );
  OAI21_X1 _632_ (
    .A(_118_),
    .B1(_125_),
    .B2(_126_),
    .ZN(_127_)
  );
  OR2_X1 _633_ (
    .A1(_312_),
    .A2(_115_),
    .ZN(_128_)
  );
  INV_X1 _634_ (
    .A(first_span_q[1]),
    .ZN(_068_)
  );
  NAND2_X1 _635_ (
    .A1(_312_),
    .A2(_115_),
    .ZN(_129_)
  );
  AOI21_X1 _636_ (
    .A(descending_q),
    .B1(_312_),
    .B2(_115_),
    .ZN(_130_)
  );
  NAND2_X1 _637_ (
    .A1(_069_),
    .A2(_129_),
    .ZN(_131_)
  );
  AOI22_X1 _638_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(descending_q),
    .B1(_128_),
    .B2(_130_),
    .ZN(_132_)
  );
  NAND2_X1 _639_ (
    .A1(first_span_q[3]),
    .A2(_132_),
    .ZN(_133_)
  );
  OR2_X1 _640_ (
    .A1(first_span_q[3]),
    .A2(_132_),
    .ZN(_134_)
  );
  NAND2_X1 _641_ (
    .A1(_133_),
    .A2(_134_),
    .ZN(_135_)
  );
  XOR2_X1 _642_ (
    .A(_127_),
    .B(_135_),
    .Z(_136_)
  );
  XNOR2_X1 _643_ (
    .A(_125_),
    .B(_126_),
    .ZN(_137_)
  );
  XOR2_X1 _644_ (
    .A(first_span_q[0]),
    .B(_315_[0]),
    .Z(_138_)
  );
  INV_X1 _645_ (
    .A(descending_q),
    .ZN(_069_)
  );
  AND3_X1 _646_ (
    .A1(_124_),
    .A2(_137_),
    .A3(_138_),
    .ZN(_139_)
  );
  NAND4_X1 _647_ (
    .A1(first_span_q[3]),
    .A2(_008_),
    .A3(_009_),
    .A4(_010_),
    .ZN(_140_)
  );
  OAI211_X1 _648_ (
    .A(_097_),
    .B(_128_),
    .C1(\u_controller.u_stage_counter.stage_count [3]),
    .C2(_312_),
    .ZN(_141_)
  );
  AOI211_X1 _649_ (
    .A(backend_flushed),
    .B(_141_),
    .C1(_140_),
    .C2(_078_),
    .ZN(_142_)
  );
  OAI211_X1 _650_ (
    .A(_118_),
    .B(_133_),
    .C1(_126_),
    .C2(_125_),
    .ZN(_143_)
  );
  AOI21_X1 _651_ (
    .A(_131_),
    .B1(_134_),
    .B2(_143_),
    .ZN(_144_)
  );
  AND3_X1 _652_ (
    .A1(_131_),
    .A2(_134_),
    .A3(_143_),
    .ZN(_145_)
  );
  OAI221_X1 _653_ (
    .A(_142_),
    .B1(_144_),
    .B2(_145_),
    .C1(_139_),
    .C2(_136_),
    .ZN(_146_)
  );
  AOI22_X1 _654_ (
    .A1(batch_retired),
    .A2(_100_),
    .B1(_113_),
    .B2(_146_),
    .ZN(_147_)
  );
  NOR2_X1 _655_ (
    .A1(_063_),
    .A2(_076_),
    .ZN(zeroize_req)
  );
  INV_X1 _656_ (
    .A(\u_controller.u_stage_counter.last_stage_q [3]),
    .ZN(_070_)
  );
  NOR2_X1 _657_ (
    .A1(_111_),
    .A2(zeroize_req),
    .ZN(_148_)
  );
  OAI21_X1 _658_ (
    .A(_110_),
    .B1(_076_),
    .B2(_063_),
    .ZN(_149_)
  );
  NAND2_X1 _659_ (
    .A1(_101_),
    .A2(_148_),
    .ZN(_150_)
  );
  OAI22_X1 _660_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_147_),
    .B2(_150_),
    .ZN(_151_)
  );
  NAND2_X1 _661_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_152_)
  );
  AOI211_X1 _662_ (
    .A(_151_),
    .B(_152_),
    .C1(_098_),
    .C2(_099_),
    .ZN(scheduler_quiescent)
  );
  INV_X1 _663_ (
    .A(scheduler_quiescent),
    .ZN(_153_)
  );
  AND2_X1 _664_ (
    .A1(rst_n),
    .A2(_014_),
    .ZN(busy)
  );
  NOR3_X1 _665_ (
    .A1(cfg_last_stage[1]),
    .A2(cfg_last_stage[2]),
    .A3(cfg_last_stage[0]),
    .ZN(_154_)
  );
  NOR2_X1 _666_ (
    .A1(cfg_span_descending),
    .A2(_154_),
    .ZN(_155_)
  );
  DFFS_X1 _667_ (
    .CK(clk),
    .D(_019_),
    .Q(\u_controller.state [0]),
    .QN(_014_),
    .SN(rst_n)
  );
  DFFR_X1 _668_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_controller.state [1]),
    .QN(_337_),
    .RN(rst_n)
  );
  DFFR_X1 _669_ (
    .CK(clk),
    .D(_020_),
    .Q(\u_controller.state [2]),
    .QN(_336_),
    .RN(rst_n)
  );
  DFFR_X1 _670_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.state [3]),
    .QN(_335_),
    .RN(rst_n)
  );
  DFFR_X1 _671_ (
    .CK(clk),
    .D(_021_),
    .Q(\u_controller.state [4]),
    .QN(_334_),
    .RN(rst_n)
  );
  DFFR_X1 _672_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.state [5]),
    .QN(_333_),
    .RN(rst_n)
  );
  DFFR_X1 _673_ (
    .CK(clk),
    .D(_022_),
    .Q(\u_controller.state [6]),
    .QN(_332_),
    .RN(rst_n)
  );
  DFFR_X1 _674_ (
    .CK(clk),
    .D(_023_),
    .Q(\u_controller.state [7]),
    .QN(_326_),
    .RN(rst_n)
  );
  DFFR_X1 _675_ (
    .CK(clk),
    .D(_046_),
    .Q(\u_scheduler.intt_q ),
    .QN(_325_),
    .RN(rst_n)
  );
  DFFR_X1 _676_ (
    .CK(clk),
    .D(_045_),
    .Q(\u_scheduler.span_q [0]),
    .QN(_013_),
    .RN(rst_n)
  );
  DFFR_X1 _677_ (
    .CK(clk),
    .D(_044_),
    .Q(\u_scheduler.span_q [1]),
    .QN(_327_),
    .RN(rst_n)
  );
  DFFR_X1 _678_ (
    .CK(clk),
    .D(_043_),
    .Q(\u_scheduler.span_q [2]),
    .QN(_328_),
    .RN(rst_n)
  );
  DFFR_X1 _679_ (
    .CK(clk),
    .D(_047_),
    .Q(\u_scheduler.span_q [3]),
    .QN(_324_),
    .RN(rst_n)
  );
  DFFR_X1 _680_ (
    .CK(clk),
    .D(_042_),
    .Q(\u_scheduler.stage_q [0]),
    .QN(_329_),
    .RN(rst_n)
  );
  DFFR_X1 _681_ (
    .CK(clk),
    .D(_041_),
    .Q(\u_scheduler.stage_q [1]),
    .QN(_330_),
    .RN(rst_n)
  );
  DFFR_X1 _682_ (
    .CK(clk),
    .D(_040_),
    .Q(\u_scheduler.stage_q [2]),
    .QN(_331_),
    .RN(rst_n)
  );
  DFFR_X1 _683_ (
    .CK(clk),
    .D(_048_),
    .Q(\u_scheduler.stage_q [3]),
    .QN(_323_),
    .RN(rst_n)
  );
  DFFR_X1 _684_ (
    .CK(clk),
    .D(_039_),
    .Q(\u_scheduler.batch_index_q [0]),
    .QN(_314_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _685_ (
    .CK(clk),
    .D(_038_),
    .Q(\u_scheduler.batch_index_q [1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _686_ (
    .CK(clk),
    .D(_037_),
    .Q(\u_scheduler.batch_index_q [2]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _687_ (
    .CK(clk),
    .D(_036_),
    .Q(\u_scheduler.batch_index_q [3]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _688_ (
    .CK(clk),
    .D(_035_),
    .Q(\u_scheduler.batch_index_q [4]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _689_ (
    .CK(clk),
    .D(_034_),
    .Q(\u_scheduler.batch_index_q [5]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _690_ (
    .CK(clk),
    .D(_033_),
    .Q(\u_scheduler.batch_index_q [6]),
    .QN(_007_),
    .RN(rst_n)
  );
  DFFR_X1 _691_ (
    .CK(clk),
    .D(_049_),
    .Q(\u_scheduler.batch_index_q [7]),
    .QN(_015_),
    .RN(rst_n)
  );
  DFFR_X1 _692_ (
    .CK(clk),
    .D(_050_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_322_),
    .RN(rst_n)
  );
  DFFR_X1 _693_ (
    .CK(clk),
    .D(_051_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _694_ (
    .CK(clk),
    .D(_032_),
    .Q(\u_controller.u_stage_counter.last_stage_q [0]),
    .QN(_311_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _695_ (
    .CK(clk),
    .D(_031_),
    .Q(\u_controller.u_stage_counter.last_stage_q [1]),
    .QN(_311_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _696_ (
    .CK(clk),
    .D(_030_),
    .Q(\u_controller.u_stage_counter.last_stage_q [2]),
    .QN(_311_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _697_ (
    .CK(clk),
    .D(_052_),
    .Q(\u_controller.u_stage_counter.last_stage_q [3]),
    .QN(_311_[3]),
    .RN(rst_n)
  );
  DFFR_X1 _698_ (
    .CK(clk),
    .D(_029_),
    .Q(\u_controller.u_stage_counter.stage_count [0]),
    .QN(_315_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _699_ (
    .CK(clk),
    .D(_028_),
    .Q(\u_controller.u_stage_counter.stage_count [1]),
    .QN(_338_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _700_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_controller.u_stage_counter.stage_count [2]),
    .QN(_338_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _701_ (
    .CK(clk),
    .D(_053_),
    .Q(\u_controller.u_stage_counter.stage_count [3]),
    .QN(_312_),
    .RN(rst_n)
  );
  DFFR_X1 _702_ (
    .CK(clk),
    .D(_054_),
    .Q(descending_q),
    .QN(_321_),
    .RN(rst_n)
  );
  DFFR_X1 _703_ (
    .CK(clk),
    .D(_026_),
    .Q(first_span_q[0]),
    .QN(_008_),
    .RN(rst_n)
  );
  DFFR_X1 _704_ (
    .CK(clk),
    .D(_025_),
    .Q(first_span_q[1]),
    .QN(_009_),
    .RN(rst_n)
  );
  DFFR_X1 _705_ (
    .CK(clk),
    .D(_024_),
    .Q(first_span_q[2]),
    .QN(_010_),
    .RN(rst_n)
  );
  DFFR_X1 _706_ (
    .CK(clk),
    .D(_055_),
    .Q(first_span_q[3]),
    .QN(_313_),
    .RN(rst_n)
  );
  DFFR_X1 _707_ (
    .CK(clk),
    .D(_056_),
    .Q(error_controller),
    .QN(_320_),
    .RN(rst_n)
  );
  DFFR_X1 _708_ (
    .CK(clk),
    .D(_057_),
    .Q(error_scheduler),
    .QN(_319_),
    .RN(rst_n)
  );
  DFFR_X1 _709_ (
    .CK(clk),
    .D(_058_),
    .Q(error_datapath),
    .QN(_318_),
    .RN(rst_n)
  );
  DFFR_X1 _710_ (
    .CK(clk),
    .D(_059_),
    .Q(error_ecc),
    .QN(_317_),
    .RN(rst_n)
  );
  DFFR_X1 _711_ (
    .CK(clk),
    .D(_060_),
    .Q(error_config),
    .QN(_316_),
    .RN(rst_n)
  );
  DFFR_X1 _712_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_011_),
    .RN(rst_n)
  );
  DFFR_X1 _713_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_012_),
    .RN(rst_n)
  );
  DFFR_X1 _714_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_001_),
    .RN(rst_n)
  );
  assign _314_[7:1] = \u_scheduler.batch_index_q [7:1];
  assign _315_[3:1] = \u_controller.u_stage_counter.stage_count [3:1];
  assign { _338_[4:3], _338_[0] } = { 1'h1, _312_, _315_[0] };
  assign \u_scheduler.decode_lanes.ordinal  = { 1'h0, \u_scheduler.batch_index_q  };
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = \u_scheduler.batch_index_q ;
  assign \u_scheduler.coeff_addr_b  = coeff_addr_b;
  assign \u_scheduler.coeff_addr_a  = coeff_addr_a;
  assign \u_scheduler.lane_valid  = batch_valid;
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.next_state [3] = 1'h0;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = \u_scheduler.batch_index_q ;
  assign lane_valid = batch_valid;
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
