/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input cfg_last_stage;
  wire cfg_last_stage;
  input cfg_first_span_log2;
  wire cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output stage_count;
  wire stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output [7:0] lane_valid;
  wire [7:0] lane_valid;
  output [7:0] coeff_addr_a;
  wire [7:0] coeff_addr_a;
  output [7:0] coeff_addr_b;
  wire [7:0] coeff_addr_b;
  output [7:0] butterfly_index;
  wire [7:0] butterfly_index;
  output batch_stage;
  wire batch_stage;
  output batch_span_log2;
  wire batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire [0:0] _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire descending_q;
  wire first_span_q;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire \u_controller.cfg_last_stage ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire \u_controller.last_stage ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.clk ;
  wire \u_controller.u_stage_counter.last_stage ;
  wire \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire \u_scheduler.batch_span_log2 ;
  wire \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [7:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [7:0] \u_scheduler.coeff_addr_a ;
  wire [7:0] \u_scheduler.coeff_addr_b ;
  wire \u_scheduler.decode_lanes.ordinal ;
  wire \u_scheduler.distance_mask ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire [7:0] \u_scheduler.lane_valid ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.rst_n ;
  wire \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire \u_scheduler.span_q ;
  wire \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _140_ (
    .A(cfg_span_descending),
    .ZN(_109_)
  );
  INV_X1 _141_ (
    .A(\u_scheduler.state [2]),
    .ZN(_110_)
  );
  INV_X1 _142_ (
    .A(\u_scheduler.batch_index_q ),
    .ZN(_119_)
  );
  AND2_X1 _143_ (
    .A1(_056_),
    .A2(_091_),
    .ZN(\u_scheduler.next_state [1])
  );
  NAND2_X1 _144_ (
    .A1(\u_controller.state [6]),
    .A2(_045_),
    .ZN(_092_)
  );
  OAI22_X1 _145_ (
    .A1(_117_),
    .A2(_046_),
    .B1(stage_done),
    .B2(_092_),
    .ZN(_012_)
  );
  AND3_X1 _146_ (
    .A1(scrub_done),
    .A2(_042_),
    .A3(scheduler_quiescent),
    .ZN(_093_)
  );
  NAND3_X1 _147_ (
    .A1(scrub_done),
    .A2(_042_),
    .A3(scheduler_quiescent),
    .ZN(_094_)
  );
  NOR2_X1 _148_ (
    .A1(\u_controller.state [5]),
    .A2(_037_),
    .ZN(_095_)
  );
  NOR2_X1 _149_ (
    .A1(_043_),
    .A2(_095_),
    .ZN(_096_)
  );
  NOR2_X1 _150_ (
    .A1(zeroize),
    .A2(_096_),
    .ZN(_097_)
  );
  NAND2_X1 _151_ (
    .A1(\u_controller.state [7]),
    .A2(_097_),
    .ZN(_098_)
  );
  NOR2_X1 _152_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .ZN(_099_)
  );
  INV_X1 _153_ (
    .A(\u_scheduler.stage_q ),
    .ZN(_120_)
  );
  OAI21_X1 _154_ (
    .A(_099_),
    .B1(_098_),
    .B2(_093_),
    .ZN(_013_)
  );
  NOR2_X1 _155_ (
    .A1(_112_),
    .A2(_081_),
    .ZN(load_start)
  );
  NOR2_X1 _156_ (
    .A1(_112_),
    .A2(_036_),
    .ZN(active)
  );
  NAND2_X1 _157_ (
    .A1(\u_controller.state [5]),
    .A2(_045_),
    .ZN(_100_)
  );
  NOR2_X1 _158_ (
    .A1(_112_),
    .A2(_100_),
    .ZN(done)
  );
  NOR2_X1 _159_ (
    .A1(intt_mode),
    .A2(_069_),
    .ZN(_101_)
  );
  AOI221_X1 _160_ (
    .A(_101_),
    .B1(_069_),
    .B2(_116_),
    .C1(_115_),
    .C2(_036_),
    .ZN(_018_)
  );
  NAND3_X1 _161_ (
    .A1(_001_),
    .A2(_028_),
    .A3(stage_start),
    .ZN(_102_)
  );
  NOR3_X1 _162_ (
    .A1(_053_),
    .A2(_055_),
    .A3(_102_),
    .ZN(_103_)
  );
  OAI33_X1 _163_ (
    .A1(\u_scheduler.next_state [2]),
    .A2(_085_),
    .A3(_091_),
    .B1(_102_),
    .B2(_053_),
    .B3(_055_),
    .ZN(_104_)
  );
  INV_X1 _164_ (
    .A(\u_scheduler.span_q ),
    .ZN(_121_)
  );
  NOR2_X1 _165_ (
    .A1(_033_),
    .A2(_091_),
    .ZN(_105_)
  );
  AOI211_X1 _166_ (
    .A(_119_),
    .B(_104_),
    .C1(_105_),
    .C2(\u_scheduler.next_state [0]),
    .ZN(_017_)
  );
  NAND2_X1 _167_ (
    .A1(\u_controller.u_stage_counter.stage_count ),
    .A2(_103_),
    .ZN(_106_)
  );
  OAI21_X1 _168_ (
    .A(_106_),
    .B1(_104_),
    .B2(_120_),
    .ZN(_016_)
  );
  NOR2_X1 _169_ (
    .A1(_121_),
    .A2(_104_),
    .ZN(_015_)
  );
  NAND2_X1 _170_ (
    .A1(\u_controller.intt_mode_q ),
    .A2(_103_),
    .ZN(_107_)
  );
  OAI21_X1 _171_ (
    .A(_107_),
    .B1(_104_),
    .B2(_122_),
    .ZN(_014_)
  );
  NOR3_X1 _172_ (
    .A1(zeroize),
    .A2(_043_),
    .A3(_095_),
    .ZN(_007_)
  );
  AND2_X1 _173_ (
    .A1(\u_controller.state [6]),
    .A2(rst_n),
    .ZN(butterfly_enable)
  );
  AND2_X1 _174_ (
    .A1(\u_controller.state [6]),
    .A2(stage_done),
    .ZN(_006_)
  );
  INV_X1 _175_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_122_)
  );
  NAND3_X1 _176_ (
    .A1(\u_controller.state [0]),
    .A2(_069_),
    .A3(_097_),
    .ZN(_108_)
  );
  OAI211_X1 _177_ (
    .A(_100_),
    .B(_108_),
    .C1(_094_),
    .C2(_098_),
    .ZN(_009_)
  );
  NOR3_X1 _178_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(\u_scheduler.state [0]),
    .ZN(_028_)
  );
  OR3_X1 _179_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(\u_scheduler.state [0]),
    .ZN(_029_)
  );
  OR3_X1 _180_ (
    .A1(\u_scheduler.state [2]),
    .A2(_005_),
    .A3(_004_),
    .ZN(_030_)
  );
  NOR3_X1 _181_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(_005_),
    .ZN(_031_)
  );
  NOR3_X1 _182_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_004_),
    .ZN(_032_)
  );
  OR3_X1 _183_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_004_),
    .ZN(_033_)
  );
  INV_X1 _184_ (
    .A(abort_req),
    .ZN(_111_)
  );
  AOI221_X1 _185_ (
    .A(\u_scheduler.state [2]),
    .B1(\u_scheduler.state [0]),
    .B2(_005_),
    .C1(_004_),
    .C2(\u_scheduler.state [1]),
    .ZN(_034_)
  );
  NOR3_X1 _186_ (
    .A1(\u_scheduler.state [1]),
    .A2(\u_scheduler.state [0]),
    .A3(_002_),
    .ZN(_035_)
  );
  NOR4_X1 _187_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .A3(\u_controller.state [2]),
    .A4(\u_controller.state [4]),
    .ZN(_036_)
  );
  OR4_X1 _188_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .A3(\u_controller.state [2]),
    .A4(\u_controller.state [4]),
    .ZN(_037_)
  );
  NOR2_X1 _189_ (
    .A1(\u_controller.state [7]),
    .A2(\u_controller.state [5]),
    .ZN(_038_)
  );
  NAND4_X1 _190_ (
    .A1(rst_n),
    .A2(_115_),
    .A3(_036_),
    .A4(_038_),
    .ZN(_039_)
  );
  INV_X1 _191_ (
    .A(_039_),
    .ZN(transform_abort)
  );
  NOR2_X1 _192_ (
    .A1(\u_controller.state [3]),
    .A2(_039_),
    .ZN(_040_)
  );
  NOR3_X1 _193_ (
    .A1(\u_scheduler.fault_q ),
    .A2(ecc_uncorrectable),
    .A3(datapath_fault),
    .ZN(_041_)
  );
  NOR4_X1 _194_ (
    .A1(\u_scheduler.fault_q ),
    .A2(ecc_uncorrectable),
    .A3(datapath_fault),
    .A4(_040_),
    .ZN(_042_)
  );
  INV_X1 _195_ (
    .A(rst_n),
    .ZN(_112_)
  );
  AND2_X1 _196_ (
    .A1(_111_),
    .A2(_042_),
    .ZN(_043_)
  );
  OAI211_X1 _197_ (
    .A(_111_),
    .B(_041_),
    .C1(_039_),
    .C2(\u_controller.state [3]),
    .ZN(_044_)
  );
  NOR2_X1 _198_ (
    .A1(zeroize),
    .A2(_044_),
    .ZN(_045_)
  );
  INV_X1 _199_ (
    .A(_045_),
    .ZN(_046_)
  );
  NOR4_X1 _200_ (
    .A1(_112_),
    .A2(zeroize),
    .A3(_117_),
    .A4(_044_),
    .ZN(stage_start)
  );
  NAND2_X1 _201_ (
    .A1(\u_controller.last_stage ),
    .A2(_000_),
    .ZN(_047_)
  );
  NOR3_X1 _202_ (
    .A1(first_span_q),
    .A2(backend_flushed),
    .A3(_047_),
    .ZN(_048_)
  );
  OAI211_X1 _203_ (
    .A(_028_),
    .B(_048_),
    .C1(_114_),
    .C2(descending_q),
    .ZN(_049_)
  );
  AOI222_X1 _204_ (
    .A1(backend_flushed),
    .A2(_029_),
    .B1(stage_start),
    .B2(_049_),
    .C1(_033_),
    .C2(batch_retired),
    .ZN(_050_)
  );
  NAND2_X1 _205_ (
    .A1(rst_n),
    .A2(\u_controller.state [7]),
    .ZN(_051_)
  );
  INV_X1 _206_ (
    .A(enable),
    .ZN(_113_)
  );
  INV_X1 _207_ (
    .A(_051_),
    .ZN(zeroize_req)
  );
  NOR3_X1 _208_ (
    .A1(zeroize),
    .A2(_044_),
    .A3(zeroize_req),
    .ZN(_052_)
  );
  NAND2_X1 _209_ (
    .A1(_045_),
    .A2(_051_),
    .ZN(_053_)
  );
  NAND2_X1 _210_ (
    .A1(_034_),
    .A2(_052_),
    .ZN(_054_)
  );
  OAI22_X1 _211_ (
    .A1(_034_),
    .A2(_035_),
    .B1(_050_),
    .B2(_054_),
    .ZN(_055_)
  );
  INV_X1 _212_ (
    .A(_055_),
    .ZN(_056_)
  );
  NAND2_X1 _213_ (
    .A1(backend_flushed),
    .A2(_035_),
    .ZN(_057_)
  );
  AOI21_X1 _214_ (
    .A(_055_),
    .B1(_057_),
    .B2(\u_scheduler.fault_q ),
    .ZN(_058_)
  );
  INV_X1 _215_ (
    .A(_058_),
    .ZN(_027_)
  );
  NAND2_X1 _216_ (
    .A1(backend_flushed),
    .A2(_053_),
    .ZN(_059_)
  );
  INV_X1 _217_ (
    .A(\u_controller.u_stage_counter.stage_count ),
    .ZN(_114_)
  );
  NOR2_X1 _218_ (
    .A1(batch_retired),
    .A2(_033_),
    .ZN(_060_)
  );
  OAI211_X1 _219_ (
    .A(_059_),
    .B(_060_),
    .C1(\u_scheduler.state [2]),
    .C2(_053_),
    .ZN(_061_)
  );
  AOI211_X1 _220_ (
    .A(_110_),
    .B(backend_flushed),
    .C1(_001_),
    .C2(batch_retired),
    .ZN(_062_)
  );
  AOI21_X1 _221_ (
    .A(_055_),
    .B1(_062_),
    .B2(_035_),
    .ZN(_063_)
  );
  NAND2_X1 _222_ (
    .A1(_061_),
    .A2(_063_),
    .ZN(\u_scheduler.next_state [2])
  );
  AND2_X1 _223_ (
    .A1(rst_n),
    .A2(_003_),
    .ZN(busy)
  );
  NAND2_X1 _224_ (
    .A1(rst_n),
    .A2(_001_),
    .ZN(_064_)
  );
  AOI211_X1 _225_ (
    .A(_055_),
    .B(_064_),
    .C1(_029_),
    .C2(_030_),
    .ZN(scheduler_quiescent)
  );
  NOR2_X1 _226_ (
    .A1(cfg_last_stage),
    .A2(cfg_first_span_log2),
    .ZN(_065_)
  );
  NOR3_X1 _227_ (
    .A1(_113_),
    .A2(_115_),
    .A3(backend_flushed),
    .ZN(_066_)
  );
  INV_X1 _228_ (
    .A(\u_controller.state [0]),
    .ZN(_115_)
  );
  AND4_X1 _229_ (
    .A1(_045_),
    .A2(scheduler_quiescent),
    .A3(_065_),
    .A4(_066_),
    .ZN(ready)
  );
  AND2_X1 _230_ (
    .A1(start),
    .A2(ready),
    .ZN(_011_)
  );
  NAND2_X1 _231_ (
    .A1(enable),
    .A2(_065_),
    .ZN(_067_)
  );
  NOR4_X1 _232_ (
    .A1(_115_),
    .A2(backend_flushed),
    .A3(_046_),
    .A4(_067_),
    .ZN(_068_)
  );
  NAND3_X1 _233_ (
    .A1(start),
    .A2(scheduler_quiescent),
    .A3(_068_),
    .ZN(_069_)
  );
  NAND2_X1 _234_ (
    .A1(error_config),
    .A2(_069_),
    .ZN(_070_)
  );
  NOR2_X1 _235_ (
    .A1(busy),
    .A2(_065_),
    .ZN(_071_)
  );
  NAND4_X1 _236_ (
    .A1(rst_n),
    .A2(start),
    .A3(enable),
    .A4(_071_),
    .ZN(_072_)
  );
  OAI21_X1 _237_ (
    .A(_070_),
    .B1(_072_),
    .B2(_046_),
    .ZN(_026_)
  );
  AOI21_X1 _238_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_069_),
    .ZN(_073_)
  );
  INV_X1 _239_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_116_)
  );
  INV_X1 _240_ (
    .A(_073_),
    .ZN(_025_)
  );
  AOI21_X1 _241_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_069_),
    .ZN(_074_)
  );
  INV_X1 _242_ (
    .A(_074_),
    .ZN(_024_)
  );
  AOI21_X1 _243_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_069_),
    .ZN(_075_)
  );
  INV_X1 _244_ (
    .A(_075_),
    .ZN(_023_)
  );
  AOI21_X1 _245_ (
    .A(_040_),
    .B1(_069_),
    .B2(error_controller),
    .ZN(_076_)
  );
  INV_X1 _246_ (
    .A(_076_),
    .ZN(_022_)
  );
  AND3_X1 _247_ (
    .A1(first_span_q),
    .A2(_051_),
    .A3(_069_),
    .ZN(_021_)
  );
  NAND3_X1 _248_ (
    .A1(descending_q),
    .A2(_051_),
    .A3(_069_),
    .ZN(_077_)
  );
  OAI21_X1 _249_ (
    .A(_077_),
    .B1(_069_),
    .B2(_109_),
    .ZN(_020_)
  );
  INV_X1 _250_ (
    .A(\u_controller.state [2]),
    .ZN(_117_)
  );
  OAI211_X1 _251_ (
    .A(\u_controller.u_stage_counter.stage_count ),
    .B(_069_),
    .C1(_037_),
    .C2(\u_controller.state [0]),
    .ZN(_078_)
  );
  INV_X1 _252_ (
    .A(_078_),
    .ZN(_019_)
  );
  NAND2_X1 _253_ (
    .A1(\u_controller.state [1]),
    .A2(_045_),
    .ZN(_079_)
  );
  NOR2_X1 _254_ (
    .A1(\u_controller.u_stage_counter.stage_count ),
    .A2(_079_),
    .ZN(_008_)
  );
  NAND3_X1 _255_ (
    .A1(\u_controller.state [6]),
    .A2(_031_),
    .A3(_052_),
    .ZN(_080_)
  );
  NOR3_X1 _256_ (
    .A1(_055_),
    .A2(_064_),
    .A3(_080_),
    .ZN(batch_valid)
  );
  NAND2_X1 _257_ (
    .A1(\u_controller.state [4]),
    .A2(_045_),
    .ZN(_081_)
  );
  OAI21_X1 _258_ (
    .A(_081_),
    .B1(_079_),
    .B2(\u_controller.last_stage ),
    .ZN(_010_)
  );
  NOR4_X1 _259_ (
    .A1(_030_),
    .A2(_053_),
    .A3(_055_),
    .A4(_064_),
    .ZN(stage_done)
  );
  NAND2_X1 _260_ (
    .A1(batch_retired),
    .A2(_032_),
    .ZN(_082_)
  );
  INV_X1 _261_ (
    .A(batch_ready),
    .ZN(_118_)
  );
  NOR4_X1 _262_ (
    .A1(_118_),
    .A2(_055_),
    .A3(_064_),
    .A4(_080_),
    .ZN(_083_)
  );
  NAND3_X1 _263_ (
    .A1(\u_scheduler.state [0]),
    .A2(_031_),
    .A3(_052_),
    .ZN(_084_)
  );
  OAI22_X1 _264_ (
    .A1(_053_),
    .A2(_082_),
    .B1(_083_),
    .B2(_084_),
    .ZN(_085_)
  );
  NAND4_X1 _265_ (
    .A1(_001_),
    .A2(_028_),
    .A3(stage_start),
    .A4(_052_),
    .ZN(_086_)
  );
  OAI221_X1 _266_ (
    .A(_086_),
    .B1(_084_),
    .B2(_083_),
    .C1(_053_),
    .C2(_082_),
    .ZN(_087_)
  );
  AND2_X1 _267_ (
    .A1(_056_),
    .A2(_087_),
    .ZN(\u_scheduler.next_state [0])
  );
  NAND4_X1 _268_ (
    .A1(batch_retired),
    .A2(_123_),
    .A3(_032_),
    .A4(_052_),
    .ZN(_088_)
  );
  NAND3_X1 _269_ (
    .A1(\u_scheduler.state [1]),
    .A2(_052_),
    .A3(_060_),
    .ZN(_089_)
  );
  NAND2_X1 _270_ (
    .A1(_088_),
    .A2(_089_),
    .ZN(_090_)
  );
  OR2_X1 _271_ (
    .A1(_083_),
    .A2(_090_),
    .ZN(_091_)
  );
  DFFS_X1 _272_ (
    .CK(clk),
    .D(_009_),
    .Q(\u_controller.state [0]),
    .QN(_003_),
    .SN(rst_n)
  );
  DFFR_X1 _273_ (
    .CK(clk),
    .D(_006_),
    .Q(\u_controller.state [1]),
    .QN(_139_),
    .RN(rst_n)
  );
  DFFR_X1 _274_ (
    .CK(clk),
    .D(_010_),
    .Q(\u_controller.state [2]),
    .QN(_138_),
    .RN(rst_n)
  );
  DFFR_X1 _275_ (
    .CK(clk),
    .D(_007_),
    .Q(\u_controller.state [3]),
    .QN(_137_),
    .RN(rst_n)
  );
  DFFR_X1 _276_ (
    .CK(clk),
    .D(_011_),
    .Q(\u_controller.state [4]),
    .QN(_136_),
    .RN(rst_n)
  );
  DFFR_X1 _277_ (
    .CK(clk),
    .D(_008_),
    .Q(\u_controller.state [5]),
    .QN(_135_),
    .RN(rst_n)
  );
  DFFR_X1 _278_ (
    .CK(clk),
    .D(_012_),
    .Q(\u_controller.state [6]),
    .QN(_134_),
    .RN(rst_n)
  );
  DFFR_X1 _279_ (
    .CK(clk),
    .D(_013_),
    .Q(\u_controller.state [7]),
    .QN(_133_),
    .RN(rst_n)
  );
  DFFR_X1 _280_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_scheduler.intt_q ),
    .QN(_132_),
    .RN(rst_n)
  );
  DFFR_X1 _281_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_scheduler.span_q ),
    .QN(\u_scheduler.distance_mask ),
    .RN(rst_n)
  );
  DFFR_X1 _282_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_scheduler.stage_q ),
    .QN(_131_),
    .RN(rst_n)
  );
  DFFR_X1 _283_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_scheduler.batch_index_q ),
    .QN(_123_),
    .RN(rst_n)
  );
  DFFR_X1 _284_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_130_),
    .RN(rst_n)
  );
  DFFR_X1 _285_ (
    .CK(clk),
    .D(_019_),
    .Q(\u_controller.u_stage_counter.stage_count ),
    .QN(\u_controller.last_stage ),
    .RN(rst_n)
  );
  DFFR_X1 _286_ (
    .CK(clk),
    .D(_020_),
    .Q(descending_q),
    .QN(_129_),
    .RN(rst_n)
  );
  DFFR_X1 _287_ (
    .CK(clk),
    .D(_021_),
    .Q(first_span_q),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _288_ (
    .CK(clk),
    .D(_022_),
    .Q(error_controller),
    .QN(_128_),
    .RN(rst_n)
  );
  DFFR_X1 _289_ (
    .CK(clk),
    .D(_023_),
    .Q(error_scheduler),
    .QN(_127_),
    .RN(rst_n)
  );
  DFFR_X1 _290_ (
    .CK(clk),
    .D(_024_),
    .Q(error_datapath),
    .QN(_126_),
    .RN(rst_n)
  );
  DFFR_X1 _291_ (
    .CK(clk),
    .D(_025_),
    .Q(error_ecc),
    .QN(_125_),
    .RN(rst_n)
  );
  DFFR_X1 _292_ (
    .CK(clk),
    .D(_026_),
    .Q(error_config),
    .QN(_124_),
    .RN(rst_n)
  );
  DFFR_X1 _293_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_scheduler.fault_q ),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _294_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _295_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _296_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_002_),
    .RN(rst_n)
  );
  assign \u_scheduler.decode_lanes.ordinal  = 1'h0;
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = 8'h00;
  assign \u_scheduler.coeff_addr_b  = { 7'h00, \u_scheduler.distance_mask  };
  assign \u_scheduler.coeff_addr_a  = 8'h00;
  assign \u_scheduler.lane_valid  = { 7'h00, batch_valid };
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.last_stage_q  = 1'h0;
  assign \u_controller.u_stage_counter.last_stage  = \u_controller.last_stage ;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.next_state  = 4'b0xxx;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = 8'h00;
  assign coeff_addr_b = { 7'h00, \u_scheduler.distance_mask  };
  assign coeff_addr_a = 8'h00;
  assign lane_valid = { 7'h00, batch_valid };
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
