/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input [1:0] cfg_last_stage;
  wire [1:0] cfg_last_stage;
  input [1:0] cfg_first_span_log2;
  wire [1:0] cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output [1:0] stage_count;
  wire [1:0] stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output [3:0] lane_valid;
  wire [3:0] lane_valid;
  output [11:0] coeff_addr_a;
  wire [11:0] coeff_addr_a;
  output [11:0] coeff_addr_b;
  wire [11:0] coeff_addr_b;
  output [7:0] butterfly_index;
  wire [7:0] butterfly_index;
  output [1:0] batch_stage;
  wire [1:0] batch_stage;
  output [1:0] batch_span_log2;
  wire [1:0] batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire [1:0] _175_;
  wire [0:0] _176_;
  wire [0:0] _177_;
  wire [0:0] _178_;
  wire [1:0] _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire descending_q;
  wire [1:0] first_span_q;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire [1:0] \u_controller.cfg_last_stage ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire [1:0] \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire [1:0] \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.clk ;
  wire [1:0] \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire [1:0] \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire [1:0] \u_scheduler.batch_span_log2 ;
  wire [1:0] \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [7:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [11:0] \u_scheduler.coeff_addr_a ;
  wire [11:0] \u_scheduler.coeff_addr_b ;
  wire [2:0] \u_scheduler.decode_lanes.ordinal ;
  wire [2:0] \u_scheduler.distance_mask ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire [3:0] \u_scheduler.lane_valid ;
  wire [2:0] \u_scheduler.low_mask ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.rst_n ;
  wire [1:0] \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire [1:0] \u_scheduler.span_q ;
  wire [1:0] \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire [1:0] \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _198_ (
    .A(cfg_last_stage[1]),
    .ZN(_035_)
  );
  INV_X1 _199_ (
    .A(\u_controller.state [6]),
    .ZN(_036_)
  );
  INV_X1 _200_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_045_)
  );
  NAND3_X1 _201_ (
    .A1(rst_n),
    .A2(_067_),
    .A3(_124_),
    .ZN(_125_)
  );
  OAI21_X1 _202_ (
    .A(_125_),
    .B1(_120_),
    .B2(_040_),
    .ZN(_034_)
  );
  AOI21_X1 _203_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_122_),
    .ZN(_126_)
  );
  INV_X1 _204_ (
    .A(_126_),
    .ZN(_033_)
  );
  AOI21_X1 _205_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_122_),
    .ZN(_127_)
  );
  INV_X1 _206_ (
    .A(_127_),
    .ZN(_032_)
  );
  AOI21_X1 _207_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_122_),
    .ZN(_128_)
  );
  INV_X1 _208_ (
    .A(_128_),
    .ZN(_031_)
  );
  NAND2_X1 _209_ (
    .A1(error_controller),
    .A2(_122_),
    .ZN(_129_)
  );
  OAI21_X1 _210_ (
    .A(_129_),
    .B1(_063_),
    .B2(\u_controller.state [3]),
    .ZN(_030_)
  );
  INV_X1 _211_ (
    .A(cfg_first_span_log2[1]),
    .ZN(_046_)
  );
  NOR2_X1 _212_ (
    .A1(zeroize_req),
    .A2(_120_),
    .ZN(_130_)
  );
  NAND2_X1 _213_ (
    .A1(first_span_q[1]),
    .A2(_130_),
    .ZN(_131_)
  );
  OAI21_X1 _214_ (
    .A(_131_),
    .B1(_122_),
    .B2(_046_),
    .ZN(_029_)
  );
  NAND2_X1 _215_ (
    .A1(backend_flushed),
    .A2(_095_),
    .ZN(_132_)
  );
  NAND2_X1 _216_ (
    .A1(\u_scheduler.fault_q ),
    .A2(_132_),
    .ZN(_133_)
  );
  NAND2_X1 _217_ (
    .A1(_097_),
    .A2(_133_),
    .ZN(_028_)
  );
  NAND2_X1 _218_ (
    .A1(_052_),
    .A2(_005_),
    .ZN(coeff_addr_a[3])
  );
  INV_X1 _219_ (
    .A(coeff_addr_a[3]),
    .ZN(coeff_addr_a[4])
  );
  NAND2_X1 _220_ (
    .A1(descending_q),
    .A2(_130_),
    .ZN(_134_)
  );
  OAI21_X1 _221_ (
    .A(_134_),
    .B1(_122_),
    .B2(_044_),
    .ZN(_027_)
  );
  INV_X1 _222_ (
    .A(backend_flushed),
    .ZN(_047_)
  );
  OAI22_X1 _223_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_175_[0]),
    .B1(_175_[1]),
    .B2(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_135_)
  );
  INV_X1 _224_ (
    .A(_135_),
    .ZN(_136_)
  );
  AND2_X1 _225_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_175_[1]),
    .ZN(_137_)
  );
  NAND2_X1 _226_ (
    .A1(\u_controller.state [6]),
    .A2(_067_),
    .ZN(_138_)
  );
  OAI21_X1 _227_ (
    .A(_068_),
    .B1(stage_done),
    .B2(_138_),
    .ZN(_013_)
  );
  NOR4_X1 _228_ (
    .A1(_105_),
    .A2(_109_),
    .A3(_136_),
    .A4(_137_),
    .ZN(_139_)
  );
  OAI211_X1 _229_ (
    .A(\u_controller.state [1]),
    .B(_139_),
    .C1(_101_),
    .C2(_036_),
    .ZN(_140_)
  );
  NOR4_X1 _230_ (
    .A1(_108_),
    .A2(_120_),
    .A3(_013_),
    .A4(_140_),
    .ZN(_141_)
  );
  AOI211_X1 _231_ (
    .A(_135_),
    .B(_137_),
    .C1(\u_controller.u_stage_counter.stage_count [0]),
    .C2(_175_[0]),
    .ZN(_142_)
  );
  NAND2_X1 _232_ (
    .A1(\u_controller.state [1]),
    .A2(_067_),
    .ZN(_143_)
  );
  INV_X1 _233_ (
    .A(intt_mode),
    .ZN(_048_)
  );
  AND3_X1 _234_ (
    .A1(\u_controller.state [1]),
    .A2(_067_),
    .A3(_142_),
    .ZN(_009_)
  );
  AOI21_X1 _235_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .B1(\u_controller.u_stage_counter.stage_count [0]),
    .B2(_141_),
    .ZN(_144_)
  );
  NAND2_X1 _236_ (
    .A1(_062_),
    .A2(_122_),
    .ZN(_145_)
  );
  NOR2_X1 _237_ (
    .A1(_144_),
    .A2(_145_),
    .ZN(_026_)
  );
  NAND2_X1 _238_ (
    .A1(backend_flushed),
    .A2(_089_),
    .ZN(_146_)
  );
  NOR2_X1 _239_ (
    .A1(batch_retired),
    .A2(_058_),
    .ZN(_147_)
  );
  OAI211_X1 _240_ (
    .A(_146_),
    .B(_147_),
    .C1(\u_scheduler.state [2]),
    .C2(_089_),
    .ZN(_148_)
  );
  NAND2_X1 _241_ (
    .A1(batch_retired),
    .A2(_000_),
    .ZN(_149_)
  );
  NAND4_X1 _242_ (
    .A1(\u_scheduler.state [2]),
    .A2(_047_),
    .A3(_095_),
    .A4(_149_),
    .ZN(_150_)
  );
  NAND3_X1 _243_ (
    .A1(_097_),
    .A2(_148_),
    .A3(_150_),
    .ZN(\u_scheduler.next_state [2])
  );
  INV_X1 _244_ (
    .A(_179_[0]),
    .ZN(_049_)
  );
  NOR2_X1 _245_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_141_),
    .ZN(_151_)
  );
  AOI211_X1 _246_ (
    .A(_145_),
    .B(_151_),
    .C1(_049_),
    .C2(_141_),
    .ZN(_025_)
  );
  AND2_X1 _247_ (
    .A1(rst_n),
    .A2(_061_),
    .ZN(active)
  );
  NAND2_X1 _248_ (
    .A1(\u_controller.state [5]),
    .A2(_067_),
    .ZN(_152_)
  );
  NOR2_X1 _249_ (
    .A1(_037_),
    .A2(_152_),
    .ZN(done)
  );
  OR3_X1 _250_ (
    .A1(_043_),
    .A2(_058_),
    .A3(_089_),
    .ZN(_153_)
  );
  AND3_X1 _251_ (
    .A1(_000_),
    .A2(_069_),
    .A3(_088_),
    .ZN(_154_)
  );
  NAND3_X1 _252_ (
    .A1(stage_start),
    .A2(_097_),
    .A3(_154_),
    .ZN(_155_)
  );
  NOR4_X1 _253_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(_003_),
    .A4(_089_),
    .ZN(_156_)
  );
  AND3_X1 _254_ (
    .A1(\u_controller.state [6]),
    .A2(_099_),
    .A3(_156_),
    .ZN(batch_valid)
  );
  INV_X1 _255_ (
    .A(\u_scheduler.batch_index_q ),
    .ZN(_050_)
  );
  AND4_X1 _256_ (
    .A1(\u_controller.state [6]),
    .A2(batch_ready),
    .A3(_099_),
    .A4(_156_),
    .ZN(_157_)
  );
  NAND2_X1 _257_ (
    .A1(\u_scheduler.state [0]),
    .A2(_156_),
    .ZN(_158_)
  );
  OAI211_X1 _258_ (
    .A(_153_),
    .B(_155_),
    .C1(_157_),
    .C2(_158_),
    .ZN(_159_)
  );
  AND2_X1 _259_ (
    .A1(_097_),
    .A2(_159_),
    .ZN(\u_scheduler.next_state [0])
  );
  NAND3_X1 _260_ (
    .A1(\u_scheduler.state [1]),
    .A2(_088_),
    .A3(_147_),
    .ZN(_160_)
  );
  OAI21_X1 _261_ (
    .A(_160_),
    .B1(_153_),
    .B2(_056_),
    .ZN(_161_)
  );
  NOR2_X1 _262_ (
    .A1(_157_),
    .A2(_161_),
    .ZN(_162_)
  );
  NOR3_X1 _263_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_162_),
    .ZN(\u_scheduler.next_state [1])
  );
  OAI21_X1 _264_ (
    .A(_062_),
    .B1(_120_),
    .B2(\u_controller.u_stage_counter.last_stage_q [1]),
    .ZN(_163_)
  );
  AOI21_X1 _265_ (
    .A(_163_),
    .B1(_120_),
    .B2(_035_),
    .ZN(_024_)
  );
  INV_X1 _266_ (
    .A(\u_scheduler.stage_q [1]),
    .ZN(_051_)
  );
  NAND2_X1 _267_ (
    .A1(first_span_q[0]),
    .A2(_130_),
    .ZN(_164_)
  );
  OAI21_X1 _268_ (
    .A(_164_),
    .B1(_122_),
    .B2(_055_),
    .ZN(_023_)
  );
  OAI21_X1 _269_ (
    .A(_062_),
    .B1(_120_),
    .B2(\u_controller.intt_mode_q ),
    .ZN(_165_)
  );
  AOI21_X1 _270_ (
    .A(_165_),
    .B1(_120_),
    .B2(_048_),
    .ZN(_022_)
  );
  NOR3_X1 _271_ (
    .A1(_058_),
    .A2(_157_),
    .A3(_161_),
    .ZN(_166_)
  );
  OR3_X1 _272_ (
    .A1(\u_scheduler.next_state [2]),
    .A2(_157_),
    .A3(_161_),
    .ZN(_167_)
  );
  OAI21_X1 _273_ (
    .A(_155_),
    .B1(_159_),
    .B2(_167_),
    .ZN(_168_)
  );
  AOI211_X1 _274_ (
    .A(_050_),
    .B(_168_),
    .C1(_166_),
    .C2(\u_scheduler.next_state [0]),
    .ZN(_021_)
  );
  OAI22_X1 _275_ (
    .A1(_041_),
    .A2(_155_),
    .B1(_168_),
    .B2(_051_),
    .ZN(_020_)
  );
  OAI22_X1 _276_ (
    .A1(_080_),
    .A2(_155_),
    .B1(_168_),
    .B2(_052_),
    .ZN(_019_)
  );
  INV_X1 _277_ (
    .A(\u_scheduler.span_q [1]),
    .ZN(_052_)
  );
  OAI22_X1 _278_ (
    .A1(_045_),
    .A2(_155_),
    .B1(_168_),
    .B2(_053_),
    .ZN(_018_)
  );
  NOR2_X1 _279_ (
    .A1(_036_),
    .A2(_037_),
    .ZN(butterfly_enable)
  );
  NAND2_X1 _280_ (
    .A1(\u_controller.state [4]),
    .A2(_067_),
    .ZN(_169_)
  );
  NOR2_X1 _281_ (
    .A1(_037_),
    .A2(_169_),
    .ZN(load_start)
  );
  NAND2_X1 _282_ (
    .A1(_052_),
    .A2(\u_scheduler.span_q [0]),
    .ZN(_170_)
  );
  INV_X1 _283_ (
    .A(_170_),
    .ZN(coeff_addr_b[1])
  );
  NAND2_X1 _284_ (
    .A1(\u_scheduler.batch_index_q ),
    .A2(_170_),
    .ZN(_171_)
  );
  NOR2_X1 _285_ (
    .A1(_005_),
    .A2(_171_),
    .ZN(coeff_addr_a[2])
  );
  NAND2_X1 _286_ (
    .A1(coeff_addr_a[3]),
    .A2(_170_),
    .ZN(coeff_addr_b[4])
  );
  NOR2_X1 _287_ (
    .A1(\u_scheduler.batch_index_q ),
    .A2(_005_),
    .ZN(_172_)
  );
  INV_X1 _288_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_053_)
  );
  NOR2_X1 _289_ (
    .A1(coeff_addr_b[4]),
    .A2(_172_),
    .ZN(coeff_addr_b[2])
  );
  NAND2_X1 _290_ (
    .A1(_054_),
    .A2(coeff_addr_a[4]),
    .ZN(coeff_addr_b[7])
  );
  NAND2_X1 _291_ (
    .A1(coeff_addr_a[3]),
    .A2(coeff_addr_b[1]),
    .ZN(coeff_addr_a[10])
  );
  AND2_X1 _292_ (
    .A1(coeff_addr_b[7]),
    .A2(coeff_addr_a[10]),
    .ZN(coeff_addr_a[7])
  );
  OAI21_X1 _293_ (
    .A(coeff_addr_a[7]),
    .B1(_171_),
    .B2(_005_),
    .ZN(coeff_addr_a[8])
  );
  NAND3_X1 _294_ (
    .A1(\u_controller.state [0]),
    .A2(_106_),
    .A3(_122_),
    .ZN(_173_)
  );
  OAI211_X1 _295_ (
    .A(_152_),
    .B(_173_),
    .C1(_103_),
    .C2(_107_),
    .ZN(_010_)
  );
  OAI21_X1 _296_ (
    .A(_169_),
    .B1(_143_),
    .B2(_142_),
    .ZN(_011_)
  );
  NOR2_X1 _297_ (
    .A1(zeroize),
    .A2(_104_),
    .ZN(_008_)
  );
  OAI21_X1 _298_ (
    .A(coeff_addr_a[7]),
    .B1(_172_),
    .B2(coeff_addr_b[4]),
    .ZN(coeff_addr_b[8])
  );
  INV_X1 _299_ (
    .A(\u_scheduler.span_q [0]),
    .ZN(_054_)
  );
  OAI21_X1 _300_ (
    .A(_062_),
    .B1(_120_),
    .B2(\u_controller.u_stage_counter.last_stage_q [0]),
    .ZN(_174_)
  );
  AOI21_X1 _301_ (
    .A(_174_),
    .B1(_120_),
    .B2(_038_),
    .ZN(_017_)
  );
  OAI22_X1 _302_ (
    .A1(_079_),
    .A2(_155_),
    .B1(_168_),
    .B2(_054_),
    .ZN(_016_)
  );
  OAI22_X1 _303_ (
    .A1(_042_),
    .A2(_155_),
    .B1(_168_),
    .B2(_057_),
    .ZN(_015_)
  );
  INV_X1 _304_ (
    .A(rst_n),
    .ZN(_037_)
  );
  INV_X1 _305_ (
    .A(cfg_first_span_log2[0]),
    .ZN(_055_)
  );
  INV_X1 _306_ (
    .A(_178_),
    .ZN(_056_)
  );
  INV_X1 _307_ (
    .A(\u_scheduler.stage_q [0]),
    .ZN(_057_)
  );
  OR3_X1 _308_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_006_),
    .ZN(_058_)
  );
  NAND2_X1 _309_ (
    .A1(batch_retired),
    .A2(_058_),
    .ZN(_059_)
  );
  NOR3_X1 _310_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_060_)
  );
  OR4_X1 _311_ (
    .A1(\u_controller.state [1]),
    .A2(\u_controller.state [2]),
    .A3(\u_controller.state [6]),
    .A4(\u_controller.state [4]),
    .ZN(_061_)
  );
  OR2_X1 _312_ (
    .A1(\u_controller.state [0]),
    .A2(_061_),
    .ZN(_062_)
  );
  OR4_X1 _313_ (
    .A1(_037_),
    .A2(\u_controller.state [7]),
    .A3(\u_controller.state [5]),
    .A4(_062_),
    .ZN(_063_)
  );
  INV_X1 _314_ (
    .A(_063_),
    .ZN(transform_abort)
  );
  INV_X1 _315_ (
    .A(cfg_last_stage[0]),
    .ZN(_038_)
  );
  OR2_X1 _316_ (
    .A1(\u_controller.state [0]),
    .A2(\u_controller.state [7]),
    .ZN(_064_)
  );
  OR4_X1 _317_ (
    .A1(_037_),
    .A2(\u_controller.state [5]),
    .A3(_061_),
    .A4(_064_),
    .ZN(_065_)
  );
  OAI21_X1 _318_ (
    .A(_060_),
    .B1(_065_),
    .B2(\u_controller.state [3]),
    .ZN(_066_)
  );
  NOR3_X1 _319_ (
    .A1(abort_req),
    .A2(zeroize),
    .A3(_066_),
    .ZN(_067_)
  );
  NAND2_X1 _320_ (
    .A1(\u_controller.state [2]),
    .A2(_067_),
    .ZN(_068_)
  );
  AND3_X1 _321_ (
    .A1(\u_controller.state [2]),
    .A2(rst_n),
    .A3(_067_),
    .ZN(stage_start)
  );
  NOR3_X1 _322_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(\u_scheduler.state [1]),
    .ZN(_069_)
  );
  NOR2_X1 _323_ (
    .A1(_047_),
    .A2(_069_),
    .ZN(_070_)
  );
  AOI21_X1 _324_ (
    .A(descending_q),
    .B1(_176_),
    .B2(_179_[0]),
    .ZN(_071_)
  );
  OR2_X1 _325_ (
    .A1(_176_),
    .A2(_179_[0]),
    .ZN(_072_)
  );
  INV_X1 _326_ (
    .A(scrub_done),
    .ZN(_039_)
  );
  AOI22_X1 _327_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(descending_q),
    .B1(_071_),
    .B2(_072_),
    .ZN(_073_)
  );
  NAND2_X1 _328_ (
    .A1(first_span_q[1]),
    .A2(_073_),
    .ZN(_074_)
  );
  NOR2_X1 _329_ (
    .A1(first_span_q[0]),
    .A2(_179_[0]),
    .ZN(_075_)
  );
  XNOR2_X1 _330_ (
    .A(first_span_q[1]),
    .B(_073_),
    .ZN(_076_)
  );
  OAI21_X1 _331_ (
    .A(_074_),
    .B1(_075_),
    .B2(_076_),
    .ZN(_077_)
  );
  XNOR2_X1 _332_ (
    .A(_071_),
    .B(_077_),
    .ZN(_078_)
  );
  XOR2_X1 _333_ (
    .A(first_span_q[0]),
    .B(_179_[0]),
    .Z(_079_)
  );
  XNOR2_X1 _334_ (
    .A(_075_),
    .B(_076_),
    .ZN(_080_)
  );
  AND2_X1 _335_ (
    .A1(_047_),
    .A2(_069_),
    .ZN(_081_)
  );
  AOI21_X1 _336_ (
    .A(_177_),
    .B1(_001_),
    .B2(first_span_q[1]),
    .ZN(_082_)
  );
  INV_X1 _337_ (
    .A(error_config),
    .ZN(_040_)
  );
  AOI21_X1 _338_ (
    .A(_176_),
    .B1(_179_[0]),
    .B2(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_083_)
  );
  NOR2_X1 _339_ (
    .A1(_082_),
    .A2(_083_),
    .ZN(_084_)
  );
  OAI211_X1 _340_ (
    .A(_081_),
    .B(_084_),
    .C1(_079_),
    .C2(_080_),
    .ZN(_085_)
  );
  OAI22_X1 _341_ (
    .A1(stage_start),
    .A2(_070_),
    .B1(_078_),
    .B2(_085_),
    .ZN(_086_)
  );
  NAND2_X1 _342_ (
    .A1(rst_n),
    .A2(\u_controller.state [7]),
    .ZN(_087_)
  );
  INV_X1 _343_ (
    .A(_087_),
    .ZN(zeroize_req)
  );
  AND2_X1 _344_ (
    .A1(_067_),
    .A2(_087_),
    .ZN(_088_)
  );
  NAND2_X1 _345_ (
    .A1(_067_),
    .A2(_087_),
    .ZN(_089_)
  );
  NOR3_X1 _346_ (
    .A1(\u_scheduler.state [2]),
    .A2(_003_),
    .A3(_006_),
    .ZN(_090_)
  );
  NOR2_X1 _347_ (
    .A1(_069_),
    .A2(_090_),
    .ZN(_091_)
  );
  INV_X1 _348_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_041_)
  );
  AOI221_X1 _349_ (
    .A(\u_scheduler.state [2]),
    .B1(\u_scheduler.state [0]),
    .B2(_003_),
    .C1(_006_),
    .C2(\u_scheduler.state [1]),
    .ZN(_092_)
  );
  NAND2_X1 _350_ (
    .A1(_088_),
    .A2(_092_),
    .ZN(_093_)
  );
  AOI21_X1 _351_ (
    .A(_093_),
    .B1(_086_),
    .B2(_059_),
    .ZN(_094_)
  );
  NOR3_X1 _352_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(_002_),
    .ZN(_095_)
  );
  NOR2_X1 _353_ (
    .A1(_092_),
    .A2(_095_),
    .ZN(_096_)
  );
  NOR2_X1 _354_ (
    .A1(_094_),
    .A2(_096_),
    .ZN(_097_)
  );
  NAND2_X1 _355_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_098_)
  );
  NOR3_X1 _356_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_098_),
    .ZN(_099_)
  );
  NAND2_X1 _357_ (
    .A1(_088_),
    .A2(_090_),
    .ZN(_100_)
  );
  OR4_X1 _358_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_098_),
    .A4(_100_),
    .ZN(_101_)
  );
  INV_X1 _359_ (
    .A(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_042_)
  );
  INV_X1 _360_ (
    .A(_101_),
    .ZN(stage_done)
  );
  NOR2_X1 _361_ (
    .A1(_036_),
    .A2(_101_),
    .ZN(_007_)
  );
  AND2_X1 _362_ (
    .A1(rst_n),
    .A2(_004_),
    .ZN(busy)
  );
  NOR4_X1 _363_ (
    .A1(_091_),
    .A2(_094_),
    .A3(_096_),
    .A4(_098_),
    .ZN(scheduler_quiescent)
  );
  NOR2_X1 _364_ (
    .A1(_039_),
    .A2(_066_),
    .ZN(_102_)
  );
  NAND2_X1 _365_ (
    .A1(scheduler_quiescent),
    .A2(_102_),
    .ZN(_103_)
  );
  OAI22_X1 _366_ (
    .A1(\u_controller.state [5]),
    .A2(_061_),
    .B1(_066_),
    .B2(abort_req),
    .ZN(_104_)
  );
  INV_X1 _367_ (
    .A(_104_),
    .ZN(_105_)
  );
  NOR2_X1 _368_ (
    .A1(zeroize),
    .A2(_105_),
    .ZN(_106_)
  );
  NAND2_X1 _369_ (
    .A1(\u_controller.state [7]),
    .A2(_106_),
    .ZN(_107_)
  );
  INV_X1 _370_ (
    .A(batch_retired),
    .ZN(_043_)
  );
  AOI21_X1 _371_ (
    .A(_107_),
    .B1(_102_),
    .B2(scheduler_quiescent),
    .ZN(_108_)
  );
  OR2_X1 _372_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .ZN(_109_)
  );
  OR2_X1 _373_ (
    .A1(_108_),
    .A2(_109_),
    .ZN(_014_)
  );
  AOI21_X1 _374_ (
    .A(cfg_span_descending),
    .B1(cfg_first_span_log2[0]),
    .B2(_038_),
    .ZN(_110_)
  );
  AOI21_X1 _375_ (
    .A(cfg_last_stage[1]),
    .B1(cfg_last_stage[0]),
    .B2(_055_),
    .ZN(_111_)
  );
  OAI21_X1 _376_ (
    .A(_046_),
    .B1(_110_),
    .B2(_111_),
    .ZN(_112_)
  );
  OAI21_X1 _377_ (
    .A(_044_),
    .B1(cfg_last_stage[0]),
    .B2(cfg_last_stage[1]),
    .ZN(_113_)
  );
  NAND3_X1 _378_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_055_),
    .A3(_113_),
    .ZN(_114_)
  );
  AOI22_X1 _379_ (
    .A1(cfg_last_stage[1]),
    .A2(cfg_last_stage[0]),
    .B1(_112_),
    .B2(_114_),
    .ZN(_115_)
  );
  NAND2_X1 _380_ (
    .A1(\u_controller.state [0]),
    .A2(enable),
    .ZN(_116_)
  );
  INV_X1 _381_ (
    .A(cfg_span_descending),
    .ZN(_044_)
  );
  NOR2_X1 _382_ (
    .A1(backend_flushed),
    .A2(_116_),
    .ZN(_117_)
  );
  AND4_X1 _383_ (
    .A1(_067_),
    .A2(scheduler_quiescent),
    .A3(_115_),
    .A4(_117_),
    .ZN(ready)
  );
  AND2_X1 _384_ (
    .A1(start),
    .A2(ready),
    .ZN(_012_)
  );
  NAND3_X1 _385_ (
    .A1(_047_),
    .A2(_067_),
    .A3(_115_),
    .ZN(_118_)
  );
  NOR2_X1 _386_ (
    .A1(_116_),
    .A2(_118_),
    .ZN(_119_)
  );
  AND3_X1 _387_ (
    .A1(start),
    .A2(scheduler_quiescent),
    .A3(_119_),
    .ZN(_120_)
  );
  AND2_X1 _388_ (
    .A1(_067_),
    .A2(_117_),
    .ZN(_121_)
  );
  NAND4_X1 _389_ (
    .A1(start),
    .A2(scheduler_quiescent),
    .A3(_115_),
    .A4(_121_),
    .ZN(_122_)
  );
  NAND2_X1 _390_ (
    .A1(start),
    .A2(enable),
    .ZN(_123_)
  );
  NOR3_X1 _391_ (
    .A1(_004_),
    .A2(_115_),
    .A3(_123_),
    .ZN(_124_)
  );
  DFFS_X1 _392_ (
    .CK(clk),
    .D(_010_),
    .Q(\u_controller.state [0]),
    .QN(_004_),
    .SN(rst_n)
  );
  DFFR_X1 _393_ (
    .CK(clk),
    .D(_007_),
    .Q(\u_controller.state [1]),
    .QN(_195_),
    .RN(rst_n)
  );
  DFFR_X1 _394_ (
    .CK(clk),
    .D(_011_),
    .Q(\u_controller.state [2]),
    .QN(_194_),
    .RN(rst_n)
  );
  DFFR_X1 _395_ (
    .CK(clk),
    .D(_008_),
    .Q(\u_controller.state [3]),
    .QN(_193_),
    .RN(rst_n)
  );
  DFFR_X1 _396_ (
    .CK(clk),
    .D(_012_),
    .Q(\u_controller.state [4]),
    .QN(_192_),
    .RN(rst_n)
  );
  DFFR_X1 _397_ (
    .CK(clk),
    .D(_009_),
    .Q(\u_controller.state [5]),
    .QN(_196_),
    .RN(rst_n)
  );
  DFFR_X1 _398_ (
    .CK(clk),
    .D(_013_),
    .Q(\u_controller.state [6]),
    .QN(_190_),
    .RN(rst_n)
  );
  DFFR_X1 _399_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_controller.state [7]),
    .QN(_197_),
    .RN(rst_n)
  );
  DFFR_X1 _400_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_scheduler.intt_q ),
    .QN(_189_),
    .RN(rst_n)
  );
  DFFR_X1 _401_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_scheduler.span_q [0]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _402_ (
    .CK(clk),
    .D(_019_),
    .Q(\u_scheduler.span_q [1]),
    .QN(_188_),
    .RN(rst_n)
  );
  DFFR_X1 _403_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_scheduler.stage_q [0]),
    .QN(_191_),
    .RN(rst_n)
  );
  DFFR_X1 _404_ (
    .CK(clk),
    .D(_020_),
    .Q(\u_scheduler.stage_q [1]),
    .QN(_187_),
    .RN(rst_n)
  );
  DFFR_X1 _405_ (
    .CK(clk),
    .D(_021_),
    .Q(\u_scheduler.batch_index_q ),
    .QN(_178_),
    .RN(rst_n)
  );
  DFFR_X1 _406_ (
    .CK(clk),
    .D(_022_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_186_),
    .RN(rst_n)
  );
  DFFR_X1 _407_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.u_stage_counter.last_stage_q [0]),
    .QN(_175_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _408_ (
    .CK(clk),
    .D(_024_),
    .Q(\u_controller.u_stage_counter.last_stage_q [1]),
    .QN(_175_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _409_ (
    .CK(clk),
    .D(_025_),
    .Q(\u_controller.u_stage_counter.stage_count [0]),
    .QN(_179_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _410_ (
    .CK(clk),
    .D(_026_),
    .Q(\u_controller.u_stage_counter.stage_count [1]),
    .QN(_176_),
    .RN(rst_n)
  );
  DFFR_X1 _411_ (
    .CK(clk),
    .D(_027_),
    .Q(descending_q),
    .QN(_185_),
    .RN(rst_n)
  );
  DFFR_X1 _412_ (
    .CK(clk),
    .D(_028_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _413_ (
    .CK(clk),
    .D(_023_),
    .Q(first_span_q[0]),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _414_ (
    .CK(clk),
    .D(_029_),
    .Q(first_span_q[1]),
    .QN(_177_),
    .RN(rst_n)
  );
  DFFR_X1 _415_ (
    .CK(clk),
    .D(_030_),
    .Q(error_controller),
    .QN(_184_),
    .RN(rst_n)
  );
  DFFR_X1 _416_ (
    .CK(clk),
    .D(_031_),
    .Q(error_scheduler),
    .QN(_183_),
    .RN(rst_n)
  );
  DFFR_X1 _417_ (
    .CK(clk),
    .D(_032_),
    .Q(error_datapath),
    .QN(_182_),
    .RN(rst_n)
  );
  DFFR_X1 _418_ (
    .CK(clk),
    .D(_033_),
    .Q(error_ecc),
    .QN(_181_),
    .RN(rst_n)
  );
  DFFR_X1 _419_ (
    .CK(clk),
    .D(_034_),
    .Q(error_config),
    .QN(_180_),
    .RN(rst_n)
  );
  DFFR_X1 _420_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _421_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _422_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_002_),
    .RN(rst_n)
  );
  assign _179_[1] = \u_controller.u_stage_counter.stage_count [1];
  assign \u_scheduler.decode_lanes.ordinal  = { \u_scheduler.batch_index_q , 2'h3 };
  assign \u_scheduler.distance_mask [1:0] = { coeff_addr_b[1], coeff_addr_a[4] };
  assign \u_scheduler.low_mask [1:0] = { coeff_addr_a[7], coeff_addr_a[3] };
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = 8'he4;
  assign \u_scheduler.coeff_addr_b  = { coeff_addr_b[8], 2'h3, coeff_addr_b[8:7], coeff_addr_a[4], coeff_addr_b[2], coeff_addr_b[4], 1'h1, coeff_addr_b[2:1], coeff_addr_a[4] };
  assign \u_scheduler.coeff_addr_a  = { coeff_addr_a[8], coeff_addr_a[10], coeff_addr_a[3], coeff_addr_a[8:7], 1'h0, coeff_addr_a[2], coeff_addr_a[4:2], 2'h0 };
  assign \u_scheduler.lane_valid  = { batch_valid, batch_valid, batch_valid, batch_valid };
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.next_state [3] = 1'h0;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = 8'he4;
  assign { coeff_addr_b[11:9], coeff_addr_b[6:5], coeff_addr_b[3], coeff_addr_b[0] } = { coeff_addr_b[8], 2'h3, coeff_addr_a[4], coeff_addr_b[2], 1'h1, coeff_addr_a[4] };
  assign { coeff_addr_a[11], coeff_addr_a[9], coeff_addr_a[6:5], coeff_addr_a[1:0] } = { coeff_addr_a[8], coeff_addr_a[3], 1'h0, coeff_addr_a[2], 2'h0 };
  assign lane_valid = { batch_valid, batch_valid, batch_valid, batch_valid };
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
