/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input cfg_last_stage;
  wire cfg_last_stage;
  input cfg_first_span_log2;
  wire cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output stage_count;
  wire stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output [7:0] lane_valid;
  wire [7:0] lane_valid;
  output [15:0] coeff_addr_a;
  wire [15:0] coeff_addr_a;
  output [15:0] coeff_addr_b;
  wire [15:0] coeff_addr_b;
  output [7:0] butterfly_index;
  wire [7:0] butterfly_index;
  output batch_stage;
  wire batch_stage;
  output batch_span_log2;
  wire batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire [0:0] _143_;
  wire [0:0] _144_;
  wire [0:0] _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire descending_q;
  wire first_span_q;
  wire range_valid;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire \u_controller.cfg_last_stage ;
  wire \u_controller.cfg_valid ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.cfg_valid ;
  wire \u_controller.u_stage_counter.clk ;
  wire \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire \u_scheduler.batch_span_log2 ;
  wire \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [7:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [15:0] \u_scheduler.coeff_addr_a ;
  wire [15:0] \u_scheduler.coeff_addr_b ;
  wire [1:0] \u_scheduler.decode_lanes.ordinal ;
  wire [1:0] \u_scheduler.distance_mask ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire [7:0] \u_scheduler.lane_valid ;
  wire [1:0] \u_scheduler.low_mask ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.range_valid ;
  wire \u_scheduler.rst_n ;
  wire \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire \u_scheduler.span_q ;
  wire \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _163_ (
    .A(cfg_last_stage),
    .ZN(_131_)
  );
  INV_X1 _164_ (
    .A(cfg_span_descending),
    .ZN(_132_)
  );
  INV_X1 _165_ (
    .A(first_span_q),
    .ZN(_141_)
  );
  NAND4_X1 _166_ (
    .A1(\u_scheduler.state [2]),
    .A2(_032_),
    .A3(_047_),
    .A4(_097_),
    .ZN(_098_)
  );
  NAND3_X1 _167_ (
    .A1(_071_),
    .A2(_096_),
    .A3(_098_),
    .ZN(\u_scheduler.next_state [2])
  );
  OAI22_X1 _168_ (
    .A1(_132_),
    .A2(_085_),
    .B1(_092_),
    .B2(_142_),
    .ZN(_020_)
  );
  AND4_X1 _169_ (
    .A1(scrub_done),
    .A2(_044_),
    .A3(_057_),
    .A4(_073_),
    .ZN(_099_)
  );
  AND2_X1 _170_ (
    .A1(_137_),
    .A2(_079_),
    .ZN(_100_)
  );
  NAND2_X1 _171_ (
    .A1(\u_controller.state [7]),
    .A2(_100_),
    .ZN(_101_)
  );
  OAI211_X1 _172_ (
    .A(_137_),
    .B(_041_),
    .C1(_099_),
    .C2(_101_),
    .ZN(_012_)
  );
  NAND3_X1 _173_ (
    .A1(\u_controller.state [6]),
    .A2(_073_),
    .A3(_093_),
    .ZN(_102_)
  );
  INV_X1 _174_ (
    .A(_102_),
    .ZN(_005_)
  );
  NAND3_X1 _175_ (
    .A1(\u_controller.state [1]),
    .A2(_059_),
    .A3(_074_),
    .ZN(_103_)
  );
  INV_X1 _176_ (
    .A(descending_q),
    .ZN(_142_)
  );
  NOR4_X1 _177_ (
    .A1(_133_),
    .A2(\u_controller.u_stage_counter.stage_count ),
    .A3(_143_),
    .A4(_006_),
    .ZN(_104_)
  );
  NAND3_X1 _178_ (
    .A1(_085_),
    .A2(_102_),
    .A3(_104_),
    .ZN(_105_)
  );
  NAND2_X1 _179_ (
    .A1(\u_controller.state [6]),
    .A2(_059_),
    .ZN(_106_)
  );
  OAI21_X1 _180_ (
    .A(_060_),
    .B1(stage_done),
    .B2(_106_),
    .ZN(_011_)
  );
  NOR3_X1 _181_ (
    .A1(_012_),
    .A2(_105_),
    .A3(_011_),
    .ZN(_107_)
  );
  OR2_X1 _182_ (
    .A1(\u_controller.state [0]),
    .A2(_078_),
    .ZN(_108_)
  );
  NOR4_X1 _183_ (
    .A1(_145_),
    .A2(_012_),
    .A3(_105_),
    .A4(_011_),
    .ZN(_109_)
  );
  OAI21_X1 _184_ (
    .A(_108_),
    .B1(_107_),
    .B2(\u_controller.u_stage_counter.stage_count ),
    .ZN(_110_)
  );
  NOR3_X1 _185_ (
    .A1(_010_),
    .A2(_109_),
    .A3(_110_),
    .ZN(_019_)
  );
  NOR4_X1 _186_ (
    .A1(\u_scheduler.state [1]),
    .A2(\u_scheduler.state [2]),
    .A3(_003_),
    .A4(_069_),
    .ZN(_111_)
  );
  INV_X1 _187_ (
    .A(\u_controller.u_stage_counter.stage_count ),
    .ZN(_028_)
  );
  NAND3_X1 _188_ (
    .A1(\u_controller.state [6]),
    .A2(_073_),
    .A3(_111_),
    .ZN(_112_)
  );
  INV_X1 _189_ (
    .A(_112_),
    .ZN(batch_valid)
  );
  OAI21_X1 _190_ (
    .A(_108_),
    .B1(_010_),
    .B2(\u_controller.u_stage_counter.last_stage_q ),
    .ZN(_113_)
  );
  AOI21_X1 _191_ (
    .A(_113_),
    .B1(_010_),
    .B2(_131_),
    .ZN(_018_)
  );
  NOR2_X1 _192_ (
    .A1(_134_),
    .A2(_139_),
    .ZN(butterfly_enable)
  );
  OAI21_X1 _193_ (
    .A(_108_),
    .B1(_010_),
    .B2(\u_controller.intt_mode_q ),
    .ZN(_114_)
  );
  AOI21_X1 _194_ (
    .A(_114_),
    .B1(_010_),
    .B2(_030_),
    .ZN(_017_)
  );
  NOR3_X1 _195_ (
    .A1(_034_),
    .A2(_042_),
    .A3(_069_),
    .ZN(_115_)
  );
  NAND3_X1 _196_ (
    .A1(stage_start),
    .A2(_071_),
    .A3(_115_),
    .ZN(_116_)
  );
  NOR3_X1 _197_ (
    .A1(_138_),
    .A2(_045_),
    .A3(_069_),
    .ZN(_117_)
  );
  INV_X1 _198_ (
    .A(cfg_first_span_log2),
    .ZN(_029_)
  );
  NAND2_X1 _199_ (
    .A1(\u_scheduler.state [0]),
    .A2(_111_),
    .ZN(_118_)
  );
  AOI21_X1 _200_ (
    .A(_118_),
    .B1(batch_valid),
    .B2(batch_ready),
    .ZN(_119_)
  );
  OAI21_X1 _201_ (
    .A(_071_),
    .B1(_117_),
    .B2(_119_),
    .ZN(_120_)
  );
  NAND2_X1 _202_ (
    .A1(_116_),
    .A2(_120_),
    .ZN(\u_scheduler.next_state [0])
  );
  NAND3_X1 _203_ (
    .A1(\u_scheduler.state [1]),
    .A2(_068_),
    .A3(_095_),
    .ZN(_121_)
  );
  NAND2_X1 _204_ (
    .A1(_144_),
    .A2(_117_),
    .ZN(_122_)
  );
  OAI211_X1 _205_ (
    .A(_121_),
    .B(_122_),
    .C1(_035_),
    .C2(_112_),
    .ZN(_123_)
  );
  NOR2_X1 _206_ (
    .A1(_045_),
    .A2(_123_),
    .ZN(_124_)
  );
  OR4_X1 _207_ (
    .A1(\u_scheduler.next_state [2]),
    .A2(_117_),
    .A3(_119_),
    .A4(_123_),
    .ZN(_125_)
  );
  NAND2_X1 _208_ (
    .A1(_116_),
    .A2(_125_),
    .ZN(_126_)
  );
  INV_X1 _209_ (
    .A(intt_mode),
    .ZN(_030_)
  );
  AOI211_X1 _210_ (
    .A(_037_),
    .B(_126_),
    .C1(_124_),
    .C2(\u_scheduler.next_state [0]),
    .ZN(_016_)
  );
  OAI22_X1 _211_ (
    .A1(_028_),
    .A2(_116_),
    .B1(_126_),
    .B2(_038_),
    .ZN(_015_)
  );
  XOR2_X1 _212_ (
    .A(_145_),
    .B(first_span_q),
    .Z(_127_)
  );
  OAI22_X1 _213_ (
    .A1(_039_),
    .A2(_126_),
    .B1(_127_),
    .B2(_116_),
    .ZN(_014_)
  );
  OAI22_X1 _214_ (
    .A1(_036_),
    .A2(_116_),
    .B1(_126_),
    .B2(_040_),
    .ZN(_013_)
  );
  NAND2_X1 _215_ (
    .A1(\u_controller.state [4]),
    .A2(_059_),
    .ZN(_128_)
  );
  NOR2_X1 _216_ (
    .A1(_134_),
    .A2(_128_),
    .ZN(load_start)
  );
  AND2_X1 _217_ (
    .A1(rst_n),
    .A2(_078_),
    .ZN(active)
  );
  NAND3_X1 _218_ (
    .A1(\u_controller.state [0]),
    .A2(_085_),
    .A3(_100_),
    .ZN(_129_)
  );
  NAND3_X1 _219_ (
    .A1(\u_controller.state [7]),
    .A2(_099_),
    .A3(_100_),
    .ZN(_130_)
  );
  INV_X1 _220_ (
    .A(\u_controller.state [2]),
    .ZN(_031_)
  );
  NAND3_X1 _221_ (
    .A1(_075_),
    .A2(_129_),
    .A3(_130_),
    .ZN(_008_)
  );
  NAND2_X1 _222_ (
    .A1(_103_),
    .A2(_128_),
    .ZN(_009_)
  );
  AND2_X1 _223_ (
    .A1(_071_),
    .A2(_123_),
    .ZN(\u_scheduler.next_state [1])
  );
  INV_X1 _224_ (
    .A(backend_flushed),
    .ZN(_032_)
  );
  INV_X1 _225_ (
    .A(\u_controller.state [0]),
    .ZN(_033_)
  );
  INV_X1 _226_ (
    .A(_000_),
    .ZN(_034_)
  );
  INV_X1 _227_ (
    .A(batch_ready),
    .ZN(_035_)
  );
  INV_X1 _228_ (
    .A(\u_controller.state [1]),
    .ZN(_133_)
  );
  INV_X1 _229_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_036_)
  );
  INV_X1 _230_ (
    .A(\u_scheduler.batch_index_q ),
    .ZN(_037_)
  );
  INV_X1 _231_ (
    .A(\u_scheduler.stage_q ),
    .ZN(_038_)
  );
  INV_X1 _232_ (
    .A(\u_scheduler.span_q ),
    .ZN(_039_)
  );
  INV_X1 _233_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_040_)
  );
  INV_X1 _234_ (
    .A(\u_controller.state [3]),
    .ZN(_041_)
  );
  OR3_X1 _235_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(\u_scheduler.state [2]),
    .ZN(_042_)
  );
  OR3_X1 _236_ (
    .A1(\u_scheduler.state [2]),
    .A2(_002_),
    .A3(_003_),
    .ZN(_043_)
  );
  NAND2_X1 _237_ (
    .A1(_042_),
    .A2(_043_),
    .ZN(_044_)
  );
  OR3_X1 _238_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [2]),
    .A3(_002_),
    .ZN(_045_)
  );
  INV_X1 _239_ (
    .A(rst_n),
    .ZN(_134_)
  );
  AOI221_X1 _240_ (
    .A(\u_scheduler.state [2]),
    .B1(_002_),
    .B2(\u_scheduler.state [1]),
    .C1(_003_),
    .C2(\u_scheduler.state [0]),
    .ZN(_046_)
  );
  NOR3_X1 _241_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(_001_),
    .ZN(_047_)
  );
  NOR2_X1 _242_ (
    .A1(_046_),
    .A2(_047_),
    .ZN(_048_)
  );
  NOR3_X1 _243_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_049_)
  );
  NOR3_X1 _244_ (
    .A1(\u_controller.state [1]),
    .A2(\u_controller.state [6]),
    .A3(\u_controller.state [5]),
    .ZN(_050_)
  );
  NOR2_X1 _245_ (
    .A1(\u_controller.state [2]),
    .A2(\u_controller.state [4]),
    .ZN(_051_)
  );
  NOR3_X1 _246_ (
    .A1(_134_),
    .A2(\u_controller.state [7]),
    .A3(\u_controller.state [0]),
    .ZN(_052_)
  );
  NAND3_X1 _247_ (
    .A1(_050_),
    .A2(_051_),
    .A3(_052_),
    .ZN(_053_)
  );
  INV_X1 _248_ (
    .A(_053_),
    .ZN(transform_abort)
  );
  NOR3_X1 _249_ (
    .A1(\u_controller.state [7]),
    .A2(\u_controller.state [2]),
    .A3(\u_controller.state [4]),
    .ZN(_054_)
  );
  INV_X1 _250_ (
    .A(abort_req),
    .ZN(_135_)
  );
  NAND4_X1 _251_ (
    .A1(rst_n),
    .A2(_033_),
    .A3(_050_),
    .A4(_054_),
    .ZN(_055_)
  );
  OR2_X1 _252_ (
    .A1(\u_controller.state [3]),
    .A2(_055_),
    .ZN(_056_)
  );
  AND2_X1 _253_ (
    .A1(_049_),
    .A2(_056_),
    .ZN(_057_)
  );
  OAI211_X1 _254_ (
    .A(_135_),
    .B(_049_),
    .C1(_055_),
    .C2(\u_controller.state [3]),
    .ZN(_058_)
  );
  NOR2_X1 _255_ (
    .A1(zeroize),
    .A2(_058_),
    .ZN(_059_)
  );
  NAND2_X1 _256_ (
    .A1(\u_controller.state [2]),
    .A2(_059_),
    .ZN(_060_)
  );
  OR4_X1 _257_ (
    .A1(_134_),
    .A2(zeroize),
    .A3(_031_),
    .A4(_058_),
    .ZN(_061_)
  );
  INV_X1 _258_ (
    .A(_061_),
    .ZN(stage_start)
  );
  OR4_X1 _259_ (
    .A1(_145_),
    .A2(first_span_q),
    .A3(descending_q),
    .A4(_028_),
    .ZN(_062_)
  );
  OAI22_X1 _260_ (
    .A1(_145_),
    .A2(first_span_q),
    .B1(descending_q),
    .B2(_028_),
    .ZN(_063_)
  );
  INV_X1 _261_ (
    .A(start),
    .ZN(_136_)
  );
  AOI211_X1 _262_ (
    .A(backend_flushed),
    .B(_042_),
    .C1(_062_),
    .C2(_063_),
    .ZN(_064_)
  );
  AOI22_X1 _263_ (
    .A1(backend_flushed),
    .A2(_042_),
    .B1(_045_),
    .B2(batch_retired),
    .ZN(_065_)
  );
  OAI21_X1 _264_ (
    .A(_065_),
    .B1(_064_),
    .B2(_061_),
    .ZN(_066_)
  );
  NAND2_X1 _265_ (
    .A1(rst_n),
    .A2(\u_controller.state [7]),
    .ZN(_067_)
  );
  INV_X1 _266_ (
    .A(_067_),
    .ZN(zeroize_req)
  );
  NOR3_X1 _267_ (
    .A1(zeroize),
    .A2(_058_),
    .A3(zeroize_req),
    .ZN(_068_)
  );
  NAND2_X1 _268_ (
    .A1(_059_),
    .A2(_067_),
    .ZN(_069_)
  );
  AND2_X1 _269_ (
    .A1(_046_),
    .A2(_068_),
    .ZN(_070_)
  );
  AOI21_X1 _270_ (
    .A(_048_),
    .B1(_066_),
    .B2(_070_),
    .ZN(_071_)
  );
  NAND2_X1 _271_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_072_)
  );
  INV_X1 _272_ (
    .A(zeroize),
    .ZN(_137_)
  );
  AOI211_X1 _273_ (
    .A(_048_),
    .B(_072_),
    .C1(_070_),
    .C2(_066_),
    .ZN(_073_)
  );
  AND2_X1 _274_ (
    .A1(_044_),
    .A2(_073_),
    .ZN(scheduler_quiescent)
  );
  XNOR2_X1 _275_ (
    .A(\u_controller.u_stage_counter.stage_count ),
    .B(_143_),
    .ZN(_074_)
  );
  NOR4_X1 _276_ (
    .A1(_133_),
    .A2(zeroize),
    .A3(_058_),
    .A4(_074_),
    .ZN(_007_)
  );
  NAND2_X1 _277_ (
    .A1(\u_controller.state [5]),
    .A2(_059_),
    .ZN(_075_)
  );
  NOR2_X1 _278_ (
    .A1(_134_),
    .A2(_075_),
    .ZN(done)
  );
  AND2_X1 _279_ (
    .A1(rst_n),
    .A2(_004_),
    .ZN(busy)
  );
  NAND2_X1 _280_ (
    .A1(backend_flushed),
    .A2(_047_),
    .ZN(_076_)
  );
  NAND2_X1 _281_ (
    .A1(\u_scheduler.fault_q ),
    .A2(_076_),
    .ZN(_077_)
  );
  NAND2_X1 _282_ (
    .A1(_071_),
    .A2(_077_),
    .ZN(_027_)
  );
  INV_X1 _283_ (
    .A(batch_retired),
    .ZN(_138_)
  );
  NAND3_X1 _284_ (
    .A1(_133_),
    .A2(_139_),
    .A3(_051_),
    .ZN(_078_)
  );
  OAI21_X1 _285_ (
    .A(_058_),
    .B1(_078_),
    .B2(\u_controller.state [5]),
    .ZN(_079_)
  );
  NOR2_X1 _286_ (
    .A1(zeroize),
    .A2(_079_),
    .ZN(_006_)
  );
  AND2_X1 _287_ (
    .A1(enable),
    .A2(_059_),
    .ZN(_080_)
  );
  OAI21_X1 _288_ (
    .A(cfg_last_stage),
    .B1(cfg_span_descending),
    .B2(cfg_first_span_log2),
    .ZN(_081_)
  );
  AOI21_X1 _289_ (
    .A(_081_),
    .B1(cfg_first_span_log2),
    .B2(cfg_span_descending),
    .ZN(_082_)
  );
  NOR2_X1 _290_ (
    .A1(backend_flushed),
    .A2(_082_),
    .ZN(_083_)
  );
  AND3_X1 _291_ (
    .A1(\u_controller.state [0]),
    .A2(_080_),
    .A3(_083_),
    .ZN(_084_)
  );
  AND2_X1 _292_ (
    .A1(scheduler_quiescent),
    .A2(_084_),
    .ZN(ready)
  );
  NAND4_X1 _293_ (
    .A1(start),
    .A2(_044_),
    .A3(_073_),
    .A4(_084_),
    .ZN(_085_)
  );
  INV_X1 _294_ (
    .A(\u_controller.state [6]),
    .ZN(_139_)
  );
  INV_X1 _295_ (
    .A(_085_),
    .ZN(_010_)
  );
  NOR3_X1 _296_ (
    .A1(_134_),
    .A2(_136_),
    .A3(_004_),
    .ZN(_086_)
  );
  NAND3_X1 _297_ (
    .A1(_080_),
    .A2(_082_),
    .A3(_086_),
    .ZN(_087_)
  );
  OAI21_X1 _298_ (
    .A(_087_),
    .B1(_010_),
    .B2(_140_),
    .ZN(_026_)
  );
  AOI21_X1 _299_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_085_),
    .ZN(_088_)
  );
  INV_X1 _300_ (
    .A(_088_),
    .ZN(_025_)
  );
  AOI21_X1 _301_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_085_),
    .ZN(_089_)
  );
  INV_X1 _302_ (
    .A(_089_),
    .ZN(_024_)
  );
  AOI21_X1 _303_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_085_),
    .ZN(_090_)
  );
  INV_X1 _304_ (
    .A(_090_),
    .ZN(_023_)
  );
  INV_X1 _305_ (
    .A(error_config),
    .ZN(_140_)
  );
  NAND2_X1 _306_ (
    .A1(error_controller),
    .A2(_085_),
    .ZN(_091_)
  );
  OAI21_X1 _307_ (
    .A(_091_),
    .B1(_053_),
    .B2(\u_controller.state [3]),
    .ZN(_022_)
  );
  NAND2_X1 _308_ (
    .A1(_067_),
    .A2(_085_),
    .ZN(_092_)
  );
  OAI22_X1 _309_ (
    .A1(_029_),
    .A2(_085_),
    .B1(_092_),
    .B2(_141_),
    .ZN(_021_)
  );
  NOR2_X1 _310_ (
    .A1(_043_),
    .A2(_069_),
    .ZN(_093_)
  );
  AND2_X1 _311_ (
    .A1(_073_),
    .A2(_093_),
    .ZN(stage_done)
  );
  NAND2_X1 _312_ (
    .A1(backend_flushed),
    .A2(_069_),
    .ZN(_094_)
  );
  NOR2_X1 _313_ (
    .A1(batch_retired),
    .A2(_045_),
    .ZN(_095_)
  );
  OAI211_X1 _314_ (
    .A(_094_),
    .B(_095_),
    .C1(\u_scheduler.state [2]),
    .C2(_069_),
    .ZN(_096_)
  );
  NAND2_X1 _315_ (
    .A1(batch_retired),
    .A2(_000_),
    .ZN(_097_)
  );
  DFFS_X1 _316_ (
    .CK(clk),
    .D(_008_),
    .Q(\u_controller.state [0]),
    .QN(_004_),
    .SN(rst_n)
  );
  DFFR_X1 _317_ (
    .CK(clk),
    .D(_005_),
    .Q(\u_controller.state [1]),
    .QN(_158_),
    .RN(rst_n)
  );
  DFFR_X1 _318_ (
    .CK(clk),
    .D(_009_),
    .Q(\u_controller.state [2]),
    .QN(_146_),
    .RN(rst_n)
  );
  DFFR_X1 _319_ (
    .CK(clk),
    .D(_006_),
    .Q(\u_controller.state [3]),
    .QN(_153_),
    .RN(rst_n)
  );
  DFFR_X1 _320_ (
    .CK(clk),
    .D(_010_),
    .Q(\u_controller.state [4]),
    .QN(_154_),
    .RN(rst_n)
  );
  DFFR_X1 _321_ (
    .CK(clk),
    .D(_007_),
    .Q(\u_controller.state [5]),
    .QN(_161_),
    .RN(rst_n)
  );
  DFFR_X1 _322_ (
    .CK(clk),
    .D(_011_),
    .Q(\u_controller.state [6]),
    .QN(_160_),
    .RN(rst_n)
  );
  DFFR_X1 _323_ (
    .CK(clk),
    .D(_012_),
    .Q(\u_controller.state [7]),
    .QN(_157_),
    .RN(rst_n)
  );
  DFFR_X1 _324_ (
    .CK(clk),
    .D(_013_),
    .Q(\u_scheduler.intt_q ),
    .QN(_156_),
    .RN(rst_n)
  );
  DFFR_X1 _325_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_scheduler.span_q ),
    .QN(coeff_addr_a[3]),
    .RN(rst_n)
  );
  DFFR_X1 _326_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_scheduler.stage_q ),
    .QN(_155_),
    .RN(rst_n)
  );
  DFFR_X1 _327_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_scheduler.batch_index_q ),
    .QN(_144_),
    .RN(rst_n)
  );
  DFFR_X1 _328_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_159_),
    .RN(rst_n)
  );
  DFFR_X1 _329_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.u_stage_counter.last_stage_q ),
    .QN(_143_),
    .RN(rst_n)
  );
  DFFR_X1 _330_ (
    .CK(clk),
    .D(_019_),
    .Q(\u_controller.u_stage_counter.stage_count ),
    .QN(_145_),
    .RN(rst_n)
  );
  DFFR_X1 _331_ (
    .CK(clk),
    .D(_020_),
    .Q(descending_q),
    .QN(_162_),
    .RN(rst_n)
  );
  DFFR_X1 _332_ (
    .CK(clk),
    .D(_021_),
    .Q(first_span_q),
    .QN(_152_),
    .RN(rst_n)
  );
  DFFR_X1 _333_ (
    .CK(clk),
    .D(_022_),
    .Q(error_controller),
    .QN(_151_),
    .RN(rst_n)
  );
  DFFR_X1 _334_ (
    .CK(clk),
    .D(_023_),
    .Q(error_scheduler),
    .QN(_150_),
    .RN(rst_n)
  );
  DFFR_X1 _335_ (
    .CK(clk),
    .D(_024_),
    .Q(error_datapath),
    .QN(_149_),
    .RN(rst_n)
  );
  DFFR_X1 _336_ (
    .CK(clk),
    .D(_025_),
    .Q(error_ecc),
    .QN(_148_),
    .RN(rst_n)
  );
  DFFR_X1 _337_ (
    .CK(clk),
    .D(_026_),
    .Q(error_config),
    .QN(_147_),
    .RN(rst_n)
  );
  DFFR_X1 _338_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _339_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _340_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _341_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_001_),
    .RN(rst_n)
  );
  assign \u_scheduler.decode_lanes.ordinal  = 2'h1;
  assign \u_scheduler.range_valid  = 1'h1;
  assign \u_scheduler.distance_mask  = { \u_scheduler.span_q , coeff_addr_a[3] };
  assign \u_scheduler.low_mask  = { 1'hx, \u_scheduler.span_q  };
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = 8'h02;
  assign \u_scheduler.coeff_addr_b  = { 14'h0003, \u_scheduler.span_q , coeff_addr_a[3] };
  assign \u_scheduler.coeff_addr_a  = { 12'h000, coeff_addr_a[3], \u_scheduler.span_q , 2'h0 };
  assign \u_scheduler.lane_valid  = { 6'h00, batch_valid, batch_valid };
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_valid  = 1'h1;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.cfg_valid  = 1'h1;
  assign \u_controller.next_state [3] = 1'h0;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign range_valid = 1'h1;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = 8'h02;
  assign coeff_addr_b = { 14'h0003, \u_scheduler.span_q , coeff_addr_a[3] };
  assign { coeff_addr_a[15:4], coeff_addr_a[2:0] } = { 12'h000, \u_scheduler.span_q , 2'h0 };
  assign lane_valid = { 6'h00, batch_valid, batch_valid };
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
