/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input [3:0] cfg_last_stage;
  wire [3:0] cfg_last_stage;
  input [3:0] cfg_first_span_log2;
  wire [3:0] cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output [3:0] stage_count;
  wire [3:0] stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output [7:0] lane_valid;
  wire [7:0] lane_valid;
  output [71:0] coeff_addr_a;
  wire [71:0] coeff_addr_a;
  output [71:0] coeff_addr_b;
  wire [71:0] coeff_addr_b;
  output [63:0] butterfly_index;
  wire [63:0] butterfly_index;
  output [3:0] batch_stage;
  wire [3:0] batch_stage;
  output [3:0] batch_span_log2;
  wire [3:0] batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire [3:0] _310_;
  wire [0:0] _311_;
  wire [0:0] _312_;
  wire [4:0] _313_;
  wire [3:0] _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire [4:0] _337_;
  wire descending_q;
  wire [3:0] first_span_q;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire [3:0] \u_controller.cfg_last_stage ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire [3:0] \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire [3:0] \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.clk ;
  wire [3:0] \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire [3:0] \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire [4:0] \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire [3:0] \u_scheduler.batch_span_log2 ;
  wire [3:0] \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [63:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [71:0] \u_scheduler.coeff_addr_a ;
  wire [71:0] \u_scheduler.coeff_addr_b ;
  wire [8:0] \u_scheduler.decode_lanes.ordinal ;
  wire [8:0] \u_scheduler.distance_mask ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire [7:0] \u_scheduler.lane_valid ;
  wire [8:0] \u_scheduler.low_mask ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.rst_n ;
  wire [3:0] \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire [3:0] \u_scheduler.span_q ;
  wire [3:0] \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire [3:0] \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _338_ (
    .A(ecc_uncorrectable),
    .ZN(_055_)
  );
  INV_X1 _339_ (
    .A(datapath_fault),
    .ZN(_056_)
  );
  INV_X1 _340_ (
    .A(error_scheduler),
    .ZN(_065_)
  );
  AOI21_X1 _341_ (
    .A(_135_),
    .B1(_137_),
    .B2(_148_),
    .ZN(_149_)
  );
  AND3_X1 _342_ (
    .A1(_135_),
    .A2(_137_),
    .A3(_148_),
    .ZN(_150_)
  );
  OAI221_X1 _343_ (
    .A(_147_),
    .B1(_149_),
    .B2(_150_),
    .C1(_143_),
    .C2(_140_),
    .ZN(_151_)
  );
  AOI21_X1 _344_ (
    .A(_072_),
    .B1(_110_),
    .B2(_111_),
    .ZN(_152_)
  );
  AOI221_X1 _345_ (
    .A(_152_),
    .B1(_151_),
    .B2(stage_start),
    .C1(batch_retired),
    .C2(_115_),
    .ZN(_153_)
  );
  NAND2_X1 _346_ (
    .A1(rst_n),
    .A2(\u_controller.state [7]),
    .ZN(_154_)
  );
  INV_X1 _347_ (
    .A(_154_),
    .ZN(zeroize_req)
  );
  NAND2_X1 _348_ (
    .A1(_107_),
    .A2(_154_),
    .ZN(_155_)
  );
  NAND3_X1 _349_ (
    .A1(_107_),
    .A2(_116_),
    .A3(_154_),
    .ZN(_156_)
  );
  OAI22_X1 _350_ (
    .A1(_116_),
    .A2(_117_),
    .B1(_153_),
    .B2(_156_),
    .ZN(_157_)
  );
  INV_X1 _351_ (
    .A(error_controller),
    .ZN(_066_)
  );
  NAND2_X1 _352_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_158_)
  );
  INV_X1 _353_ (
    .A(_158_),
    .ZN(_159_)
  );
  OAI221_X1 _354_ (
    .A(_159_),
    .B1(_156_),
    .B2(_153_),
    .C1(_116_),
    .C2(_117_),
    .ZN(_160_)
  );
  NOR2_X1 _355_ (
    .A1(_114_),
    .A2(_160_),
    .ZN(scheduler_quiescent)
  );
  NOR2_X1 _356_ (
    .A1(cfg_last_stage[1]),
    .A2(cfg_last_stage[0]),
    .ZN(_161_)
  );
  NOR3_X1 _357_ (
    .A1(cfg_last_stage[1]),
    .A2(cfg_last_stage[2]),
    .A3(cfg_last_stage[0]),
    .ZN(_162_)
  );
  NOR2_X1 _358_ (
    .A1(cfg_span_descending),
    .A2(_162_),
    .ZN(_163_)
  );
  XNOR2_X1 _359_ (
    .A(cfg_last_stage[3]),
    .B(_163_),
    .ZN(_164_)
  );
  NAND2_X1 _360_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_164_),
    .ZN(_165_)
  );
  XNOR2_X1 _361_ (
    .A(_070_),
    .B(_164_),
    .ZN(_166_)
  );
  INV_X1 _362_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .ZN(_067_)
  );
  OR3_X1 _363_ (
    .A1(cfg_span_descending),
    .A2(cfg_last_stage[2]),
    .A3(_161_),
    .ZN(_167_)
  );
  OAI21_X1 _364_ (
    .A(cfg_last_stage[2]),
    .B1(_161_),
    .B2(cfg_span_descending),
    .ZN(_168_)
  );
  AND2_X1 _365_ (
    .A1(_167_),
    .A2(_168_),
    .ZN(_169_)
  );
  OR2_X1 _366_ (
    .A1(cfg_first_span_log2[2]),
    .A2(_169_),
    .ZN(_170_)
  );
  AND2_X1 _367_ (
    .A1(cfg_last_stage[1]),
    .A2(cfg_last_stage[0]),
    .ZN(_171_)
  );
  OR3_X1 _368_ (
    .A1(cfg_span_descending),
    .A2(_161_),
    .A3(_171_),
    .ZN(_172_)
  );
  NAND2_X1 _369_ (
    .A1(cfg_span_descending),
    .A2(cfg_last_stage[1]),
    .ZN(_173_)
  );
  NAND2_X1 _370_ (
    .A1(_172_),
    .A2(_173_),
    .ZN(_174_)
  );
  AOI21_X1 _371_ (
    .A(cfg_first_span_log2[1]),
    .B1(_172_),
    .B2(_173_),
    .ZN(_175_)
  );
  NAND3_X1 _372_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_172_),
    .A3(_173_),
    .ZN(_176_)
  );
  INV_X1 _373_ (
    .A(descending_q),
    .ZN(_068_)
  );
  NOR2_X1 _374_ (
    .A1(cfg_first_span_log2[0]),
    .A2(_091_),
    .ZN(_177_)
  );
  XOR2_X1 _375_ (
    .A(cfg_first_span_log2[1]),
    .B(_174_),
    .Z(_178_)
  );
  NAND3_X1 _376_ (
    .A1(cfg_first_span_log2[2]),
    .A2(_167_),
    .A3(_168_),
    .ZN(_179_)
  );
  OAI211_X1 _377_ (
    .A(_176_),
    .B(_179_),
    .C1(_177_),
    .C2(_175_),
    .ZN(_180_)
  );
  NAND2_X1 _378_ (
    .A1(_170_),
    .A2(_180_),
    .ZN(_181_)
  );
  NAND3_X1 _379_ (
    .A1(_166_),
    .A2(_170_),
    .A3(_180_),
    .ZN(_182_)
  );
  NAND2_X1 _380_ (
    .A1(_165_),
    .A2(_182_),
    .ZN(_183_)
  );
  AOI21_X1 _381_ (
    .A(cfg_span_descending),
    .B1(_084_),
    .B2(_162_),
    .ZN(_184_)
  );
  NOR2_X1 _382_ (
    .A1(_084_),
    .A2(_162_),
    .ZN(_185_)
  );
  NOR3_X1 _383_ (
    .A1(cfg_first_span_log2[0]),
    .A2(cfg_first_span_log2[1]),
    .A3(cfg_first_span_log2[2]),
    .ZN(_186_)
  );
  INV_X1 _384_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_069_)
  );
  NOR2_X1 _385_ (
    .A1(_070_),
    .A2(_186_),
    .ZN(_187_)
  );
  AND2_X1 _386_ (
    .A1(_183_),
    .A2(_184_),
    .ZN(_188_)
  );
  NAND2_X1 _387_ (
    .A1(cfg_first_span_log2[0]),
    .A2(_091_),
    .ZN(_189_)
  );
  NAND3_X1 _388_ (
    .A1(_170_),
    .A2(_179_),
    .A3(_189_),
    .ZN(_190_)
  );
  NOR3_X1 _389_ (
    .A1(_177_),
    .A2(_178_),
    .A3(_190_),
    .ZN(_191_)
  );
  XOR2_X1 _390_ (
    .A(_166_),
    .B(_181_),
    .Z(_192_)
  );
  OAI22_X1 _391_ (
    .A1(_183_),
    .A2(_184_),
    .B1(_191_),
    .B2(_192_),
    .ZN(_193_)
  );
  NOR4_X1 _392_ (
    .A1(_185_),
    .A2(_187_),
    .A3(_188_),
    .A4(_193_),
    .ZN(_194_)
  );
  NAND2_X1 _393_ (
    .A1(enable),
    .A2(\u_controller.state [0]),
    .ZN(_195_)
  );
  INV_X1 _394_ (
    .A(_195_),
    .ZN(_196_)
  );
  INV_X1 _395_ (
    .A(cfg_first_span_log2[3]),
    .ZN(_070_)
  );
  NOR3_X1 _396_ (
    .A1(backend_flushed),
    .A2(_108_),
    .A3(_195_),
    .ZN(_197_)
  );
  AND3_X1 _397_ (
    .A1(scheduler_quiescent),
    .A2(_194_),
    .A3(_197_),
    .ZN(ready)
  );
  AND2_X1 _398_ (
    .A1(start),
    .A2(ready),
    .ZN(_018_)
  );
  NAND4_X1 _399_ (
    .A1(_072_),
    .A2(_107_),
    .A3(_194_),
    .A4(_196_),
    .ZN(_198_)
  );
  NOR4_X1 _400_ (
    .A1(_059_),
    .A2(_114_),
    .A3(_160_),
    .A4(_198_),
    .ZN(_199_)
  );
  NAND3_X1 _401_ (
    .A1(rst_n),
    .A2(start),
    .A3(enable),
    .ZN(_200_)
  );
  OR4_X1 _402_ (
    .A1(_011_),
    .A2(_108_),
    .A3(_194_),
    .A4(_200_),
    .ZN(_201_)
  );
  OAI21_X1 _403_ (
    .A(_201_),
    .B1(_199_),
    .B2(_062_),
    .ZN(_054_)
  );
  OAI21_X1 _404_ (
    .A(_055_),
    .B1(_063_),
    .B2(_199_),
    .ZN(_053_)
  );
  OAI21_X1 _405_ (
    .A(_056_),
    .B1(_064_),
    .B2(_199_),
    .ZN(_052_)
  );
  INV_X1 _406_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_071_)
  );
  OAI21_X1 _407_ (
    .A(_057_),
    .B1(_065_),
    .B2(_199_),
    .ZN(_051_)
  );
  OAI22_X1 _408_ (
    .A1(\u_controller.state [3]),
    .A2(_103_),
    .B1(_199_),
    .B2(_066_),
    .ZN(_050_)
  );
  NOR2_X1 _409_ (
    .A1(zeroize_req),
    .A2(_199_),
    .ZN(_202_)
  );
  AOI22_X1 _410_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_199_),
    .B1(_202_),
    .B2(first_span_q[3]),
    .ZN(_203_)
  );
  INV_X1 _411_ (
    .A(_203_),
    .ZN(_049_)
  );
  NOR2_X1 _412_ (
    .A1(_060_),
    .A2(_105_),
    .ZN(_204_)
  );
  NAND2_X1 _413_ (
    .A1(scheduler_quiescent),
    .A2(_204_),
    .ZN(_205_)
  );
  NAND3_X1 _414_ (
    .A1(_058_),
    .A2(_077_),
    .A3(_102_),
    .ZN(_206_)
  );
  OAI21_X1 _415_ (
    .A(_106_),
    .B1(_206_),
    .B2(\u_controller.state [5]),
    .ZN(_207_)
  );
  INV_X1 _416_ (
    .A(_207_),
    .ZN(_208_)
  );
  INV_X1 _417_ (
    .A(backend_flushed),
    .ZN(_072_)
  );
  NOR2_X1 _418_ (
    .A1(zeroize),
    .A2(_208_),
    .ZN(_209_)
  );
  NAND2_X1 _419_ (
    .A1(\u_controller.state [7]),
    .A2(_209_),
    .ZN(_210_)
  );
  AOI21_X1 _420_ (
    .A(_210_),
    .B1(_204_),
    .B2(scheduler_quiescent),
    .ZN(_211_)
  );
  OR3_X1 _421_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .A3(_211_),
    .ZN(_020_)
  );
  NAND2_X1 _422_ (
    .A1(\u_controller.state [4]),
    .A2(_107_),
    .ZN(_212_)
  );
  AND3_X1 _423_ (
    .A1(rst_n),
    .A2(\u_controller.state [4]),
    .A3(_107_),
    .ZN(load_start)
  );
  AOI22_X1 _424_ (
    .A1(cfg_span_descending),
    .A2(_199_),
    .B1(_202_),
    .B2(descending_q),
    .ZN(_213_)
  );
  INV_X1 _425_ (
    .A(_213_),
    .ZN(_048_)
  );
  NOR2_X1 _426_ (
    .A1(\u_controller.state [0]),
    .A2(_206_),
    .ZN(_214_)
  );
  OR2_X1 _427_ (
    .A1(_199_),
    .A2(_214_),
    .ZN(_215_)
  );
  INV_X1 _428_ (
    .A(_312_),
    .ZN(_073_)
  );
  NOR3_X1 _429_ (
    .A1(_113_),
    .A2(_155_),
    .A3(_160_),
    .ZN(stage_done)
  );
  AND2_X1 _430_ (
    .A1(\u_controller.state [6]),
    .A2(stage_done),
    .ZN(_013_)
  );
  NOR2_X1 _431_ (
    .A1(zeroize),
    .A2(_207_),
    .ZN(_014_)
  );
  NAND2_X1 _432_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(_310_[3]),
    .ZN(_216_)
  );
  XOR2_X1 _433_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B(_310_[3]),
    .Z(_217_)
  );
  XOR2_X1 _434_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .B(_310_[2]),
    .Z(_218_)
  );
  NAND2_X1 _435_ (
    .A1(_217_),
    .A2(_218_),
    .ZN(_219_)
  );
  OAI22_X1 _436_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_310_[0]),
    .B1(\u_controller.u_stage_counter.stage_count [1]),
    .B2(_310_[1]),
    .ZN(_220_)
  );
  NAND2_X1 _437_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_310_[1]),
    .ZN(_221_)
  );
  AOI21_X1 _438_ (
    .A(_219_),
    .B1(_220_),
    .B2(_221_),
    .ZN(_222_)
  );
  INV_X1 _439_ (
    .A(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_074_)
  );
  NAND3_X1 _440_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_310_[2]),
    .A3(_217_),
    .ZN(_223_)
  );
  NOR3_X1 _441_ (
    .A1(zeroize),
    .A2(_077_),
    .A3(\u_controller.state [3]),
    .ZN(_224_)
  );
  NAND3_X1 _442_ (
    .A1(_216_),
    .A2(_223_),
    .A3(_224_),
    .ZN(_225_)
  );
  NAND2_X1 _443_ (
    .A1(\u_controller.state [6]),
    .A2(_107_),
    .ZN(_226_)
  );
  OAI21_X1 _444_ (
    .A(_109_),
    .B1(stage_done),
    .B2(_226_),
    .ZN(_019_)
  );
  OR4_X1 _445_ (
    .A1(_199_),
    .A2(_014_),
    .A3(_222_),
    .A4(_225_),
    .ZN(_227_)
  );
  NOR4_X1 _446_ (
    .A1(_211_),
    .A2(_013_),
    .A3(_019_),
    .A4(_227_),
    .ZN(_228_)
  );
  AND3_X1 _447_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(\u_controller.u_stage_counter.stage_count [1]),
    .A3(_228_),
    .ZN(_229_)
  );
  OAI21_X1 _448_ (
    .A(_221_),
    .B1(_075_),
    .B2(_074_),
    .ZN(_230_)
  );
  NOR3_X1 _449_ (
    .A1(_219_),
    .A2(_220_),
    .A3(_230_),
    .ZN(_231_)
  );
  INV_X1 _450_ (
    .A(\u_scheduler.fault_q ),
    .ZN(_057_)
  );
  INV_X1 _451_ (
    .A(_310_[0]),
    .ZN(_075_)
  );
  NAND2_X1 _452_ (
    .A1(\u_controller.state [1]),
    .A2(_107_),
    .ZN(_232_)
  );
  AOI21_X1 _453_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B1(\u_controller.u_stage_counter.stage_count [2]),
    .B2(_229_),
    .ZN(_233_)
  );
  NOR2_X1 _454_ (
    .A1(_215_),
    .A2(_233_),
    .ZN(_047_)
  );
  MUX2_X1 _455_ (
    .A(\u_controller.u_stage_counter.last_stage_q [3]),
    .B(cfg_last_stage[3]),
    .S(_199_),
    .Z(_234_)
  );
  INV_X1 _456_ (
    .A(_234_),
    .ZN(_235_)
  );
  NOR2_X1 _457_ (
    .A1(_214_),
    .A2(_235_),
    .ZN(_046_)
  );
  AND2_X1 _458_ (
    .A1(rst_n),
    .A2(_206_),
    .ZN(active)
  );
  AND3_X1 _459_ (
    .A1(rst_n),
    .A2(\u_controller.state [5]),
    .A3(_107_),
    .ZN(done)
  );
  AOI21_X1 _460_ (
    .A(_057_),
    .B1(backend_flushed),
    .B2(_117_),
    .ZN(_236_)
  );
  NOR2_X1 _461_ (
    .A1(_157_),
    .A2(_236_),
    .ZN(_237_)
  );
  INV_X1 _462_ (
    .A(batch_ready),
    .ZN(_076_)
  );
  INV_X1 _463_ (
    .A(_237_),
    .ZN(_045_)
  );
  NAND2_X1 _464_ (
    .A1(batch_retired),
    .A2(_000_),
    .ZN(_238_)
  );
  NAND4_X1 _465_ (
    .A1(\u_scheduler.state [2]),
    .A2(_072_),
    .A3(_117_),
    .A4(_238_),
    .ZN(_239_)
  );
  AOI211_X1 _466_ (
    .A(batch_retired),
    .B(_115_),
    .C1(_155_),
    .C2(backend_flushed),
    .ZN(_240_)
  );
  OAI21_X1 _467_ (
    .A(_240_),
    .B1(_155_),
    .B2(\u_scheduler.state [2]),
    .ZN(_241_)
  );
  NAND2_X1 _468_ (
    .A1(_239_),
    .A2(_241_),
    .ZN(_242_)
  );
  OR2_X1 _469_ (
    .A1(_157_),
    .A2(_242_),
    .ZN(\u_scheduler.next_state [2])
  );
  NOR4_X1 _470_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(_008_),
    .A4(_155_),
    .ZN(_243_)
  );
  NAND2_X1 _471_ (
    .A1(butterfly_enable),
    .A2(_243_),
    .ZN(_244_)
  );
  NOR2_X1 _472_ (
    .A1(_160_),
    .A2(_244_),
    .ZN(batch_valid)
  );
  INV_X1 _473_ (
    .A(\u_controller.state [1]),
    .ZN(_077_)
  );
  OR2_X1 _474_ (
    .A1(_069_),
    .A2(_199_),
    .ZN(_245_)
  );
  NAND2_X1 _475_ (
    .A1(intt_mode),
    .A2(_199_),
    .ZN(_246_)
  );
  AOI21_X1 _476_ (
    .A(_214_),
    .B1(_245_),
    .B2(_246_),
    .ZN(_044_)
  );
  OR3_X1 _477_ (
    .A1(_076_),
    .A2(_160_),
    .A3(_244_),
    .ZN(_247_)
  );
  AND2_X1 _478_ (
    .A1(\u_scheduler.state [0]),
    .A2(_243_),
    .ZN(_248_)
  );
  NAND4_X1 _479_ (
    .A1(_061_),
    .A2(_000_),
    .A3(stage_start),
    .A4(_111_),
    .ZN(_249_)
  );
  INV_X1 _480_ (
    .A(_249_),
    .ZN(_250_)
  );
  NOR2_X1 _481_ (
    .A1(_115_),
    .A2(_155_),
    .ZN(_251_)
  );
  AOI221_X1 _482_ (
    .A(_250_),
    .B1(_251_),
    .B2(batch_retired),
    .C1(_247_),
    .C2(_248_),
    .ZN(_252_)
  );
  NOR2_X1 _483_ (
    .A1(_157_),
    .A2(_252_),
    .ZN(\u_scheduler.next_state [0])
  );
  INV_X1 _484_ (
    .A(\u_scheduler.batch_index_q [4]),
    .ZN(_078_)
  );
  NOR3_X1 _485_ (
    .A1(batch_retired),
    .A2(_115_),
    .A3(_155_),
    .ZN(_253_)
  );
  NAND2_X1 _486_ (
    .A1(\u_scheduler.state [1]),
    .A2(_253_),
    .ZN(_254_)
  );
  NOR4_X1 _487_ (
    .A1(_012_),
    .A2(_002_),
    .A3(_003_),
    .A4(_004_),
    .ZN(_255_)
  );
  NAND4_X1 _488_ (
    .A1(batch_retired),
    .A2(_085_),
    .A3(_251_),
    .A4(_255_),
    .ZN(_256_)
  );
  NAND3_X1 _489_ (
    .A1(_247_),
    .A2(_254_),
    .A3(_256_),
    .ZN(_257_)
  );
  INV_X1 _490_ (
    .A(_257_),
    .ZN(_258_)
  );
  NOR4_X1 _491_ (
    .A1(_115_),
    .A2(_157_),
    .A3(_252_),
    .A4(_257_),
    .ZN(_259_)
  );
  AND3_X1 _492_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(\u_scheduler.batch_index_q [1]),
    .A3(_259_),
    .ZN(_260_)
  );
  AND4_X1 _493_ (
    .A1(\u_scheduler.batch_index_q [2]),
    .A2(\u_scheduler.batch_index_q [0]),
    .A3(\u_scheduler.batch_index_q [1]),
    .A4(_259_),
    .ZN(_261_)
  );
  AND2_X1 _494_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_261_),
    .ZN(_262_)
  );
  INV_X1 _495_ (
    .A(\u_scheduler.stage_q [3]),
    .ZN(_079_)
  );
  AND3_X1 _496_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(\u_scheduler.batch_index_q [3]),
    .A3(_261_),
    .ZN(_263_)
  );
  OR2_X1 _497_ (
    .A1(_157_),
    .A2(_249_),
    .ZN(_264_)
  );
  NAND2_X1 _498_ (
    .A1(_252_),
    .A2(_258_),
    .ZN(_265_)
  );
  OAI21_X1 _499_ (
    .A(_264_),
    .B1(_265_),
    .B2(\u_scheduler.next_state [2]),
    .ZN(_266_)
  );
  AOI21_X1 _500_ (
    .A(\u_scheduler.batch_index_q [4]),
    .B1(\u_scheduler.batch_index_q [3]),
    .B2(_261_),
    .ZN(_267_)
  );
  NOR3_X1 _501_ (
    .A1(_263_),
    .A2(_266_),
    .A3(_267_),
    .ZN(_043_)
  );
  OAI22_X1 _502_ (
    .A1(_067_),
    .A2(_264_),
    .B1(_266_),
    .B2(_079_),
    .ZN(_042_)
  );
  OAI22_X1 _503_ (
    .A1(_140_),
    .A2(_264_),
    .B1(_266_),
    .B2(_080_),
    .ZN(_041_)
  );
  OAI22_X1 _504_ (
    .A1(_069_),
    .A2(_264_),
    .B1(_266_),
    .B2(_081_),
    .ZN(_040_)
  );
  NOR2_X1 _505_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(_094_),
    .ZN(_268_)
  );
  INV_X1 _506_ (
    .A(\u_scheduler.span_q [3]),
    .ZN(_080_)
  );
  NAND2_X1 _507_ (
    .A1(_080_),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_269_)
  );
  NAND3_X1 _508_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .A3(_268_),
    .ZN(_270_)
  );
  NAND2_X1 _509_ (
    .A1(\u_scheduler.span_q [1]),
    .A2(_010_),
    .ZN(_271_)
  );
  NOR2_X1 _510_ (
    .A1(_269_),
    .A2(_271_),
    .ZN(_272_)
  );
  NAND2_X1 _511_ (
    .A1(_099_),
    .A2(_268_),
    .ZN(_273_)
  );
  NAND2_X1 _512_ (
    .A1(_093_),
    .A2(_010_),
    .ZN(_274_)
  );
  NAND3_X1 _513_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .A3(_098_),
    .ZN(_275_)
  );
  NAND3_X1 _514_ (
    .A1(_093_),
    .A2(_010_),
    .A3(_098_),
    .ZN(coeff_addr_a[9])
  );
  INV_X1 _515_ (
    .A(coeff_addr_a[9]),
    .ZN(coeff_addr_a[10])
  );
  NAND2_X1 _516_ (
    .A1(_100_),
    .A2(coeff_addr_a[9]),
    .ZN(coeff_addr_b[10])
  );
  INV_X1 _517_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_081_)
  );
  INV_X1 _518_ (
    .A(coeff_addr_b[10]),
    .ZN(coeff_addr_b[38])
  );
  NOR3_X1 _519_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(\u_scheduler.span_q [2]),
    .A3(_271_),
    .ZN(coeff_addr_b[2])
  );
  NOR2_X1 _520_ (
    .A1(coeff_addr_b[10]),
    .A2(coeff_addr_b[2]),
    .ZN(coeff_addr_a[38])
  );
  OAI21_X1 _521_ (
    .A(_098_),
    .B1(_010_),
    .B2(\u_scheduler.span_q [0]),
    .ZN(_276_)
  );
  OAI21_X1 _522_ (
    .A(_276_),
    .B1(_274_),
    .B2(_269_),
    .ZN(_277_)
  );
  INV_X1 _523_ (
    .A(_277_),
    .ZN(_278_)
  );
  OAI211_X1 _524_ (
    .A(_273_),
    .B(_278_),
    .C1(_269_),
    .C2(_271_),
    .ZN(_279_)
  );
  XNOR2_X1 _525_ (
    .A(_270_),
    .B(_279_),
    .ZN(_280_)
  );
  AND2_X1 _526_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(_280_),
    .ZN(coeff_addr_a[8])
  );
  MUX2_X1 _527_ (
    .A(_010_),
    .B(coeff_addr_a[38]),
    .S(_275_),
    .Z(_281_)
  );
  INV_X1 _528_ (
    .A(first_span_q[1]),
    .ZN(_082_)
  );
  NAND2_X1 _529_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_281_),
    .ZN(_282_)
  );
  INV_X1 _530_ (
    .A(_282_),
    .ZN(coeff_addr_a[3])
  );
  NAND2_X1 _531_ (
    .A1(coeff_addr_a[38]),
    .A2(_282_),
    .ZN(coeff_addr_a[39])
  );
  NAND2_X1 _532_ (
    .A1(\u_controller.state [0]),
    .A2(_209_),
    .ZN(_283_)
  );
  NOR2_X1 _533_ (
    .A1(_199_),
    .A2(_283_),
    .ZN(_284_)
  );
  AOI21_X1 _534_ (
    .A(_284_),
    .B1(_107_),
    .B2(\u_controller.state [5]),
    .ZN(_285_)
  );
  OAI21_X1 _535_ (
    .A(_285_),
    .B1(_210_),
    .B2(_205_),
    .ZN(_016_)
  );
  OAI21_X1 _536_ (
    .A(_212_),
    .B1(_231_),
    .B2(_232_),
    .ZN(_017_)
  );
  AND3_X1 _537_ (
    .A1(\u_controller.state [1]),
    .A2(_107_),
    .A3(_231_),
    .ZN(_015_)
  );
  NAND2_X1 _538_ (
    .A1(\u_scheduler.batch_index_q [1]),
    .A2(_278_),
    .ZN(_286_)
  );
  INV_X1 _539_ (
    .A(first_span_q[2]),
    .ZN(_083_)
  );
  OAI21_X1 _540_ (
    .A(_286_),
    .B1(_281_),
    .B2(_090_),
    .ZN(coeff_addr_a[4])
  );
  INV_X1 _541_ (
    .A(coeff_addr_a[4]),
    .ZN(_287_)
  );
  OAI21_X1 _542_ (
    .A(_287_),
    .B1(_274_),
    .B2(_269_),
    .ZN(coeff_addr_b[4])
  );
  NOR3_X1 _543_ (
    .A1(_080_),
    .A2(\u_scheduler.span_q [2]),
    .A3(_274_),
    .ZN(_288_)
  );
  NOR2_X1 _544_ (
    .A1(coeff_addr_a[8]),
    .A2(_288_),
    .ZN(_289_)
  );
  INV_X1 _545_ (
    .A(_289_),
    .ZN(coeff_addr_b[8])
  );
  NAND2_X1 _546_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(coeff_addr_a[10]),
    .ZN(coeff_addr_b[56])
  );
  NAND2_X1 _547_ (
    .A1(coeff_addr_b[10]),
    .A2(coeff_addr_b[56]),
    .ZN(coeff_addr_a[19])
  );
  INV_X1 _548_ (
    .A(coeff_addr_a[19]),
    .ZN(coeff_addr_a[20])
  );
  NAND2_X1 _549_ (
    .A1(_092_),
    .A2(coeff_addr_a[10]),
    .ZN(coeff_addr_b[19])
  );
  INV_X1 _550_ (
    .A(cfg_last_stage[3]),
    .ZN(_084_)
  );
  NOR2_X1 _551_ (
    .A1(_157_),
    .A2(_258_),
    .ZN(\u_scheduler.next_state [1])
  );
  XOR2_X1 _552_ (
    .A(_273_),
    .B(_277_),
    .Z(_290_)
  );
  AOI22_X1 _553_ (
    .A1(\u_scheduler.batch_index_q [1]),
    .A2(_277_),
    .B1(_290_),
    .B2(\u_scheduler.batch_index_q [2]),
    .ZN(_291_)
  );
  INV_X1 _554_ (
    .A(_291_),
    .ZN(coeff_addr_a[5])
  );
  OAI22_X1 _555_ (
    .A1(_087_),
    .A2(_279_),
    .B1(_290_),
    .B2(_088_),
    .ZN(coeff_addr_a[6])
  );
  NAND2_X1 _556_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_279_),
    .ZN(_292_)
  );
  OAI21_X1 _557_ (
    .A(_292_),
    .B1(_280_),
    .B2(_078_),
    .ZN(coeff_addr_a[7])
  );
  AOI21_X1 _558_ (
    .A(coeff_addr_b[2]),
    .B1(coeff_addr_a[10]),
    .B2(\u_scheduler.span_q [0]),
    .ZN(coeff_addr_a[56])
  );
  NAND2_X1 _559_ (
    .A1(_090_),
    .A2(_276_),
    .ZN(coeff_addr_b[39])
  );
  OAI22_X1 _560_ (
    .A1(_141_),
    .A2(_264_),
    .B1(_266_),
    .B2(_092_),
    .ZN(_039_)
  );
  INV_X1 _561_ (
    .A(\u_controller.state [6]),
    .ZN(_058_)
  );
  INV_X1 _562_ (
    .A(_313_[0]),
    .ZN(_085_)
  );
  XNOR2_X1 _563_ (
    .A(_127_),
    .B(_128_),
    .ZN(_293_)
  );
  OAI22_X1 _564_ (
    .A1(_093_),
    .A2(_266_),
    .B1(_293_),
    .B2(_264_),
    .ZN(_038_)
  );
  OAI22_X1 _565_ (
    .A1(_142_),
    .A2(_264_),
    .B1(_266_),
    .B2(_094_),
    .ZN(_037_)
  );
  OAI22_X1 _566_ (
    .A1(_074_),
    .A2(_264_),
    .B1(_266_),
    .B2(_095_),
    .ZN(_036_)
  );
  OAI22_X1 _567_ (
    .A1(_086_),
    .A2(_264_),
    .B1(_266_),
    .B2(_096_),
    .ZN(_035_)
  );
  OAI22_X1 _568_ (
    .A1(_071_),
    .A2(_264_),
    .B1(_266_),
    .B2(_097_),
    .ZN(_034_)
  );
  NOR2_X1 _569_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_259_),
    .ZN(_294_)
  );
  AOI211_X1 _570_ (
    .A(_266_),
    .B(_294_),
    .C1(_085_),
    .C2(_259_),
    .ZN(_033_)
  );
  AOI21_X1 _571_ (
    .A(\u_scheduler.batch_index_q [1]),
    .B1(_259_),
    .B2(\u_scheduler.batch_index_q [0]),
    .ZN(_295_)
  );
  NOR3_X1 _572_ (
    .A1(_260_),
    .A2(_266_),
    .A3(_295_),
    .ZN(_032_)
  );
  INV_X1 _573_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_086_)
  );
  NOR2_X1 _574_ (
    .A1(\u_scheduler.batch_index_q [2]),
    .A2(_260_),
    .ZN(_296_)
  );
  NOR3_X1 _575_ (
    .A1(_261_),
    .A2(_266_),
    .A3(_296_),
    .ZN(_031_)
  );
  NOR2_X1 _576_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_261_),
    .ZN(_297_)
  );
  NOR3_X1 _577_ (
    .A1(_262_),
    .A2(_266_),
    .A3(_297_),
    .ZN(_030_)
  );
  MUX2_X1 _578_ (
    .A(\u_controller.u_stage_counter.last_stage_q [0]),
    .B(cfg_last_stage[0]),
    .S(_199_),
    .Z(_298_)
  );
  INV_X1 _579_ (
    .A(_298_),
    .ZN(_299_)
  );
  NOR2_X1 _580_ (
    .A1(_214_),
    .A2(_299_),
    .ZN(_029_)
  );
  MUX2_X1 _581_ (
    .A(\u_controller.u_stage_counter.last_stage_q [1]),
    .B(cfg_last_stage[1]),
    .S(_199_),
    .Z(_300_)
  );
  INV_X1 _582_ (
    .A(_300_),
    .ZN(_301_)
  );
  NOR2_X1 _583_ (
    .A1(_214_),
    .A2(_301_),
    .ZN(_028_)
  );
  INV_X1 _584_ (
    .A(\u_scheduler.batch_index_q [3]),
    .ZN(_087_)
  );
  MUX2_X1 _585_ (
    .A(\u_controller.u_stage_counter.last_stage_q [2]),
    .B(cfg_last_stage[2]),
    .S(_199_),
    .Z(_302_)
  );
  INV_X1 _586_ (
    .A(_302_),
    .ZN(_303_)
  );
  NOR2_X1 _587_ (
    .A1(_214_),
    .A2(_303_),
    .ZN(_027_)
  );
  NOR2_X1 _588_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_228_),
    .ZN(_304_)
  );
  AOI211_X1 _589_ (
    .A(_215_),
    .B(_304_),
    .C1(_228_),
    .C2(_089_),
    .ZN(_026_)
  );
  AOI21_X1 _590_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .B1(_228_),
    .B2(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_305_)
  );
  NOR3_X1 _591_ (
    .A1(_215_),
    .A2(_229_),
    .A3(_305_),
    .ZN(_025_)
  );
  XNOR2_X1 _592_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .B(_229_),
    .ZN(_306_)
  );
  NOR2_X1 _593_ (
    .A1(_215_),
    .A2(_306_),
    .ZN(_024_)
  );
  AOI22_X1 _594_ (
    .A1(cfg_first_span_log2[0]),
    .A2(_199_),
    .B1(_202_),
    .B2(first_span_q[0]),
    .ZN(_307_)
  );
  INV_X1 _595_ (
    .A(\u_scheduler.batch_index_q [2]),
    .ZN(_088_)
  );
  INV_X1 _596_ (
    .A(_307_),
    .ZN(_023_)
  );
  AOI22_X1 _597_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_199_),
    .B1(_202_),
    .B2(first_span_q[1]),
    .ZN(_308_)
  );
  INV_X1 _598_ (
    .A(_308_),
    .ZN(_022_)
  );
  AOI22_X1 _599_ (
    .A1(cfg_first_span_log2[2]),
    .A2(_199_),
    .B1(_202_),
    .B2(first_span_q[2]),
    .ZN(_309_)
  );
  INV_X1 _600_ (
    .A(_309_),
    .ZN(_021_)
  );
  OR2_X1 _601_ (
    .A1(_272_),
    .A2(coeff_addr_a[6]),
    .ZN(coeff_addr_b[6])
  );
  OR2_X1 _602_ (
    .A1(coeff_addr_b[2]),
    .A2(coeff_addr_a[20]),
    .ZN(coeff_addr_b[20])
  );
  NAND2_X1 _603_ (
    .A1(_275_),
    .A2(_282_),
    .ZN(coeff_addr_b[3])
  );
  OAI211_X1 _604_ (
    .A(_270_),
    .B(_292_),
    .C1(_279_),
    .C2(_078_),
    .ZN(coeff_addr_b[7])
  );
  NAND2_X1 _605_ (
    .A1(_273_),
    .A2(_291_),
    .ZN(coeff_addr_b[5])
  );
  INV_X1 _606_ (
    .A(_314_[0]),
    .ZN(_089_)
  );
  INV_X1 _607_ (
    .A(\u_scheduler.batch_index_q [0]),
    .ZN(_090_)
  );
  INV_X1 _608_ (
    .A(cfg_last_stage[0]),
    .ZN(_091_)
  );
  INV_X1 _609_ (
    .A(\u_scheduler.span_q [0]),
    .ZN(_092_)
  );
  INV_X1 _610_ (
    .A(\u_scheduler.span_q [1]),
    .ZN(_093_)
  );
  INV_X1 _611_ (
    .A(\u_scheduler.span_q [2]),
    .ZN(_094_)
  );
  INV_X1 _612_ (
    .A(start),
    .ZN(_059_)
  );
  INV_X1 _613_ (
    .A(\u_scheduler.stage_q [0]),
    .ZN(_095_)
  );
  INV_X1 _614_ (
    .A(\u_scheduler.stage_q [1]),
    .ZN(_096_)
  );
  INV_X1 _615_ (
    .A(\u_scheduler.stage_q [2]),
    .ZN(_097_)
  );
  NOR2_X1 _616_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_098_)
  );
  NOR2_X1 _617_ (
    .A1(_092_),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_099_)
  );
  NAND2_X1 _618_ (
    .A1(_098_),
    .A2(_099_),
    .ZN(_100_)
  );
  INV_X1 _619_ (
    .A(_100_),
    .ZN(coeff_addr_b[1])
  );
  OR2_X1 _620_ (
    .A1(_010_),
    .A2(_100_),
    .ZN(coeff_addr_a[28])
  );
  AND2_X1 _621_ (
    .A1(rst_n),
    .A2(\u_controller.state [6]),
    .ZN(butterfly_enable)
  );
  AND2_X1 _622_ (
    .A1(rst_n),
    .A2(_011_),
    .ZN(busy)
  );
  INV_X1 _623_ (
    .A(scrub_done),
    .ZN(_060_)
  );
  NOR4_X1 _624_ (
    .A1(\u_controller.state [7]),
    .A2(\u_controller.state [0]),
    .A3(\u_controller.state [1]),
    .A4(\u_controller.state [5]),
    .ZN(_101_)
  );
  NOR2_X1 _625_ (
    .A1(\u_controller.state [4]),
    .A2(\u_controller.state [2]),
    .ZN(_102_)
  );
  NAND4_X1 _626_ (
    .A1(rst_n),
    .A2(_058_),
    .A3(_101_),
    .A4(_102_),
    .ZN(_103_)
  );
  INV_X1 _627_ (
    .A(_103_),
    .ZN(transform_abort)
  );
  NOR3_X1 _628_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_104_)
  );
  OAI21_X1 _629_ (
    .A(_104_),
    .B1(_103_),
    .B2(\u_controller.state [3]),
    .ZN(_105_)
  );
  OR2_X1 _630_ (
    .A1(abort_req),
    .A2(_105_),
    .ZN(_106_)
  );
  NOR2_X1 _631_ (
    .A1(zeroize),
    .A2(_106_),
    .ZN(_107_)
  );
  INV_X1 _632_ (
    .A(_107_),
    .ZN(_108_)
  );
  NAND2_X1 _633_ (
    .A1(\u_controller.state [2]),
    .A2(_107_),
    .ZN(_109_)
  );
  INV_X1 _634_ (
    .A(\u_controller.state [7]),
    .ZN(_061_)
  );
  NAND3_X1 _635_ (
    .A1(rst_n),
    .A2(\u_controller.state [2]),
    .A3(_107_),
    .ZN(_110_)
  );
  INV_X1 _636_ (
    .A(_110_),
    .ZN(stage_start)
  );
  NOR3_X1 _637_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(\u_scheduler.state [1]),
    .ZN(_111_)
  );
  NOR3_X1 _638_ (
    .A1(\u_scheduler.state [2]),
    .A2(_008_),
    .A3(_009_),
    .ZN(_112_)
  );
  OR3_X1 _639_ (
    .A1(\u_scheduler.state [2]),
    .A2(_008_),
    .A3(_009_),
    .ZN(_113_)
  );
  NOR2_X1 _640_ (
    .A1(_111_),
    .A2(_112_),
    .ZN(_114_)
  );
  OR3_X1 _641_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_009_),
    .ZN(_115_)
  );
  AOI221_X1 _642_ (
    .A(\u_scheduler.state [2]),
    .B1(\u_scheduler.state [0]),
    .B2(_008_),
    .C1(_009_),
    .C2(\u_scheduler.state [1]),
    .ZN(_116_)
  );
  NOR3_X1 _643_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(_001_),
    .ZN(_117_)
  );
  AND3_X1 _644_ (
    .A1(_314_[0]),
    .A2(_337_[2]),
    .A3(_337_[1]),
    .ZN(_118_)
  );
  INV_X1 _645_ (
    .A(error_config),
    .ZN(_062_)
  );
  AOI21_X1 _646_ (
    .A(_337_[2]),
    .B1(_337_[1]),
    .B2(_314_[0]),
    .ZN(_119_)
  );
  OR3_X1 _647_ (
    .A1(descending_q),
    .A2(_118_),
    .A3(_119_),
    .ZN(_120_)
  );
  OAI21_X1 _648_ (
    .A(_120_),
    .B1(_071_),
    .B2(_068_),
    .ZN(_121_)
  );
  OR2_X1 _649_ (
    .A1(_083_),
    .A2(_121_),
    .ZN(_122_)
  );
  XOR2_X1 _650_ (
    .A(_314_[0]),
    .B(_337_[1]),
    .Z(_123_)
  );
  MUX2_X1 _651_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .B(_123_),
    .S(_068_),
    .Z(_124_)
  );
  NOR2_X1 _652_ (
    .A1(_082_),
    .A2(_124_),
    .ZN(_125_)
  );
  NOR2_X1 _653_ (
    .A1(first_span_q[0]),
    .A2(_314_[0]),
    .ZN(_126_)
  );
  INV_X1 _654_ (
    .A(_126_),
    .ZN(_127_)
  );
  XNOR2_X1 _655_ (
    .A(first_span_q[1]),
    .B(_124_),
    .ZN(_128_)
  );
  INV_X1 _656_ (
    .A(error_ecc),
    .ZN(_063_)
  );
  AOI21_X1 _657_ (
    .A(_125_),
    .B1(_127_),
    .B2(_128_),
    .ZN(_129_)
  );
  XNOR2_X1 _658_ (
    .A(first_span_q[2]),
    .B(_121_),
    .ZN(_130_)
  );
  XNOR2_X1 _659_ (
    .A(_083_),
    .B(_121_),
    .ZN(_131_)
  );
  OAI21_X1 _660_ (
    .A(_122_),
    .B1(_129_),
    .B2(_131_),
    .ZN(_132_)
  );
  OR2_X1 _661_ (
    .A1(_311_),
    .A2(_118_),
    .ZN(_133_)
  );
  AOI21_X1 _662_ (
    .A(descending_q),
    .B1(_311_),
    .B2(_118_),
    .ZN(_134_)
  );
  INV_X1 _663_ (
    .A(_134_),
    .ZN(_135_)
  );
  AOI22_X1 _664_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(descending_q),
    .B1(_133_),
    .B2(_134_),
    .ZN(_136_)
  );
  OR2_X1 _665_ (
    .A1(first_span_q[3]),
    .A2(_136_),
    .ZN(_137_)
  );
  NAND2_X1 _666_ (
    .A1(first_span_q[3]),
    .A2(_136_),
    .ZN(_138_)
  );
  INV_X1 _667_ (
    .A(error_datapath),
    .ZN(_064_)
  );
  NAND2_X1 _668_ (
    .A1(_137_),
    .A2(_138_),
    .ZN(_139_)
  );
  XOR2_X1 _669_ (
    .A(_132_),
    .B(_139_),
    .Z(_140_)
  );
  XOR2_X1 _670_ (
    .A(first_span_q[0]),
    .B(_314_[0]),
    .Z(_141_)
  );
  XNOR2_X1 _671_ (
    .A(_129_),
    .B(_131_),
    .ZN(_142_)
  );
  AND3_X1 _672_ (
    .A1(_128_),
    .A2(_130_),
    .A3(_141_),
    .ZN(_143_)
  );
  NAND4_X1 _673_ (
    .A1(first_span_q[3]),
    .A2(_005_),
    .A3(_006_),
    .A4(_007_),
    .ZN(_144_)
  );
  OAI21_X1 _674_ (
    .A(_111_),
    .B1(_311_),
    .B2(\u_controller.u_stage_counter.stage_count [3]),
    .ZN(_145_)
  );
  AOI21_X1 _675_ (
    .A(_145_),
    .B1(_144_),
    .B2(_073_),
    .ZN(_146_)
  );
  AND2_X1 _676_ (
    .A1(_133_),
    .A2(_146_),
    .ZN(_147_)
  );
  OAI211_X1 _677_ (
    .A(_122_),
    .B(_138_),
    .C1(_131_),
    .C2(_129_),
    .ZN(_148_)
  );
  DFFS_X1 _678_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_controller.state [0]),
    .QN(_011_),
    .SN(rst_n)
  );
  DFFR_X1 _679_ (
    .CK(clk),
    .D(_013_),
    .Q(\u_controller.state [1]),
    .QN(_336_),
    .RN(rst_n)
  );
  DFFR_X1 _680_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.state [2]),
    .QN(_335_),
    .RN(rst_n)
  );
  DFFR_X1 _681_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_controller.state [3]),
    .QN(_334_),
    .RN(rst_n)
  );
  DFFR_X1 _682_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.state [4]),
    .QN(_333_),
    .RN(rst_n)
  );
  DFFR_X1 _683_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_controller.state [5]),
    .QN(_332_),
    .RN(rst_n)
  );
  DFFR_X1 _684_ (
    .CK(clk),
    .D(_019_),
    .Q(\u_controller.state [6]),
    .QN(_331_),
    .RN(rst_n)
  );
  DFFR_X1 _685_ (
    .CK(clk),
    .D(_020_),
    .Q(\u_controller.state [7]),
    .QN(_325_),
    .RN(rst_n)
  );
  DFFR_X1 _686_ (
    .CK(clk),
    .D(_040_),
    .Q(\u_scheduler.intt_q ),
    .QN(_324_),
    .RN(rst_n)
  );
  DFFR_X1 _687_ (
    .CK(clk),
    .D(_039_),
    .Q(\u_scheduler.span_q [0]),
    .QN(_010_),
    .RN(rst_n)
  );
  DFFR_X1 _688_ (
    .CK(clk),
    .D(_038_),
    .Q(\u_scheduler.span_q [1]),
    .QN(_326_),
    .RN(rst_n)
  );
  DFFR_X1 _689_ (
    .CK(clk),
    .D(_037_),
    .Q(\u_scheduler.span_q [2]),
    .QN(_327_),
    .RN(rst_n)
  );
  DFFR_X1 _690_ (
    .CK(clk),
    .D(_041_),
    .Q(\u_scheduler.span_q [3]),
    .QN(_323_),
    .RN(rst_n)
  );
  DFFR_X1 _691_ (
    .CK(clk),
    .D(_036_),
    .Q(\u_scheduler.stage_q [0]),
    .QN(_328_),
    .RN(rst_n)
  );
  DFFR_X1 _692_ (
    .CK(clk),
    .D(_035_),
    .Q(\u_scheduler.stage_q [1]),
    .QN(_329_),
    .RN(rst_n)
  );
  DFFR_X1 _693_ (
    .CK(clk),
    .D(_034_),
    .Q(\u_scheduler.stage_q [2]),
    .QN(_330_),
    .RN(rst_n)
  );
  DFFR_X1 _694_ (
    .CK(clk),
    .D(_042_),
    .Q(\u_scheduler.stage_q [3]),
    .QN(_322_),
    .RN(rst_n)
  );
  DFFR_X1 _695_ (
    .CK(clk),
    .D(_033_),
    .Q(\u_scheduler.batch_index_q [0]),
    .QN(_313_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _696_ (
    .CK(clk),
    .D(_032_),
    .Q(\u_scheduler.batch_index_q [1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _697_ (
    .CK(clk),
    .D(_031_),
    .Q(\u_scheduler.batch_index_q [2]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _698_ (
    .CK(clk),
    .D(_030_),
    .Q(\u_scheduler.batch_index_q [3]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _699_ (
    .CK(clk),
    .D(_043_),
    .Q(\u_scheduler.batch_index_q [4]),
    .QN(_012_),
    .RN(rst_n)
  );
  DFFR_X1 _700_ (
    .CK(clk),
    .D(_044_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_321_),
    .RN(rst_n)
  );
  DFFR_X1 _701_ (
    .CK(clk),
    .D(_045_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _702_ (
    .CK(clk),
    .D(_029_),
    .Q(\u_controller.u_stage_counter.last_stage_q [0]),
    .QN(_310_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _703_ (
    .CK(clk),
    .D(_028_),
    .Q(\u_controller.u_stage_counter.last_stage_q [1]),
    .QN(_310_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _704_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_controller.u_stage_counter.last_stage_q [2]),
    .QN(_310_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _705_ (
    .CK(clk),
    .D(_046_),
    .Q(\u_controller.u_stage_counter.last_stage_q [3]),
    .QN(_310_[3]),
    .RN(rst_n)
  );
  DFFR_X1 _706_ (
    .CK(clk),
    .D(_026_),
    .Q(\u_controller.u_stage_counter.stage_count [0]),
    .QN(_314_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _707_ (
    .CK(clk),
    .D(_025_),
    .Q(\u_controller.u_stage_counter.stage_count [1]),
    .QN(_337_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _708_ (
    .CK(clk),
    .D(_024_),
    .Q(\u_controller.u_stage_counter.stage_count [2]),
    .QN(_337_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _709_ (
    .CK(clk),
    .D(_047_),
    .Q(\u_controller.u_stage_counter.stage_count [3]),
    .QN(_311_),
    .RN(rst_n)
  );
  DFFR_X1 _710_ (
    .CK(clk),
    .D(_048_),
    .Q(descending_q),
    .QN(_320_),
    .RN(rst_n)
  );
  DFFR_X1 _711_ (
    .CK(clk),
    .D(_023_),
    .Q(first_span_q[0]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _712_ (
    .CK(clk),
    .D(_022_),
    .Q(first_span_q[1]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _713_ (
    .CK(clk),
    .D(_021_),
    .Q(first_span_q[2]),
    .QN(_007_),
    .RN(rst_n)
  );
  DFFR_X1 _714_ (
    .CK(clk),
    .D(_049_),
    .Q(first_span_q[3]),
    .QN(_312_),
    .RN(rst_n)
  );
  DFFR_X1 _715_ (
    .CK(clk),
    .D(_050_),
    .Q(error_controller),
    .QN(_319_),
    .RN(rst_n)
  );
  DFFR_X1 _716_ (
    .CK(clk),
    .D(_051_),
    .Q(error_scheduler),
    .QN(_318_),
    .RN(rst_n)
  );
  DFFR_X1 _717_ (
    .CK(clk),
    .D(_052_),
    .Q(error_datapath),
    .QN(_317_),
    .RN(rst_n)
  );
  DFFR_X1 _718_ (
    .CK(clk),
    .D(_053_),
    .Q(error_ecc),
    .QN(_316_),
    .RN(rst_n)
  );
  DFFR_X1 _719_ (
    .CK(clk),
    .D(_054_),
    .Q(error_config),
    .QN(_315_),
    .RN(rst_n)
  );
  DFFR_X1 _720_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_008_),
    .RN(rst_n)
  );
  DFFR_X1 _721_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_009_),
    .RN(rst_n)
  );
  DFFR_X1 _722_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_001_),
    .RN(rst_n)
  );
  assign _313_[4:1] = \u_scheduler.batch_index_q [4:1];
  assign _314_[3:1] = \u_controller.u_stage_counter.stage_count [3:1];
  assign { _337_[4:3], _337_[0] } = { 1'h1, _311_, _314_[0] };
  assign \u_scheduler.decode_lanes.ordinal  = { 1'h0, \u_scheduler.batch_index_q , 3'h7 };
  assign \u_scheduler.distance_mask [2:0] = { coeff_addr_b[2:1], coeff_addr_a[10] };
  assign \u_scheduler.low_mask [2:0] = { coeff_addr_a[38], coeff_addr_a[19], coeff_addr_a[9] };
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = { \u_scheduler.batch_index_q , 3'h7, \u_scheduler.batch_index_q , 3'h6, \u_scheduler.batch_index_q , 3'h5, \u_scheduler.batch_index_q , 3'h4, \u_scheduler.batch_index_q , 3'h3, \u_scheduler.batch_index_q , 3'h2, \u_scheduler.batch_index_q , 3'h1, \u_scheduler.batch_index_q , 3'h0 };
  assign \u_scheduler.coeff_addr_b  = { coeff_addr_b[8:4], coeff_addr_b[39], coeff_addr_b[56], 2'h3, coeff_addr_b[8:4], coeff_addr_b[39], coeff_addr_b[56], coeff_addr_b[19], coeff_addr_a[10], coeff_addr_b[8:4], coeff_addr_b[39:38], coeff_addr_b[10], 1'h1, coeff_addr_b[8:4], coeff_addr_b[39:38], coeff_addr_b[1], coeff_addr_a[10], coeff_addr_b[8:3], coeff_addr_b[20], 2'h3, coeff_addr_b[8:3], coeff_addr_b[20:19], coeff_addr_a[10], coeff_addr_b[8:2], coeff_addr_b[10], 1'h1, coeff_addr_b[8:1], coeff_addr_a[10] };
  assign \u_scheduler.coeff_addr_a  = { coeff_addr_a[8:4], coeff_addr_a[39], coeff_addr_a[56], coeff_addr_a[28], coeff_addr_a[9:4], coeff_addr_a[39], coeff_addr_a[56], coeff_addr_a[19], 1'h0, coeff_addr_a[8:4], coeff_addr_a[39:38], coeff_addr_a[10:4], coeff_addr_a[39:38], 2'h0, coeff_addr_a[8:3], coeff_addr_a[20], coeff_addr_a[28], coeff_addr_a[9:3], coeff_addr_a[20:19], 1'h0, coeff_addr_a[8:3], 1'h0, coeff_addr_a[10:3], 3'h0 };
  assign \u_scheduler.lane_valid  = { batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid };
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.next_state [3] = 1'h0;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = { \u_scheduler.batch_index_q , 3'h7, \u_scheduler.batch_index_q , 3'h6, \u_scheduler.batch_index_q , 3'h5, \u_scheduler.batch_index_q , 3'h4, \u_scheduler.batch_index_q , 3'h3, \u_scheduler.batch_index_q , 3'h2, \u_scheduler.batch_index_q , 3'h1, \u_scheduler.batch_index_q , 3'h0 };
  assign { coeff_addr_b[71:57], coeff_addr_b[55:40], coeff_addr_b[37:21], coeff_addr_b[18:11], coeff_addr_b[9], coeff_addr_b[0] } = { coeff_addr_b[8:4], coeff_addr_b[39], coeff_addr_b[56], 2'h3, coeff_addr_b[8:4], coeff_addr_b[39], coeff_addr_b[19], coeff_addr_a[10], coeff_addr_b[8:4], coeff_addr_b[39:38], coeff_addr_b[10], 1'h1, coeff_addr_b[8:4], coeff_addr_b[1], coeff_addr_a[10], coeff_addr_b[8:3], coeff_addr_b[20], 2'h3, coeff_addr_b[8:3], coeff_addr_a[10], coeff_addr_b[8:2], 1'h1, coeff_addr_a[10] };
  assign { coeff_addr_a[71:57], coeff_addr_a[55:40], coeff_addr_a[37:29], coeff_addr_a[27:21], coeff_addr_a[18:11], coeff_addr_a[2:0] } = { coeff_addr_a[8:4], coeff_addr_a[39], coeff_addr_a[56], coeff_addr_a[28], coeff_addr_a[9:4], coeff_addr_a[39], coeff_addr_a[19], 1'h0, coeff_addr_a[8:4], coeff_addr_a[39:38], coeff_addr_a[10:4], 2'h0, coeff_addr_a[8:3], coeff_addr_a[20], coeff_addr_a[9:3], 1'h0, coeff_addr_a[8:3], 4'h0 };
  assign lane_valid = { batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid, batch_valid };
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
