/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input [3:0] cfg_last_stage;
  wire [3:0] cfg_last_stage;
  input [3:0] cfg_first_span_log2;
  wire [3:0] cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output [3:0] stage_count;
  wire [3:0] stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output lane_valid;
  wire lane_valid;
  output [9:0] coeff_addr_a;
  wire [9:0] coeff_addr_a;
  output [9:0] coeff_addr_b;
  wire [9:0] coeff_addr_b;
  output [8:0] butterfly_index;
  wire [8:0] butterfly_index;
  output [3:0] batch_stage;
  wire [3:0] batch_stage;
  output [3:0] batch_span_log2;
  wire [3:0] batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire [3:0] _336_;
  wire [3:0] _337_;
  wire [3:0] _338_;
  wire [3:0] _339_;
  wire [8:0] _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire [4:0] _365_;
  wire descending_q;
  wire [3:0] first_span_q;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire [3:0] \u_controller.cfg_last_stage ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire [3:0] \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire [3:0] \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.clk ;
  wire [3:0] \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire [3:0] \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire [8:0] \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire [3:0] \u_scheduler.batch_span_log2 ;
  wire [3:0] \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [8:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [9:0] \u_scheduler.coeff_addr_a ;
  wire [9:0] \u_scheduler.coeff_addr_b ;
  wire [9:0] \u_scheduler.decode_lanes.ordinal ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire \u_scheduler.lane_valid ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.rst_n ;
  wire [3:0] \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire [3:0] \u_scheduler.span_q ;
  wire [3:0] \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire [3:0] \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _366_ (
    .A(cfg_first_span_log2[3]),
    .ZN(_060_)
  );
  INV_X1 _367_ (
    .A(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_061_)
  );
  INV_X1 _368_ (
    .A(backend_flushed),
    .ZN(_070_)
  );
  AND2_X1 _369_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_157_)
  );
  AND3_X1 _370_ (
    .A1(_096_),
    .A2(_155_),
    .A3(_157_),
    .ZN(scheduler_quiescent)
  );
  AND2_X1 _371_ (
    .A1(rst_n),
    .A2(_012_),
    .ZN(busy)
  );
  NOR3_X1 _372_ (
    .A1(cfg_last_stage[0]),
    .A2(cfg_last_stage[2]),
    .A3(cfg_last_stage[1]),
    .ZN(_158_)
  );
  NAND2_X1 _373_ (
    .A1(cfg_last_stage[0]),
    .A2(_069_),
    .ZN(_159_)
  );
  NOR2_X1 _374_ (
    .A1(cfg_span_descending),
    .A2(_158_),
    .ZN(_160_)
  );
  AOI21_X1 _375_ (
    .A(cfg_span_descending),
    .B1(_078_),
    .B2(_158_),
    .ZN(_161_)
  );
  XNOR2_X1 _376_ (
    .A(cfg_last_stage[3]),
    .B(_160_),
    .ZN(_162_)
  );
  AND2_X1 _377_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_162_),
    .ZN(_163_)
  );
  NOR2_X1 _378_ (
    .A1(cfg_first_span_log2[3]),
    .A2(_162_),
    .ZN(_164_)
  );
  INV_X1 _379_ (
    .A(\u_controller.state [0]),
    .ZN(_071_)
  );
  OAI21_X1 _380_ (
    .A(_069_),
    .B1(cfg_last_stage[1]),
    .B2(cfg_last_stage[0]),
    .ZN(_165_)
  );
  XNOR2_X1 _381_ (
    .A(cfg_last_stage[2]),
    .B(_165_),
    .ZN(_166_)
  );
  NOR2_X1 _382_ (
    .A1(_088_),
    .A2(_166_),
    .ZN(_167_)
  );
  XOR2_X1 _383_ (
    .A(cfg_last_stage[1]),
    .B(_159_),
    .Z(_168_)
  );
  NAND2_X1 _384_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_168_),
    .ZN(_169_)
  );
  NAND2_X1 _385_ (
    .A1(cfg_last_stage[0]),
    .A2(_085_),
    .ZN(_170_)
  );
  INV_X1 _386_ (
    .A(_170_),
    .ZN(_171_)
  );
  NOR2_X1 _387_ (
    .A1(cfg_first_span_log2[1]),
    .A2(_168_),
    .ZN(_172_)
  );
  XNOR2_X1 _388_ (
    .A(_064_),
    .B(_168_),
    .ZN(_173_)
  );
  OAI21_X1 _389_ (
    .A(_169_),
    .B1(_171_),
    .B2(_172_),
    .ZN(_174_)
  );
  INV_X1 _390_ (
    .A(\u_scheduler.batch_index_q [8]),
    .ZN(_072_)
  );
  XNOR2_X1 _391_ (
    .A(_088_),
    .B(_166_),
    .ZN(_175_)
  );
  INV_X1 _392_ (
    .A(_175_),
    .ZN(_176_)
  );
  AOI21_X1 _393_ (
    .A(_167_),
    .B1(_174_),
    .B2(_176_),
    .ZN(_177_)
  );
  NOR2_X1 _394_ (
    .A1(_164_),
    .A2(_177_),
    .ZN(_178_)
  );
  OAI21_X1 _395_ (
    .A(_161_),
    .B1(_163_),
    .B2(_178_),
    .ZN(_179_)
  );
  OAI21_X1 _396_ (
    .A(cfg_last_stage[3]),
    .B1(cfg_last_stage[2]),
    .B2(cfg_last_stage[1]),
    .ZN(_180_)
  );
  OAI21_X1 _397_ (
    .A(cfg_first_span_log2[3]),
    .B1(cfg_first_span_log2[1]),
    .B2(cfg_first_span_log2[2]),
    .ZN(_181_)
  );
  NAND3_X1 _398_ (
    .A1(_179_),
    .A2(_180_),
    .A3(_181_),
    .ZN(_182_)
  );
  NOR3_X1 _399_ (
    .A1(_161_),
    .A2(_163_),
    .A3(_178_),
    .ZN(_183_)
  );
  NOR2_X1 _400_ (
    .A1(_163_),
    .A2(_164_),
    .ZN(_184_)
  );
  INV_X1 _401_ (
    .A(\u_scheduler.stage_q [3]),
    .ZN(_073_)
  );
  XNOR2_X1 _402_ (
    .A(_170_),
    .B(_173_),
    .ZN(_185_)
  );
  XNOR2_X1 _403_ (
    .A(_174_),
    .B(_176_),
    .ZN(_186_)
  );
  XOR2_X1 _404_ (
    .A(_177_),
    .B(_184_),
    .Z(_187_)
  );
  AOI21_X1 _405_ (
    .A(_187_),
    .B1(_186_),
    .B2(_185_),
    .ZN(_188_)
  );
  NOR3_X1 _406_ (
    .A1(_182_),
    .A2(_183_),
    .A3(_188_),
    .ZN(_189_)
  );
  NAND2_X1 _407_ (
    .A1(enable),
    .A2(_106_),
    .ZN(_190_)
  );
  NOR3_X1 _408_ (
    .A1(backend_flushed),
    .A2(_071_),
    .A3(_190_),
    .ZN(_191_)
  );
  AND3_X1 _409_ (
    .A1(scheduler_quiescent),
    .A2(_189_),
    .A3(_191_),
    .ZN(ready)
  );
  NAND2_X1 _410_ (
    .A1(start),
    .A2(ready),
    .ZN(_192_)
  );
  INV_X1 _411_ (
    .A(_192_),
    .ZN(_019_)
  );
  INV_X1 _412_ (
    .A(\u_scheduler.span_q [3]),
    .ZN(_074_)
  );
  NAND2_X1 _413_ (
    .A1(rst_n),
    .A2(start),
    .ZN(_193_)
  );
  NOR4_X1 _414_ (
    .A1(_012_),
    .A2(_189_),
    .A3(_190_),
    .A4(_193_),
    .ZN(_194_)
  );
  AOI21_X1 _415_ (
    .A(_194_),
    .B1(_192_),
    .B2(error_config),
    .ZN(_195_)
  );
  INV_X1 _416_ (
    .A(_195_),
    .ZN(_059_)
  );
  AOI21_X1 _417_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_192_),
    .ZN(_196_)
  );
  INV_X1 _418_ (
    .A(_196_),
    .ZN(_058_)
  );
  AOI21_X1 _419_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_192_),
    .ZN(_197_)
  );
  INV_X1 _420_ (
    .A(_197_),
    .ZN(_057_)
  );
  AOI21_X1 _421_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_192_),
    .ZN(_198_)
  );
  INV_X1 _422_ (
    .A(_198_),
    .ZN(_056_)
  );
  INV_X1 _423_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_075_)
  );
  AOI21_X1 _424_ (
    .A(_102_),
    .B1(_192_),
    .B2(error_controller),
    .ZN(_199_)
  );
  INV_X1 _425_ (
    .A(_199_),
    .ZN(_055_)
  );
  NOR2_X1 _426_ (
    .A1(zeroize_req),
    .A2(_019_),
    .ZN(_200_)
  );
  NAND2_X1 _427_ (
    .A1(first_span_q[3]),
    .A2(_200_),
    .ZN(_201_)
  );
  OAI21_X1 _428_ (
    .A(_201_),
    .B1(_192_),
    .B2(_060_),
    .ZN(_054_)
  );
  NAND2_X1 _429_ (
    .A1(descending_q),
    .A2(_200_),
    .ZN(_202_)
  );
  OAI21_X1 _430_ (
    .A(_202_),
    .B1(_192_),
    .B2(_069_),
    .ZN(_053_)
  );
  NAND2_X1 _431_ (
    .A1(_071_),
    .A2(_097_),
    .ZN(_203_)
  );
  NAND2_X1 _432_ (
    .A1(_192_),
    .A2(_203_),
    .ZN(_204_)
  );
  AOI21_X1 _433_ (
    .A(_099_),
    .B1(_103_),
    .B2(_063_),
    .ZN(_205_)
  );
  INV_X1 _434_ (
    .A(\u_scheduler.span_q [0]),
    .ZN(_076_)
  );
  AOI211_X1 _435_ (
    .A(zeroize),
    .B(_099_),
    .C1(_103_),
    .C2(_063_),
    .ZN(_015_)
  );
  AOI22_X1 _436_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_336_[2]),
    .B1(_336_[3]),
    .B2(\u_controller.u_stage_counter.stage_count [3]),
    .ZN(_206_)
  );
  NOR2_X1 _437_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(_336_[3]),
    .ZN(_207_)
  );
  OAI21_X1 _438_ (
    .A(_206_),
    .B1(_336_[2]),
    .B2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_208_)
  );
  OR2_X1 _439_ (
    .A1(_207_),
    .A2(_208_),
    .ZN(_209_)
  );
  OAI22_X1 _440_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_336_[0]),
    .B1(\u_controller.u_stage_counter.stage_count [1]),
    .B2(_336_[1]),
    .ZN(_210_)
  );
  NAND2_X1 _441_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_336_[1]),
    .ZN(_211_)
  );
  AOI21_X1 _442_ (
    .A(_209_),
    .B1(_210_),
    .B2(_211_),
    .ZN(_212_)
  );
  NOR2_X1 _443_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .ZN(_213_)
  );
  OAI211_X1 _444_ (
    .A(\u_controller.state [1]),
    .B(_213_),
    .C1(_207_),
    .C2(_206_),
    .ZN(_214_)
  );
  INV_X1 _445_ (
    .A(\u_scheduler.batch_index_q [5]),
    .ZN(_077_)
  );
  NOR3_X1 _446_ (
    .A1(_015_),
    .A2(_212_),
    .A3(_214_),
    .ZN(_215_)
  );
  NAND4_X1 _447_ (
    .A1(_095_),
    .A2(_149_),
    .A3(_155_),
    .A4(_157_),
    .ZN(_216_)
  );
  INV_X1 _448_ (
    .A(_216_),
    .ZN(stage_done)
  );
  NOR2_X1 _449_ (
    .A1(_067_),
    .A2(_216_),
    .ZN(_014_)
  );
  OAI21_X1 _450_ (
    .A(_215_),
    .B1(_216_),
    .B2(_067_),
    .ZN(_217_)
  );
  NAND2_X1 _451_ (
    .A1(\u_controller.state [6]),
    .A2(_106_),
    .ZN(_218_)
  );
  OAI21_X1 _452_ (
    .A(_107_),
    .B1(stage_done),
    .B2(_218_),
    .ZN(_020_)
  );
  NOR2_X1 _453_ (
    .A1(zeroize),
    .A2(_205_),
    .ZN(_219_)
  );
  NAND2_X1 _454_ (
    .A1(\u_controller.state [7]),
    .A2(_219_),
    .ZN(_220_)
  );
  NOR2_X1 _455_ (
    .A1(_066_),
    .A2(_104_),
    .ZN(_221_)
  );
  INV_X1 _456_ (
    .A(cfg_last_stage[3]),
    .ZN(_078_)
  );
  NAND2_X1 _457_ (
    .A1(scheduler_quiescent),
    .A2(_221_),
    .ZN(_222_)
  );
  AOI21_X1 _458_ (
    .A(_220_),
    .B1(_221_),
    .B2(scheduler_quiescent),
    .ZN(_223_)
  );
  NOR4_X1 _459_ (
    .A1(_019_),
    .A2(_217_),
    .A3(_020_),
    .A4(_223_),
    .ZN(_224_)
  );
  AND3_X1 _460_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(\u_controller.u_stage_counter.stage_count [1]),
    .A3(_224_),
    .ZN(_225_)
  );
  OAI21_X1 _461_ (
    .A(_211_),
    .B1(_062_),
    .B2(_061_),
    .ZN(_226_)
  );
  NOR3_X1 _462_ (
    .A1(_209_),
    .A2(_210_),
    .A3(_226_),
    .ZN(_227_)
  );
  NAND2_X1 _463_ (
    .A1(\u_controller.state [1]),
    .A2(_106_),
    .ZN(_228_)
  );
  AOI21_X1 _464_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B1(\u_controller.u_stage_counter.stage_count [2]),
    .B2(_225_),
    .ZN(_229_)
  );
  NOR2_X1 _465_ (
    .A1(_204_),
    .A2(_229_),
    .ZN(_052_)
  );
  MUX2_X1 _466_ (
    .A(\u_controller.u_stage_counter.last_stage_q [3]),
    .B(cfg_last_stage[3]),
    .S(_019_),
    .Z(_230_)
  );
  INV_X1 _467_ (
    .A(\u_controller.state [5]),
    .ZN(_079_)
  );
  AND2_X1 _468_ (
    .A1(_203_),
    .A2(_230_),
    .ZN(_051_)
  );
  NAND2_X1 _469_ (
    .A1(rst_n),
    .A2(\u_controller.state [6]),
    .ZN(_231_)
  );
  INV_X1 _470_ (
    .A(_231_),
    .ZN(butterfly_enable)
  );
  OR4_X1 _471_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(_009_),
    .A4(_150_),
    .ZN(_232_)
  );
  NOR2_X1 _472_ (
    .A1(_231_),
    .A2(_232_),
    .ZN(_233_)
  );
  AND3_X1 _473_ (
    .A1(_155_),
    .A2(_157_),
    .A3(_233_),
    .ZN(batch_valid)
  );
  NAND2_X1 _474_ (
    .A1(\u_controller.state [4]),
    .A2(_106_),
    .ZN(_234_)
  );
  AND3_X1 _475_ (
    .A1(\u_controller.state [4]),
    .A2(rst_n),
    .A3(_106_),
    .ZN(load_start)
  );
  AND2_X1 _476_ (
    .A1(rst_n),
    .A2(_098_),
    .ZN(active)
  );
  OR3_X1 _477_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .A3(_223_),
    .ZN(_021_)
  );
  INV_X1 _478_ (
    .A(_336_[0]),
    .ZN(_062_)
  );
  INV_X1 _479_ (
    .A(\u_scheduler.batch_index_q [0]),
    .ZN(_080_)
  );
  NAND2_X1 _480_ (
    .A1(backend_flushed),
    .A2(_150_),
    .ZN(_235_)
  );
  NOR2_X1 _481_ (
    .A1(batch_retired),
    .A2(_147_),
    .ZN(_236_)
  );
  OAI211_X1 _482_ (
    .A(_235_),
    .B(_236_),
    .C1(\u_scheduler.state [2]),
    .C2(_150_),
    .ZN(_237_)
  );
  NAND2_X1 _483_ (
    .A1(batch_retired),
    .A2(_000_),
    .ZN(_238_)
  );
  NAND3_X1 _484_ (
    .A1(\u_scheduler.state [2]),
    .A2(_070_),
    .A3(_238_),
    .ZN(_239_)
  );
  OAI211_X1 _485_ (
    .A(_155_),
    .B(_237_),
    .C1(_239_),
    .C2(_154_),
    .ZN(\u_scheduler.next_state [2])
  );
  OAI21_X1 _486_ (
    .A(\u_scheduler.fault_q ),
    .B1(_070_),
    .B2(_154_),
    .ZN(_240_)
  );
  NAND2_X1 _487_ (
    .A1(_155_),
    .A2(_240_),
    .ZN(_050_)
  );
  MUX2_X1 _488_ (
    .A(\u_controller.intt_mode_q ),
    .B(intt_mode),
    .S(_019_),
    .Z(_241_)
  );
  AND2_X1 _489_ (
    .A1(_203_),
    .A2(_241_),
    .ZN(_049_)
  );
  INV_X1 _490_ (
    .A(\u_scheduler.batch_index_q [1]),
    .ZN(_081_)
  );
  NAND4_X1 _491_ (
    .A1(_000_),
    .A2(_094_),
    .A3(_110_),
    .A4(_155_),
    .ZN(_242_)
  );
  AND4_X1 _492_ (
    .A1(batch_ready),
    .A2(_155_),
    .A3(_157_),
    .A4(_233_),
    .ZN(_243_)
  );
  NAND4_X1 _493_ (
    .A1(batch_ready),
    .A2(_155_),
    .A3(_157_),
    .A4(_233_),
    .ZN(_244_)
  );
  OR2_X1 _494_ (
    .A1(_093_),
    .A2(_232_),
    .ZN(_245_)
  );
  INV_X1 _495_ (
    .A(_245_),
    .ZN(_246_)
  );
  NAND3_X1 _496_ (
    .A1(batch_retired),
    .A2(_146_),
    .A3(_149_),
    .ZN(_247_)
  );
  OAI211_X1 _497_ (
    .A(_242_),
    .B(_247_),
    .C1(_245_),
    .C2(_243_),
    .ZN(_248_)
  );
  NOR3_X1 _498_ (
    .A1(_006_),
    .A2(_007_),
    .A3(_008_),
    .ZN(_249_)
  );
  NOR2_X1 _499_ (
    .A1(_013_),
    .A2(_340_[0]),
    .ZN(_250_)
  );
  NOR4_X1 _500_ (
    .A1(_002_),
    .A2(_003_),
    .A3(_004_),
    .A4(_005_),
    .ZN(_251_)
  );
  INV_X1 _501_ (
    .A(\u_scheduler.batch_index_q [2]),
    .ZN(_082_)
  );
  NAND3_X1 _502_ (
    .A1(_249_),
    .A2(_250_),
    .A3(_251_),
    .ZN(_252_)
  );
  NAND3_X1 _503_ (
    .A1(\u_scheduler.state [1]),
    .A2(_149_),
    .A3(_236_),
    .ZN(_253_)
  );
  OAI21_X1 _504_ (
    .A(_253_),
    .B1(_252_),
    .B2(_247_),
    .ZN(_254_)
  );
  INV_X1 _505_ (
    .A(_254_),
    .ZN(_255_)
  );
  NAND2_X1 _506_ (
    .A1(_244_),
    .A2(_255_),
    .ZN(_256_)
  );
  AND3_X1 _507_ (
    .A1(batch_retired),
    .A2(_146_),
    .A3(_149_),
    .ZN(_257_)
  );
  AND4_X1 _508_ (
    .A1(_000_),
    .A2(_094_),
    .A3(_110_),
    .A4(_155_),
    .ZN(_258_)
  );
  NAND4_X1 _509_ (
    .A1(_000_),
    .A2(_094_),
    .A3(_110_),
    .A4(_155_),
    .ZN(_259_)
  );
  AOI211_X1 _510_ (
    .A(_257_),
    .B(_258_),
    .C1(_244_),
    .C2(_246_),
    .ZN(_260_)
  );
  NOR3_X1 _511_ (
    .A1(\u_scheduler.next_state [2]),
    .A2(_248_),
    .A3(_256_),
    .ZN(_261_)
  );
  INV_X1 _512_ (
    .A(\u_scheduler.batch_index_q [3]),
    .ZN(_083_)
  );
  NOR2_X1 _513_ (
    .A1(_258_),
    .A2(_261_),
    .ZN(_262_)
  );
  OR2_X1 _514_ (
    .A1(_258_),
    .A2(_261_),
    .ZN(_263_)
  );
  NAND4_X1 _515_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(\u_scheduler.batch_index_q [0]),
    .A3(\u_scheduler.batch_index_q [2]),
    .A4(\u_scheduler.batch_index_q [3]),
    .ZN(_264_)
  );
  OR2_X1 _516_ (
    .A1(_081_),
    .A2(_264_),
    .ZN(_265_)
  );
  NAND3_X1 _517_ (
    .A1(_146_),
    .A2(_244_),
    .A3(_255_),
    .ZN(_266_)
  );
  AND2_X1 _518_ (
    .A1(_155_),
    .A2(_248_),
    .ZN(\u_scheduler.next_state [0])
  );
  NOR3_X1 _519_ (
    .A1(_156_),
    .A2(_260_),
    .A3(_266_),
    .ZN(_267_)
  );
  NOR4_X1 _520_ (
    .A1(_156_),
    .A2(_260_),
    .A3(_265_),
    .A4(_266_),
    .ZN(_268_)
  );
  AND2_X1 _521_ (
    .A1(\u_scheduler.batch_index_q [5]),
    .A2(_268_),
    .ZN(_269_)
  );
  AND3_X1 _522_ (
    .A1(\u_scheduler.batch_index_q [6]),
    .A2(\u_scheduler.batch_index_q [7]),
    .A3(_269_),
    .ZN(_270_)
  );
  INV_X1 _523_ (
    .A(\u_scheduler.batch_index_q [7]),
    .ZN(_084_)
  );
  NAND4_X1 _524_ (
    .A1(\u_scheduler.batch_index_q [5]),
    .A2(\u_scheduler.batch_index_q [6]),
    .A3(\u_scheduler.batch_index_q [7]),
    .A4(_268_),
    .ZN(_271_)
  );
  OAI21_X1 _525_ (
    .A(_262_),
    .B1(_271_),
    .B2(_072_),
    .ZN(_272_)
  );
  AOI21_X1 _526_ (
    .A(_272_),
    .B1(_271_),
    .B2(_072_),
    .ZN(_048_)
  );
  NAND2_X1 _527_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(_258_),
    .ZN(_273_)
  );
  OAI21_X1 _528_ (
    .A(_273_),
    .B1(_263_),
    .B2(_073_),
    .ZN(_047_)
  );
  NAND2_X1 _529_ (
    .A1(_136_),
    .A2(_258_),
    .ZN(_274_)
  );
  OAI21_X1 _530_ (
    .A(_274_),
    .B1(_263_),
    .B2(_074_),
    .ZN(_046_)
  );
  NAND2_X1 _531_ (
    .A1(\u_controller.intt_mode_q ),
    .A2(_258_),
    .ZN(_275_)
  );
  OAI21_X1 _532_ (
    .A(_275_),
    .B1(_263_),
    .B2(_075_),
    .ZN(_045_)
  );
  NAND2_X1 _533_ (
    .A1(_011_),
    .A2(_086_),
    .ZN(_276_)
  );
  INV_X1 _534_ (
    .A(cfg_first_span_log2[0]),
    .ZN(_085_)
  );
  NAND4_X1 _535_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(_011_),
    .A3(_086_),
    .A4(_087_),
    .ZN(_277_)
  );
  NAND2_X1 _536_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_278_)
  );
  NAND2_X1 _537_ (
    .A1(_074_),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_279_)
  );
  NOR2_X1 _538_ (
    .A1(_278_),
    .A2(_279_),
    .ZN(_280_)
  );
  NAND2_X1 _539_ (
    .A1(_011_),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_281_)
  );
  NOR2_X1 _540_ (
    .A1(_279_),
    .A2(_281_),
    .ZN(_282_)
  );
  NAND2_X1 _541_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(_086_),
    .ZN(_283_)
  );
  INV_X1 _542_ (
    .A(_283_),
    .ZN(_284_)
  );
  NOR2_X1 _543_ (
    .A1(_279_),
    .A2(_283_),
    .ZN(_285_)
  );
  NOR2_X1 _544_ (
    .A1(\u_scheduler.span_q [3]),
    .A2(\u_scheduler.span_q [2]),
    .ZN(_286_)
  );
  INV_X1 _545_ (
    .A(\u_scheduler.span_q [1]),
    .ZN(_086_)
  );
  INV_X1 _546_ (
    .A(_286_),
    .ZN(_287_)
  );
  NOR2_X1 _547_ (
    .A1(_278_),
    .A2(_287_),
    .ZN(_288_)
  );
  NAND2_X1 _548_ (
    .A1(_284_),
    .A2(_286_),
    .ZN(_289_)
  );
  NOR2_X1 _549_ (
    .A1(_276_),
    .A2(_287_),
    .ZN(_290_)
  );
  OAI21_X1 _550_ (
    .A(_286_),
    .B1(_284_),
    .B2(_011_),
    .ZN(_291_)
  );
  OAI21_X1 _551_ (
    .A(_286_),
    .B1(_011_),
    .B2(\u_scheduler.span_q [0]),
    .ZN(_292_)
  );
  OAI21_X1 _552_ (
    .A(_292_),
    .B1(_279_),
    .B2(_276_),
    .ZN(_293_)
  );
  NOR3_X1 _553_ (
    .A1(_282_),
    .A2(_285_),
    .A3(_293_),
    .ZN(_294_)
  );
  INV_X1 _554_ (
    .A(_294_),
    .ZN(_295_)
  );
  NOR2_X1 _555_ (
    .A1(_280_),
    .A2(_295_),
    .ZN(_296_)
  );
  INV_X1 _556_ (
    .A(\u_scheduler.span_q [2]),
    .ZN(_087_)
  );
  NAND2_X1 _557_ (
    .A1(_277_),
    .A2(_296_),
    .ZN(_297_)
  );
  AOI21_X1 _558_ (
    .A(_072_),
    .B1(_277_),
    .B2(_296_),
    .ZN(coeff_addr_a[9])
  );
  XOR2_X1 _559_ (
    .A(_280_),
    .B(_294_),
    .Z(_298_)
  );
  OAI22_X1 _560_ (
    .A1(_072_),
    .A2(_297_),
    .B1(_298_),
    .B2(_084_),
    .ZN(coeff_addr_a[8])
  );
  NOR3_X1 _561_ (
    .A1(_074_),
    .A2(\u_scheduler.span_q [2]),
    .A3(_283_),
    .ZN(_299_)
  );
  OR2_X1 _562_ (
    .A1(coeff_addr_a[9]),
    .A2(_299_),
    .ZN(coeff_addr_b[9])
  );
  NAND2_X1 _563_ (
    .A1(\u_controller.state [5]),
    .A2(_106_),
    .ZN(_300_)
  );
  AND3_X1 _564_ (
    .A1(rst_n),
    .A2(\u_controller.state [5]),
    .A3(_106_),
    .ZN(done)
  );
  NAND3_X1 _565_ (
    .A1(\u_controller.state [0]),
    .A2(_192_),
    .A3(_219_),
    .ZN(_301_)
  );
  OAI211_X1 _566_ (
    .A(_300_),
    .B(_301_),
    .C1(_220_),
    .C2(_222_),
    .ZN(_017_)
  );
  INV_X1 _567_ (
    .A(cfg_first_span_log2[2]),
    .ZN(_088_)
  );
  OAI21_X1 _568_ (
    .A(_234_),
    .B1(_228_),
    .B2(_227_),
    .ZN(_018_)
  );
  AND3_X1 _569_ (
    .A1(\u_controller.state [1]),
    .A2(_106_),
    .A3(_227_),
    .ZN(_016_)
  );
  MUX2_X1 _570_ (
    .A(_289_),
    .B(_284_),
    .S(_290_),
    .Z(_302_)
  );
  AOI22_X1 _571_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_290_),
    .B1(_302_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_303_)
  );
  INV_X1 _572_ (
    .A(_303_),
    .ZN(coeff_addr_a[1])
  );
  NAND2_X1 _573_ (
    .A1(\u_scheduler.batch_index_q [2]),
    .A2(_291_),
    .ZN(_304_)
  );
  OAI21_X1 _574_ (
    .A(_304_),
    .B1(_302_),
    .B2(_081_),
    .ZN(coeff_addr_a[2])
  );
  AOI21_X1 _575_ (
    .A(_292_),
    .B1(_288_),
    .B2(_011_),
    .ZN(_305_)
  );
  OAI22_X1 _576_ (
    .A1(_082_),
    .A2(_291_),
    .B1(_305_),
    .B2(_083_),
    .ZN(coeff_addr_a[3])
  );
  NAND2_X1 _577_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_305_),
    .ZN(_306_)
  );
  INV_X1 _578_ (
    .A(\u_scheduler.stage_q [0]),
    .ZN(_089_)
  );
  OAI21_X1 _579_ (
    .A(_306_),
    .B1(_293_),
    .B2(_068_),
    .ZN(coeff_addr_a[4])
  );
  INV_X1 _580_ (
    .A(coeff_addr_a[4]),
    .ZN(_307_)
  );
  XNOR2_X1 _581_ (
    .A(_285_),
    .B(_293_),
    .ZN(_308_)
  );
  AOI22_X1 _582_ (
    .A1(\u_scheduler.batch_index_q [4]),
    .A2(_293_),
    .B1(_308_),
    .B2(\u_scheduler.batch_index_q [5]),
    .ZN(_309_)
  );
  INV_X1 _583_ (
    .A(_309_),
    .ZN(coeff_addr_a[5])
  );
  NAND2_X1 _584_ (
    .A1(\u_scheduler.batch_index_q [6]),
    .A2(_294_),
    .ZN(_310_)
  );
  OAI21_X1 _585_ (
    .A(_310_),
    .B1(_308_),
    .B2(_077_),
    .ZN(coeff_addr_a[6])
  );
  AOI22_X1 _586_ (
    .A1(\u_scheduler.batch_index_q [6]),
    .A2(_295_),
    .B1(_298_),
    .B2(\u_scheduler.batch_index_q [7]),
    .ZN(_311_)
  );
  INV_X1 _587_ (
    .A(_311_),
    .ZN(coeff_addr_a[7])
  );
  NOR2_X1 _588_ (
    .A1(_080_),
    .A2(_290_),
    .ZN(coeff_addr_a[0])
  );
  INV_X1 _589_ (
    .A(abort_req),
    .ZN(_063_)
  );
  INV_X1 _590_ (
    .A(\u_scheduler.stage_q [1]),
    .ZN(_090_)
  );
  XOR2_X1 _591_ (
    .A(_338_[0]),
    .B(first_span_q[0]),
    .Z(_312_)
  );
  OAI22_X1 _592_ (
    .A1(_076_),
    .A2(_263_),
    .B1(_312_),
    .B2(_259_),
    .ZN(_044_)
  );
  OAI22_X1 _593_ (
    .A1(_132_),
    .A2(_259_),
    .B1(_263_),
    .B2(_086_),
    .ZN(_043_)
  );
  OAI22_X1 _594_ (
    .A1(_133_),
    .A2(_259_),
    .B1(_263_),
    .B2(_087_),
    .ZN(_042_)
  );
  OAI22_X1 _595_ (
    .A1(_061_),
    .A2(_259_),
    .B1(_263_),
    .B2(_089_),
    .ZN(_041_)
  );
  NAND2_X1 _596_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_258_),
    .ZN(_313_)
  );
  OAI21_X1 _597_ (
    .A(_313_),
    .B1(_263_),
    .B2(_090_),
    .ZN(_040_)
  );
  NAND2_X1 _598_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_258_),
    .ZN(_314_)
  );
  OAI21_X1 _599_ (
    .A(_314_),
    .B1(_263_),
    .B2(_091_),
    .ZN(_039_)
  );
  NOR2_X1 _600_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_267_),
    .ZN(_315_)
  );
  INV_X1 _601_ (
    .A(\u_scheduler.stage_q [2]),
    .ZN(_091_)
  );
  AOI211_X1 _602_ (
    .A(_263_),
    .B(_315_),
    .C1(_267_),
    .C2(_092_),
    .ZN(_038_)
  );
  OR4_X1 _603_ (
    .A1(_080_),
    .A2(_156_),
    .A3(_260_),
    .A4(_266_),
    .ZN(_316_)
  );
  INV_X1 _604_ (
    .A(_316_),
    .ZN(_317_)
  );
  OAI21_X1 _605_ (
    .A(_262_),
    .B1(_317_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_318_)
  );
  AOI21_X1 _606_ (
    .A(_318_),
    .B1(_317_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_037_)
  );
  AOI21_X1 _607_ (
    .A(\u_scheduler.batch_index_q [2]),
    .B1(_317_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_319_)
  );
  NOR3_X1 _608_ (
    .A1(_081_),
    .A2(_082_),
    .A3(_316_),
    .ZN(_320_)
  );
  NOR3_X1 _609_ (
    .A1(_263_),
    .A2(_319_),
    .A3(_320_),
    .ZN(_036_)
  );
  OAI21_X1 _610_ (
    .A(_262_),
    .B1(_320_),
    .B2(\u_scheduler.batch_index_q [3]),
    .ZN(_321_)
  );
  AOI21_X1 _611_ (
    .A(_321_),
    .B1(_320_),
    .B2(\u_scheduler.batch_index_q [3]),
    .ZN(_035_)
  );
  INV_X1 _612_ (
    .A(_340_[0]),
    .ZN(_092_)
  );
  AOI21_X1 _613_ (
    .A(\u_scheduler.batch_index_q [4]),
    .B1(\u_scheduler.batch_index_q [3]),
    .B2(_320_),
    .ZN(_322_)
  );
  NOR3_X1 _614_ (
    .A1(_263_),
    .A2(_268_),
    .A3(_322_),
    .ZN(_034_)
  );
  NOR2_X1 _615_ (
    .A1(\u_scheduler.batch_index_q [5]),
    .A2(_268_),
    .ZN(_323_)
  );
  NOR3_X1 _616_ (
    .A1(_263_),
    .A2(_269_),
    .A3(_323_),
    .ZN(_033_)
  );
  OAI21_X1 _617_ (
    .A(_262_),
    .B1(_269_),
    .B2(\u_scheduler.batch_index_q [6]),
    .ZN(_324_)
  );
  AOI21_X1 _618_ (
    .A(_324_),
    .B1(_269_),
    .B2(\u_scheduler.batch_index_q [6]),
    .ZN(_032_)
  );
  AOI21_X1 _619_ (
    .A(\u_scheduler.batch_index_q [7]),
    .B1(_269_),
    .B2(\u_scheduler.batch_index_q [6]),
    .ZN(_325_)
  );
  NOR3_X1 _620_ (
    .A1(_263_),
    .A2(_270_),
    .A3(_325_),
    .ZN(_031_)
  );
  MUX2_X1 _621_ (
    .A(\u_controller.u_stage_counter.last_stage_q [0]),
    .B(cfg_last_stage[0]),
    .S(_019_),
    .Z(_326_)
  );
  AND2_X1 _622_ (
    .A1(_203_),
    .A2(_326_),
    .ZN(_030_)
  );
  INV_X1 _623_ (
    .A(\u_scheduler.state [0]),
    .ZN(_093_)
  );
  MUX2_X1 _624_ (
    .A(\u_controller.u_stage_counter.last_stage_q [1]),
    .B(cfg_last_stage[1]),
    .S(_019_),
    .Z(_327_)
  );
  AND2_X1 _625_ (
    .A1(_203_),
    .A2(_327_),
    .ZN(_029_)
  );
  MUX2_X1 _626_ (
    .A(\u_controller.u_stage_counter.last_stage_q [2]),
    .B(cfg_last_stage[2]),
    .S(_019_),
    .Z(_328_)
  );
  AND2_X1 _627_ (
    .A1(_203_),
    .A2(_328_),
    .ZN(_028_)
  );
  NAND2_X1 _628_ (
    .A1(_338_[0]),
    .A2(_224_),
    .ZN(_329_)
  );
  OR2_X1 _629_ (
    .A1(_061_),
    .A2(_224_),
    .ZN(_330_)
  );
  AOI21_X1 _630_ (
    .A(_204_),
    .B1(_329_),
    .B2(_330_),
    .ZN(_027_)
  );
  AOI21_X1 _631_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .B1(_224_),
    .B2(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_331_)
  );
  NOR3_X1 _632_ (
    .A1(_204_),
    .A2(_225_),
    .A3(_331_),
    .ZN(_026_)
  );
  NOR2_X1 _633_ (
    .A1(\u_controller.u_stage_counter.stage_count [2]),
    .A2(_225_),
    .ZN(_332_)
  );
  NOR3_X1 _634_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(\u_scheduler.state [1]),
    .ZN(_094_)
  );
  AOI211_X1 _635_ (
    .A(_204_),
    .B(_332_),
    .C1(_225_),
    .C2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_025_)
  );
  NAND2_X1 _636_ (
    .A1(first_span_q[0]),
    .A2(_200_),
    .ZN(_333_)
  );
  OAI21_X1 _637_ (
    .A(_333_),
    .B1(_192_),
    .B2(_085_),
    .ZN(_024_)
  );
  NAND2_X1 _638_ (
    .A1(first_span_q[1]),
    .A2(_200_),
    .ZN(_334_)
  );
  OAI21_X1 _639_ (
    .A(_334_),
    .B1(_192_),
    .B2(_064_),
    .ZN(_023_)
  );
  NAND2_X1 _640_ (
    .A1(first_span_q[2]),
    .A2(_200_),
    .ZN(_335_)
  );
  OAI21_X1 _641_ (
    .A(_335_),
    .B1(_192_),
    .B2(_088_),
    .ZN(_022_)
  );
  AOI21_X1 _642_ (
    .A(_156_),
    .B1(_244_),
    .B2(_255_),
    .ZN(\u_scheduler.next_state [1])
  );
  OAI21_X1 _643_ (
    .A(_080_),
    .B1(_276_),
    .B2(_287_),
    .ZN(coeff_addr_b[0])
  );
  NAND2_X1 _644_ (
    .A1(_289_),
    .A2(_303_),
    .ZN(coeff_addr_b[1])
  );
  NOR3_X1 _645_ (
    .A1(\u_scheduler.state [2]),
    .A2(_010_),
    .A3(_009_),
    .ZN(_095_)
  );
  OAI221_X1 _646_ (
    .A(_304_),
    .B1(_287_),
    .B2(_281_),
    .C1(_081_),
    .C2(_302_),
    .ZN(coeff_addr_b[2])
  );
  OR2_X1 _647_ (
    .A1(_288_),
    .A2(coeff_addr_a[3]),
    .ZN(coeff_addr_b[3])
  );
  OAI21_X1 _648_ (
    .A(_307_),
    .B1(_279_),
    .B2(_276_),
    .ZN(coeff_addr_b[4])
  );
  OAI21_X1 _649_ (
    .A(_309_),
    .B1(_283_),
    .B2(_279_),
    .ZN(coeff_addr_b[5])
  );
  OR2_X1 _650_ (
    .A1(_282_),
    .A2(coeff_addr_a[6]),
    .ZN(coeff_addr_b[6])
  );
  OAI21_X1 _651_ (
    .A(_311_),
    .B1(_279_),
    .B2(_278_),
    .ZN(coeff_addr_b[7])
  );
  OAI221_X1 _652_ (
    .A(_277_),
    .B1(_297_),
    .B2(_072_),
    .C1(_298_),
    .C2(_084_),
    .ZN(coeff_addr_b[8])
  );
  OR2_X1 _653_ (
    .A1(_094_),
    .A2(_095_),
    .ZN(_096_)
  );
  NOR4_X1 _654_ (
    .A1(\u_controller.state [4]),
    .A2(\u_controller.state [6]),
    .A3(\u_controller.state [1]),
    .A4(\u_controller.state [2]),
    .ZN(_097_)
  );
  OR4_X1 _655_ (
    .A1(\u_controller.state [4]),
    .A2(\u_controller.state [6]),
    .A3(\u_controller.state [1]),
    .A4(\u_controller.state [2]),
    .ZN(_098_)
  );
  NOR2_X1 _656_ (
    .A1(\u_controller.state [5]),
    .A2(_098_),
    .ZN(_099_)
  );
  INV_X1 _657_ (
    .A(cfg_first_span_log2[1]),
    .ZN(_064_)
  );
  NOR2_X1 _658_ (
    .A1(\u_controller.state [0]),
    .A2(\u_controller.state [7]),
    .ZN(_100_)
  );
  NAND4_X1 _659_ (
    .A1(rst_n),
    .A2(_079_),
    .A3(_097_),
    .A4(_100_),
    .ZN(_101_)
  );
  INV_X1 _660_ (
    .A(_101_),
    .ZN(transform_abort)
  );
  NOR2_X1 _661_ (
    .A1(\u_controller.state [3]),
    .A2(_101_),
    .ZN(_102_)
  );
  NOR3_X1 _662_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_103_)
  );
  OAI21_X1 _663_ (
    .A(_103_),
    .B1(_101_),
    .B2(\u_controller.state [3]),
    .ZN(_104_)
  );
  OAI211_X1 _664_ (
    .A(_063_),
    .B(_103_),
    .C1(_101_),
    .C2(\u_controller.state [3]),
    .ZN(_105_)
  );
  NOR2_X1 _665_ (
    .A1(zeroize),
    .A2(_105_),
    .ZN(_106_)
  );
  NAND2_X1 _666_ (
    .A1(\u_controller.state [2]),
    .A2(_106_),
    .ZN(_107_)
  );
  NAND3_X1 _667_ (
    .A1(rst_n),
    .A2(\u_controller.state [2]),
    .A3(_106_),
    .ZN(_108_)
  );
  INV_X1 _668_ (
    .A(first_span_q[1]),
    .ZN(_065_)
  );
  INV_X1 _669_ (
    .A(_108_),
    .ZN(stage_start)
  );
  NAND2_X1 _670_ (
    .A1(rst_n),
    .A2(\u_controller.state [7]),
    .ZN(_109_)
  );
  INV_X1 _671_ (
    .A(_109_),
    .ZN(zeroize_req)
  );
  NOR2_X1 _672_ (
    .A1(\u_controller.state [7]),
    .A2(_108_),
    .ZN(_110_)
  );
  AND3_X1 _673_ (
    .A1(_337_[1]),
    .A2(_338_[0]),
    .A3(_337_[2]),
    .ZN(_111_)
  );
  AOI21_X1 _674_ (
    .A(descending_q),
    .B1(_365_[3]),
    .B2(_111_),
    .ZN(_112_)
  );
  OAI21_X1 _675_ (
    .A(_112_),
    .B1(_111_),
    .B2(_365_[3]),
    .ZN(_113_)
  );
  NAND2_X1 _676_ (
    .A1(\u_controller.u_stage_counter.stage_count [3]),
    .A2(descending_q),
    .ZN(_114_)
  );
  AND3_X1 _677_ (
    .A1(first_span_q[3]),
    .A2(_113_),
    .A3(_114_),
    .ZN(_115_)
  );
  NAND3_X1 _678_ (
    .A1(first_span_q[3]),
    .A2(_113_),
    .A3(_114_),
    .ZN(_116_)
  );
  INV_X1 _679_ (
    .A(scrub_done),
    .ZN(_066_)
  );
  AOI21_X1 _680_ (
    .A(first_span_q[3]),
    .B1(_113_),
    .B2(_114_),
    .ZN(_117_)
  );
  AOI21_X1 _681_ (
    .A(_337_[2]),
    .B1(_338_[0]),
    .B2(_337_[1]),
    .ZN(_118_)
  );
  NOR3_X1 _682_ (
    .A1(descending_q),
    .A2(_111_),
    .A3(_118_),
    .ZN(_119_)
  );
  AOI21_X1 _683_ (
    .A(_119_),
    .B1(\u_controller.u_stage_counter.stage_count [2]),
    .B2(descending_q),
    .ZN(_120_)
  );
  AND2_X1 _684_ (
    .A1(first_span_q[2]),
    .A2(_120_),
    .ZN(_121_)
  );
  XOR2_X1 _685_ (
    .A(_337_[1]),
    .B(_338_[0]),
    .Z(_122_)
  );
  MUX2_X1 _686_ (
    .A(_122_),
    .B(\u_controller.u_stage_counter.stage_count [1]),
    .S(descending_q),
    .Z(_123_)
  );
  OR2_X1 _687_ (
    .A1(_065_),
    .A2(_123_),
    .ZN(_124_)
  );
  NOR2_X1 _688_ (
    .A1(_338_[0]),
    .A2(first_span_q[0]),
    .ZN(_125_)
  );
  XNOR2_X1 _689_ (
    .A(_065_),
    .B(_123_),
    .ZN(_126_)
  );
  INV_X1 _690_ (
    .A(\u_controller.state [6]),
    .ZN(_067_)
  );
  OAI21_X1 _691_ (
    .A(_124_),
    .B1(_125_),
    .B2(_126_),
    .ZN(_127_)
  );
  XOR2_X1 _692_ (
    .A(first_span_q[2]),
    .B(_120_),
    .Z(_128_)
  );
  AOI21_X1 _693_ (
    .A(_121_),
    .B1(_127_),
    .B2(_128_),
    .ZN(_129_)
  );
  AOI21_X1 _694_ (
    .A(_117_),
    .B1(_129_),
    .B2(_116_),
    .ZN(_130_)
  );
  XOR2_X1 _695_ (
    .A(_112_),
    .B(_130_),
    .Z(_131_)
  );
  XNOR2_X1 _696_ (
    .A(_125_),
    .B(_126_),
    .ZN(_132_)
  );
  XNOR2_X1 _697_ (
    .A(_127_),
    .B(_128_),
    .ZN(_133_)
  );
  NAND2_X1 _698_ (
    .A1(_132_),
    .A2(_133_),
    .ZN(_134_)
  );
  NOR2_X1 _699_ (
    .A1(_115_),
    .A2(_117_),
    .ZN(_135_)
  );
  XNOR2_X1 _700_ (
    .A(_129_),
    .B(_135_),
    .ZN(_136_)
  );
  INV_X1 _701_ (
    .A(\u_scheduler.batch_index_q [4]),
    .ZN(_068_)
  );
  NAND3_X1 _702_ (
    .A1(\u_controller.u_stage_counter.stage_count [0]),
    .A2(_337_[1]),
    .A3(_337_[2]),
    .ZN(_137_)
  );
  AND2_X1 _703_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_337_[2]),
    .ZN(_138_)
  );
  OAI211_X1 _704_ (
    .A(\u_controller.u_stage_counter.stage_count [3]),
    .B(_137_),
    .C1(_138_),
    .C2(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_139_)
  );
  NAND3_X1 _705_ (
    .A1(_339_[2]),
    .A2(_339_[1]),
    .A3(first_span_q[0]),
    .ZN(_140_)
  );
  AOI21_X1 _706_ (
    .A(first_span_q[2]),
    .B1(_339_[2]),
    .B2(first_span_q[1]),
    .ZN(_141_)
  );
  NAND2_X1 _707_ (
    .A1(first_span_q[3]),
    .A2(_140_),
    .ZN(_142_)
  );
  OAI211_X1 _708_ (
    .A(_094_),
    .B(_139_),
    .C1(_141_),
    .C2(_142_),
    .ZN(_143_)
  );
  AOI21_X1 _709_ (
    .A(_143_),
    .B1(_136_),
    .B2(_134_),
    .ZN(_144_)
  );
  AOI211_X1 _710_ (
    .A(\u_controller.state [7]),
    .B(_108_),
    .C1(_131_),
    .C2(_144_),
    .ZN(_145_)
  );
  NOR3_X1 _711_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_010_),
    .ZN(_146_)
  );
  INV_X1 _712_ (
    .A(cfg_span_descending),
    .ZN(_069_)
  );
  OR3_X1 _713_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_010_),
    .ZN(_147_)
  );
  AOI221_X1 _714_ (
    .A(\u_scheduler.state [2]),
    .B1(\u_scheduler.state [1]),
    .B2(_010_),
    .C1(_009_),
    .C2(\u_scheduler.state [0]),
    .ZN(_148_)
  );
  NOR3_X1 _715_ (
    .A1(zeroize),
    .A2(_105_),
    .A3(zeroize_req),
    .ZN(_149_)
  );
  NAND2_X1 _716_ (
    .A1(_106_),
    .A2(_109_),
    .ZN(_150_)
  );
  AOI21_X1 _717_ (
    .A(_070_),
    .B1(_094_),
    .B2(_108_),
    .ZN(_151_)
  );
  AOI21_X1 _718_ (
    .A(_151_),
    .B1(_147_),
    .B2(batch_retired),
    .ZN(_152_)
  );
  OAI21_X1 _719_ (
    .A(_148_),
    .B1(_150_),
    .B2(_152_),
    .ZN(_153_)
  );
  OR3_X1 _720_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(_001_),
    .ZN(_154_)
  );
  OAI22_X1 _721_ (
    .A1(_145_),
    .A2(_153_),
    .B1(_154_),
    .B2(_148_),
    .ZN(_155_)
  );
  INV_X1 _722_ (
    .A(_155_),
    .ZN(_156_)
  );
  DFFS_X1 _723_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.state [0]),
    .QN(_012_),
    .SN(rst_n)
  );
  DFFR_X1 _724_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_controller.state [1]),
    .QN(_364_),
    .RN(rst_n)
  );
  DFFR_X1 _725_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.state [2]),
    .QN(_363_),
    .RN(rst_n)
  );
  DFFR_X1 _726_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_controller.state [3]),
    .QN(_362_),
    .RN(rst_n)
  );
  DFFR_X1 _727_ (
    .CK(clk),
    .D(_019_),
    .Q(\u_controller.state [4]),
    .QN(_361_),
    .RN(rst_n)
  );
  DFFR_X1 _728_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_controller.state [5]),
    .QN(_360_),
    .RN(rst_n)
  );
  DFFR_X1 _729_ (
    .CK(clk),
    .D(_020_),
    .Q(\u_controller.state [6]),
    .QN(_359_),
    .RN(rst_n)
  );
  DFFR_X1 _730_ (
    .CK(clk),
    .D(_021_),
    .Q(\u_controller.state [7]),
    .QN(_352_),
    .RN(rst_n)
  );
  DFFR_X1 _731_ (
    .CK(clk),
    .D(_045_),
    .Q(\u_scheduler.intt_q ),
    .QN(_351_),
    .RN(rst_n)
  );
  DFFR_X1 _732_ (
    .CK(clk),
    .D(_044_),
    .Q(\u_scheduler.span_q [0]),
    .QN(_011_),
    .RN(rst_n)
  );
  DFFR_X1 _733_ (
    .CK(clk),
    .D(_043_),
    .Q(\u_scheduler.span_q [1]),
    .QN(_353_),
    .RN(rst_n)
  );
  DFFR_X1 _734_ (
    .CK(clk),
    .D(_042_),
    .Q(\u_scheduler.span_q [2]),
    .QN(_354_),
    .RN(rst_n)
  );
  DFFR_X1 _735_ (
    .CK(clk),
    .D(_046_),
    .Q(\u_scheduler.span_q [3]),
    .QN(_350_),
    .RN(rst_n)
  );
  DFFR_X1 _736_ (
    .CK(clk),
    .D(_041_),
    .Q(\u_scheduler.stage_q [0]),
    .QN(_355_),
    .RN(rst_n)
  );
  DFFR_X1 _737_ (
    .CK(clk),
    .D(_040_),
    .Q(\u_scheduler.stage_q [1]),
    .QN(_356_),
    .RN(rst_n)
  );
  DFFR_X1 _738_ (
    .CK(clk),
    .D(_039_),
    .Q(\u_scheduler.stage_q [2]),
    .QN(_357_),
    .RN(rst_n)
  );
  DFFR_X1 _739_ (
    .CK(clk),
    .D(_047_),
    .Q(\u_scheduler.stage_q [3]),
    .QN(_349_),
    .RN(rst_n)
  );
  DFFR_X1 _740_ (
    .CK(clk),
    .D(_038_),
    .Q(\u_scheduler.batch_index_q [0]),
    .QN(_340_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _741_ (
    .CK(clk),
    .D(_037_),
    .Q(\u_scheduler.batch_index_q [1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _742_ (
    .CK(clk),
    .D(_036_),
    .Q(\u_scheduler.batch_index_q [2]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _743_ (
    .CK(clk),
    .D(_035_),
    .Q(\u_scheduler.batch_index_q [3]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _744_ (
    .CK(clk),
    .D(_034_),
    .Q(\u_scheduler.batch_index_q [4]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _745_ (
    .CK(clk),
    .D(_033_),
    .Q(\u_scheduler.batch_index_q [5]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _746_ (
    .CK(clk),
    .D(_032_),
    .Q(\u_scheduler.batch_index_q [6]),
    .QN(_007_),
    .RN(rst_n)
  );
  DFFR_X1 _747_ (
    .CK(clk),
    .D(_031_),
    .Q(\u_scheduler.batch_index_q [7]),
    .QN(_008_),
    .RN(rst_n)
  );
  DFFR_X1 _748_ (
    .CK(clk),
    .D(_048_),
    .Q(\u_scheduler.batch_index_q [8]),
    .QN(_013_),
    .RN(rst_n)
  );
  DFFR_X1 _749_ (
    .CK(clk),
    .D(_049_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_348_),
    .RN(rst_n)
  );
  DFFR_X1 _750_ (
    .CK(clk),
    .D(_050_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _751_ (
    .CK(clk),
    .D(_030_),
    .Q(\u_controller.u_stage_counter.last_stage_q [0]),
    .QN(_336_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _752_ (
    .CK(clk),
    .D(_029_),
    .Q(\u_controller.u_stage_counter.last_stage_q [1]),
    .QN(_336_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _753_ (
    .CK(clk),
    .D(_028_),
    .Q(\u_controller.u_stage_counter.last_stage_q [2]),
    .QN(_336_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _754_ (
    .CK(clk),
    .D(_051_),
    .Q(\u_controller.u_stage_counter.last_stage_q [3]),
    .QN(_336_[3]),
    .RN(rst_n)
  );
  DFFR_X1 _755_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_controller.u_stage_counter.stage_count [0]),
    .QN(_338_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _756_ (
    .CK(clk),
    .D(_026_),
    .Q(\u_controller.u_stage_counter.stage_count [1]),
    .QN(_337_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _757_ (
    .CK(clk),
    .D(_025_),
    .Q(\u_controller.u_stage_counter.stage_count [2]),
    .QN(_337_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _758_ (
    .CK(clk),
    .D(_052_),
    .Q(\u_controller.u_stage_counter.stage_count [3]),
    .QN(_365_[3]),
    .RN(rst_n)
  );
  DFFR_X1 _759_ (
    .CK(clk),
    .D(_053_),
    .Q(descending_q),
    .QN(_347_),
    .RN(rst_n)
  );
  DFFR_X1 _760_ (
    .CK(clk),
    .D(_024_),
    .Q(first_span_q[0]),
    .QN(_358_),
    .RN(rst_n)
  );
  DFFR_X1 _761_ (
    .CK(clk),
    .D(_023_),
    .Q(first_span_q[1]),
    .QN(_339_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _762_ (
    .CK(clk),
    .D(_022_),
    .Q(first_span_q[2]),
    .QN(_339_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _763_ (
    .CK(clk),
    .D(_054_),
    .Q(first_span_q[3]),
    .QN(_346_),
    .RN(rst_n)
  );
  DFFR_X1 _764_ (
    .CK(clk),
    .D(_055_),
    .Q(error_controller),
    .QN(_345_),
    .RN(rst_n)
  );
  DFFR_X1 _765_ (
    .CK(clk),
    .D(_056_),
    .Q(error_scheduler),
    .QN(_344_),
    .RN(rst_n)
  );
  DFFR_X1 _766_ (
    .CK(clk),
    .D(_057_),
    .Q(error_datapath),
    .QN(_343_),
    .RN(rst_n)
  );
  DFFR_X1 _767_ (
    .CK(clk),
    .D(_058_),
    .Q(error_ecc),
    .QN(_342_),
    .RN(rst_n)
  );
  DFFR_X1 _768_ (
    .CK(clk),
    .D(_059_),
    .Q(error_config),
    .QN(_341_),
    .RN(rst_n)
  );
  DFFR_X1 _769_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_009_),
    .RN(rst_n)
  );
  DFFR_X1 _770_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_010_),
    .RN(rst_n)
  );
  DFFR_X1 _771_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_001_),
    .RN(rst_n)
  );
  assign _340_[8:1] = \u_scheduler.batch_index_q [8:1];
  assign { _365_[4], _365_[2:0] } = { 1'h1, _337_[2:1], _338_[0] };
  assign { _337_[3], _337_[0] } = { \u_controller.u_stage_counter.stage_count [3], \u_controller.u_stage_counter.stage_count [0] };
  assign \u_scheduler.decode_lanes.ordinal  = { 1'h0, \u_scheduler.batch_index_q  };
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = \u_scheduler.batch_index_q ;
  assign \u_scheduler.coeff_addr_b  = coeff_addr_b;
  assign \u_scheduler.coeff_addr_a  = coeff_addr_a;
  assign \u_scheduler.lane_valid  = batch_valid;
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.next_state [3] = 1'h0;
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign { _339_[3], _339_[0] } = { first_span_q[3], first_span_q[0] };
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = \u_scheduler.batch_index_q ;
  assign lane_valid = batch_valid;
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
