/* Generated by Yosys 0.69+272 (git sha1 230fb23f8, Release, Clang /usr/bin/clang++ 21.1.8) */

module ntt_control(clk, rst_n, start, enable, intt_mode, cfg_last_stage, cfg_first_span_log2, cfg_span_descending, abort_req, zeroize, ecc_uncorrectable, datapath_fault, scrub_done, backend_flushed, ready, busy, done, zeroize_req, active, load_start, stage_start
, butterfly_enable, transform_abort, transform_intt, stage_count, batch_valid, batch_ready, lane_valid, coeff_addr_a, coeff_addr_b, butterfly_index, batch_stage, batch_span_log2, batch_intt, batch_retired, stage_done, scheduler_quiescent, error_config, error_ecc, error_datapath, error_scheduler, error_controller
);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input enable;
  wire enable;
  input intt_mode;
  wire intt_mode;
  input [2:0] cfg_last_stage;
  wire [2:0] cfg_last_stage;
  input [2:0] cfg_first_span_log2;
  wire [2:0] cfg_first_span_log2;
  input cfg_span_descending;
  wire cfg_span_descending;
  input abort_req;
  wire abort_req;
  input zeroize;
  wire zeroize;
  input ecc_uncorrectable;
  wire ecc_uncorrectable;
  input datapath_fault;
  wire datapath_fault;
  input scrub_done;
  wire scrub_done;
  input backend_flushed;
  wire backend_flushed;
  output ready;
  wire ready;
  output busy;
  wire busy;
  output done;
  wire done;
  output zeroize_req;
  wire zeroize_req;
  output active;
  wire active;
  output load_start;
  wire load_start;
  output stage_start;
  wire stage_start;
  output butterfly_enable;
  wire butterfly_enable;
  output transform_abort;
  wire transform_abort;
  output transform_intt;
  wire transform_intt;
  output [2:0] stage_count;
  wire [2:0] stage_count;
  output batch_valid;
  wire batch_valid;
  input batch_ready;
  wire batch_ready;
  output [1:0] lane_valid;
  wire [1:0] lane_valid;
  output [15:0] coeff_addr_a;
  wire [15:0] coeff_addr_a;
  output [15:0] coeff_addr_b;
  wire [15:0] coeff_addr_b;
  output [13:0] butterfly_index;
  wire [13:0] butterfly_index;
  output [2:0] batch_stage;
  wire [2:0] batch_stage;
  output [2:0] batch_span_log2;
  wire [2:0] batch_span_log2;
  output batch_intt;
  wire batch_intt;
  input batch_retired;
  wire batch_retired;
  output stage_done;
  wire stage_done;
  output scheduler_quiescent;
  wire scheduler_quiescent;
  output error_config;
  wire error_config;
  output error_ecc;
  wire error_ecc;
  output error_datapath;
  wire error_datapath;
  output error_scheduler;
  wire error_scheduler;
  output error_controller;
  wire error_controller;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire [2:0] _237_;
  wire [5:0] _238_;
  wire [2:0] _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire [2:0] _263_;
  wire descending_q;
  wire [2:0] first_span_q;
  wire range_valid;
  wire scheduler_fault;
  wire [5:0] \u_controller.a2b_cmd_opcode ;
  wire [4:0] \u_controller.a2b_context_id ;
  wire [3:0] \u_controller.a2b_profile_id ;
  wire \u_controller.a2b_start ;
  wire \u_controller.a2b_zeroize ;
  wire \u_controller.b2a_busy ;
  wire \u_controller.b2a_done ;
  wire [15:0] \u_controller.b2a_error_code ;
  wire \u_controller.b2a_ready ;
  wire \u_controller.butterfly_done ;
  wire \u_controller.butterfly_enable ;
  wire [2:0] \u_controller.cfg_last_stage ;
  wire \u_controller.cfg_valid ;
  wire \u_controller.clk ;
  wire \u_controller.intt_mode ;
  wire \u_controller.intt_mode_q ;
  wire [3:0] \u_controller.next_state ;
  wire \u_controller.ntt_active ;
  wire \u_controller.ntt_start ;
  wire \u_controller.rst_n ;
  wire [2:0] \u_controller.stage_count ;
  wire \u_controller.stage_done ;
  wire \u_controller.stage_start ;
  wire [7:0] \u_controller.state ;
  wire \u_controller.transform_abort ;
  wire \u_controller.transform_done ;
  wire \u_controller.transform_intt ;
  wire [2:0] \u_controller.u_stage_counter.cfg_last_stage ;
  wire \u_controller.u_stage_counter.cfg_valid ;
  wire \u_controller.u_stage_counter.clk ;
  wire [2:0] \u_controller.u_stage_counter.last_stage_q ;
  wire \u_controller.u_stage_counter.rst_n ;
  wire [2:0] \u_controller.u_stage_counter.stage_count ;
  wire \u_controller.zeroize_req ;
  wire \u_scheduler.backend_flushed ;
  wire [5:0] \u_scheduler.batch_index_q ;
  wire \u_scheduler.batch_intt ;
  wire \u_scheduler.batch_ready ;
  wire \u_scheduler.batch_retired ;
  wire [2:0] \u_scheduler.batch_span_log2 ;
  wire [2:0] \u_scheduler.batch_stage ;
  wire \u_scheduler.batch_valid ;
  wire \u_scheduler.butterfly_enable ;
  wire [13:0] \u_scheduler.butterfly_index ;
  wire \u_scheduler.clk ;
  wire [15:0] \u_scheduler.coeff_addr_a ;
  wire [15:0] \u_scheduler.coeff_addr_b ;
  wire [7:0] \u_scheduler.decode_lanes.ordinal ;
  wire [7:0] \u_scheduler.distance_mask ;
  wire \u_scheduler.fault_q ;
  wire \u_scheduler.intt_q ;
  wire [1:0] \u_scheduler.lane_valid ;
  wire [7:0] \u_scheduler.low_mask ;
  wire [2:0] \u_scheduler.next_state ;
  wire \u_scheduler.range_valid ;
  wire \u_scheduler.rst_n ;
  wire [2:0] \u_scheduler.schedule_first_span_log2 ;
  wire \u_scheduler.schedule_span_descending ;
  wire \u_scheduler.scheduler_fault ;
  wire \u_scheduler.scheduler_quiescent ;
  wire [2:0] \u_scheduler.span_q ;
  wire [2:0] \u_scheduler.stage_count ;
  wire \u_scheduler.stage_done ;
  wire [2:0] \u_scheduler.stage_q ;
  wire \u_scheduler.stage_start ;
  wire [2:0] \u_scheduler.state ;
  wire \u_scheduler.transform_intt ;
  wire \u_scheduler.zeroize ;
  wire \u_scheduler.zeroize_req ;
  INV_X1 _264_ (
    .A(cfg_last_stage[2]),
    .ZN(_049_)
  );
  INV_X1 _265_ (
    .A(cfg_span_descending),
    .ZN(_050_)
  );
  INV_X1 _266_ (
    .A(_009_),
    .ZN(_059_)
  );
  OAI21_X1 _267_ (
    .A(_138_),
    .B1(_141_),
    .B2(cfg_span_descending),
    .ZN(_142_)
  );
  NOR4_X1 _268_ (
    .A1(backend_flushed),
    .A2(_060_),
    .A3(_135_),
    .A4(_142_),
    .ZN(_143_)
  );
  AND2_X1 _269_ (
    .A1(scheduler_quiescent),
    .A2(_143_),
    .ZN(ready)
  );
  NOR2_X1 _270_ (
    .A1(_051_),
    .A2(_059_),
    .ZN(busy)
  );
  NAND2_X1 _271_ (
    .A1(\u_controller.state [5]),
    .A2(_102_),
    .ZN(_144_)
  );
  NOR2_X1 _272_ (
    .A1(_051_),
    .A2(_144_),
    .ZN(done)
  );
  NAND2_X1 _273_ (
    .A1(backend_flushed),
    .A2(_091_),
    .ZN(_145_)
  );
  NAND2_X1 _274_ (
    .A1(\u_scheduler.fault_q ),
    .A2(_145_),
    .ZN(_146_)
  );
  NAND2_X1 _275_ (
    .A1(_127_),
    .A2(_146_),
    .ZN(_048_)
  );
  NAND2_X1 _276_ (
    .A1(start),
    .A2(ready),
    .ZN(_147_)
  );
  INV_X1 _277_ (
    .A(\u_controller.state [0]),
    .ZN(_060_)
  );
  INV_X1 _278_ (
    .A(_147_),
    .ZN(_016_)
  );
  NAND2_X1 _279_ (
    .A1(error_config),
    .A2(_147_),
    .ZN(_148_)
  );
  NAND4_X1 _280_ (
    .A1(rst_n),
    .A2(start),
    .A3(_059_),
    .A4(_142_),
    .ZN(_149_)
  );
  OAI21_X1 _281_ (
    .A(_148_),
    .B1(_149_),
    .B2(_135_),
    .ZN(_047_)
  );
  AOI21_X1 _282_ (
    .A(ecc_uncorrectable),
    .B1(error_ecc),
    .B2(_147_),
    .ZN(_150_)
  );
  INV_X1 _283_ (
    .A(_150_),
    .ZN(_046_)
  );
  AOI21_X1 _284_ (
    .A(datapath_fault),
    .B1(error_datapath),
    .B2(_147_),
    .ZN(_151_)
  );
  INV_X1 _285_ (
    .A(_151_),
    .ZN(_045_)
  );
  AOI21_X1 _286_ (
    .A(\u_scheduler.fault_q ),
    .B1(error_scheduler),
    .B2(_147_),
    .ZN(_152_)
  );
  INV_X1 _287_ (
    .A(_152_),
    .ZN(_044_)
  );
  INV_X1 _288_ (
    .A(\u_controller.state [7]),
    .ZN(_061_)
  );
  AOI21_X1 _289_ (
    .A(_098_),
    .B1(_147_),
    .B2(error_controller),
    .ZN(_153_)
  );
  INV_X1 _290_ (
    .A(_153_),
    .ZN(_043_)
  );
  NAND2_X1 _291_ (
    .A1(_123_),
    .A2(_147_),
    .ZN(_154_)
  );
  OAI22_X1 _292_ (
    .A1(_056_),
    .A2(_147_),
    .B1(_154_),
    .B2(_052_),
    .ZN(_042_)
  );
  OAI22_X1 _293_ (
    .A1(_050_),
    .A2(_147_),
    .B1(_154_),
    .B2(_053_),
    .ZN(_041_)
  );
  AND2_X1 _294_ (
    .A1(_097_),
    .A2(_147_),
    .ZN(_155_)
  );
  NAND2_X1 _295_ (
    .A1(\u_controller.state [6]),
    .A2(_102_),
    .ZN(_156_)
  );
  OR2_X1 _296_ (
    .A1(stage_done),
    .A2(_156_),
    .ZN(_157_)
  );
  AND2_X1 _297_ (
    .A1(_103_),
    .A2(_157_),
    .ZN(_158_)
  );
  INV_X1 _298_ (
    .A(_158_),
    .ZN(_017_)
  );
  INV_X1 _299_ (
    .A(\u_controller.u_stage_counter.last_stage_q [0]),
    .ZN(_062_)
  );
  NOR2_X1 _300_ (
    .A1(_094_),
    .A2(_101_),
    .ZN(_159_)
  );
  NOR3_X1 _301_ (
    .A1(zeroize),
    .A2(_061_),
    .A3(_159_),
    .ZN(_160_)
  );
  NAND3_X1 _302_ (
    .A1(scrub_done),
    .A2(_100_),
    .A3(scheduler_quiescent),
    .ZN(_161_)
  );
  NAND2_X1 _303_ (
    .A1(_160_),
    .A2(_161_),
    .ZN(_162_)
  );
  NOR3_X1 _304_ (
    .A1(zeroize),
    .A2(_094_),
    .A3(_101_),
    .ZN(_012_)
  );
  XNOR2_X1 _305_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .B(_237_[2]),
    .ZN(_163_)
  );
  INV_X1 _306_ (
    .A(_163_),
    .ZN(_164_)
  );
  NAND3_X1 _307_ (
    .A1(\u_controller.u_stage_counter.stage_count [1]),
    .A2(_237_[1]),
    .A3(_164_),
    .ZN(_165_)
  );
  NOR2_X1 _308_ (
    .A1(zeroize),
    .A2(\u_controller.state [3]),
    .ZN(_166_)
  );
  AOI211_X1 _309_ (
    .A(zeroize),
    .B(\u_controller.state [3]),
    .C1(\u_controller.u_stage_counter.stage_count [2]),
    .C2(_237_[2]),
    .ZN(_167_)
  );
  INV_X1 _310_ (
    .A(\u_scheduler.batch_index_q [5]),
    .ZN(_063_)
  );
  OAI221_X1 _311_ (
    .A(_164_),
    .B1(_237_[1]),
    .B2(\u_controller.u_stage_counter.stage_count [1]),
    .C1(\u_controller.u_stage_counter.stage_count [0]),
    .C2(_237_[0]),
    .ZN(_168_)
  );
  NAND4_X1 _312_ (
    .A1(\u_controller.state [1]),
    .A2(_165_),
    .A3(_167_),
    .A4(_168_),
    .ZN(_169_)
  );
  NOR3_X1 _313_ (
    .A1(_011_),
    .A2(_012_),
    .A3(_169_),
    .ZN(_170_)
  );
  NAND4_X1 _314_ (
    .A1(_147_),
    .A2(_158_),
    .A3(_162_),
    .A4(_170_),
    .ZN(_171_)
  );
  OR3_X1 _315_ (
    .A1(_071_),
    .A2(_072_),
    .A3(_171_),
    .ZN(_172_)
  );
  AOI221_X1 _316_ (
    .A(_168_),
    .B1(_237_[1]),
    .B2(\u_controller.u_stage_counter.stage_count [1]),
    .C1(\u_controller.u_stage_counter.stage_count [0]),
    .C2(_237_[0]),
    .ZN(_173_)
  );
  NAND2_X1 _317_ (
    .A1(\u_controller.state [1]),
    .A2(_102_),
    .ZN(_174_)
  );
  AOI221_X1 _318_ (
    .A(_016_),
    .B1(_172_),
    .B2(_054_),
    .C1(_060_),
    .C2(_096_),
    .ZN(_040_)
  );
  NOR2_X1 _319_ (
    .A1(\u_controller.u_stage_counter.last_stage_q [2]),
    .A2(_016_),
    .ZN(_175_)
  );
  AOI221_X1 _320_ (
    .A(_175_),
    .B1(_096_),
    .B2(_060_),
    .C1(_049_),
    .C2(_016_),
    .ZN(_039_)
  );
  INV_X1 _321_ (
    .A(\u_controller.intt_mode_q ),
    .ZN(_064_)
  );
  NAND3_X1 _322_ (
    .A1(\u_controller.state [6]),
    .A2(_089_),
    .A3(_124_),
    .ZN(_176_)
  );
  NOR4_X1 _323_ (
    .A1(_092_),
    .A2(_126_),
    .A3(_128_),
    .A4(_176_),
    .ZN(batch_valid)
  );
  AND2_X1 _324_ (
    .A1(\u_controller.state [6]),
    .A2(rst_n),
    .ZN(butterfly_enable)
  );
  NAND2_X1 _325_ (
    .A1(\u_controller.state [4]),
    .A2(_102_),
    .ZN(_177_)
  );
  NOR2_X1 _326_ (
    .A1(_051_),
    .A2(_177_),
    .ZN(load_start)
  );
  NOR2_X1 _327_ (
    .A1(_051_),
    .A2(_096_),
    .ZN(active)
  );
  NAND2_X1 _328_ (
    .A1(_162_),
    .A2(_166_),
    .ZN(_018_)
  );
  OAI21_X1 _329_ (
    .A(_097_),
    .B1(_147_),
    .B2(intt_mode),
    .ZN(_178_)
  );
  AOI21_X1 _330_ (
    .A(_178_),
    .B1(_147_),
    .B2(_064_),
    .ZN(_038_)
  );
  NAND2_X1 _331_ (
    .A1(_000_),
    .A2(_084_),
    .ZN(_179_)
  );
  INV_X1 _332_ (
    .A(\u_scheduler.stage_q [2]),
    .ZN(_065_)
  );
  OR3_X1 _333_ (
    .A1(_095_),
    .A2(_103_),
    .A3(_179_),
    .ZN(_180_)
  );
  OR3_X1 _334_ (
    .A1(_092_),
    .A2(_126_),
    .A3(_180_),
    .ZN(_181_)
  );
  NAND3_X1 _335_ (
    .A1(\u_scheduler.state [0]),
    .A2(_089_),
    .A3(_124_),
    .ZN(_182_)
  );
  AOI21_X1 _336_ (
    .A(_182_),
    .B1(batch_valid),
    .B2(batch_ready),
    .ZN(_183_)
  );
  NAND3_X1 _337_ (
    .A1(batch_retired),
    .A2(_087_),
    .A3(_124_),
    .ZN(_184_)
  );
  NAND2_X1 _338_ (
    .A1(_180_),
    .A2(_184_),
    .ZN(_185_)
  );
  OAI21_X1 _339_ (
    .A(_127_),
    .B1(_183_),
    .B2(_185_),
    .ZN(_186_)
  );
  INV_X1 _340_ (
    .A(_186_),
    .ZN(\u_scheduler.next_state [0])
  );
  AND3_X1 _341_ (
    .A1(\u_scheduler.state [1]),
    .A2(_124_),
    .A3(_130_),
    .ZN(_187_)
  );
  NOR3_X1 _342_ (
    .A1(_004_),
    .A2(_005_),
    .A3(_010_),
    .ZN(_188_)
  );
  INV_X1 _343_ (
    .A(\u_scheduler.span_q [2]),
    .ZN(_066_)
  );
  NOR4_X1 _344_ (
    .A1(_055_),
    .A2(_238_[0]),
    .A3(_002_),
    .A4(_003_),
    .ZN(_189_)
  );
  AND4_X1 _345_ (
    .A1(_087_),
    .A2(_124_),
    .A3(_188_),
    .A4(_189_),
    .ZN(_190_)
  );
  OR2_X1 _346_ (
    .A1(_187_),
    .A2(_190_),
    .ZN(_191_)
  );
  AOI21_X1 _347_ (
    .A(_191_),
    .B1(batch_valid),
    .B2(batch_ready),
    .ZN(_192_)
  );
  NAND4_X1 _348_ (
    .A1(_127_),
    .A2(_134_),
    .A3(_186_),
    .A4(_192_),
    .ZN(_193_)
  );
  NAND2_X1 _349_ (
    .A1(_181_),
    .A2(_193_),
    .ZN(_194_)
  );
  AOI211_X1 _350_ (
    .A(_088_),
    .B(_191_),
    .C1(batch_valid),
    .C2(batch_ready),
    .ZN(_195_)
  );
  OAI211_X1 _351_ (
    .A(_127_),
    .B(_195_),
    .C1(_185_),
    .C2(_183_),
    .ZN(_196_)
  );
  NOR2_X1 _352_ (
    .A1(_075_),
    .A2(_196_),
    .ZN(_197_)
  );
  NOR2_X1 _353_ (
    .A1(_074_),
    .A2(_076_),
    .ZN(_198_)
  );
  INV_X1 _354_ (
    .A(\u_scheduler.intt_q ),
    .ZN(_067_)
  );
  NOR3_X1 _355_ (
    .A1(_073_),
    .A2(_074_),
    .A3(_076_),
    .ZN(_199_)
  );
  NAND2_X1 _356_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_198_),
    .ZN(_200_)
  );
  NOR4_X1 _357_ (
    .A1(_075_),
    .A2(_077_),
    .A3(_196_),
    .A4(_200_),
    .ZN(_201_)
  );
  XNOR2_X1 _358_ (
    .A(\u_scheduler.batch_index_q [5]),
    .B(_201_),
    .ZN(_202_)
  );
  NOR2_X1 _359_ (
    .A1(_194_),
    .A2(_202_),
    .ZN(_037_)
  );
  OAI22_X1 _360_ (
    .A1(_054_),
    .A2(_181_),
    .B1(_194_),
    .B2(_065_),
    .ZN(_036_)
  );
  XNOR2_X1 _361_ (
    .A(_115_),
    .B(_116_),
    .ZN(_203_)
  );
  OAI22_X1 _362_ (
    .A1(_066_),
    .A2(_194_),
    .B1(_203_),
    .B2(_181_),
    .ZN(_035_)
  );
  OAI22_X1 _363_ (
    .A1(_064_),
    .A2(_181_),
    .B1(_194_),
    .B2(_067_),
    .ZN(_034_)
  );
  AND3_X1 _364_ (
    .A1(\u_controller.state [1]),
    .A2(_102_),
    .A3(_173_),
    .ZN(_013_)
  );
  INV_X1 _365_ (
    .A(\u_scheduler.span_q [0]),
    .ZN(_068_)
  );
  NAND2_X1 _366_ (
    .A1(\u_scheduler.span_q [1]),
    .A2(_008_),
    .ZN(_204_)
  );
  NOR2_X1 _367_ (
    .A1(_068_),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_205_)
  );
  NAND2_X1 _368_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(_069_),
    .ZN(_206_)
  );
  NOR2_X1 _369_ (
    .A1(_066_),
    .A2(_206_),
    .ZN(_207_)
  );
  NAND3_X1 _370_ (
    .A1(\u_scheduler.span_q [2]),
    .A2(_069_),
    .A3(_008_),
    .ZN(_208_)
  );
  NAND2_X1 _371_ (
    .A1(\u_scheduler.span_q [0]),
    .A2(\u_scheduler.span_q [1]),
    .ZN(_209_)
  );
  NOR2_X1 _372_ (
    .A1(\u_scheduler.span_q [2]),
    .A2(_209_),
    .ZN(_210_)
  );
  NAND3_X1 _373_ (
    .A1(_066_),
    .A2(_069_),
    .A3(_008_),
    .ZN(coeff_addr_a[8])
  );
  INV_X1 _374_ (
    .A(coeff_addr_a[8]),
    .ZN(coeff_addr_b[0])
  );
  OAI21_X1 _375_ (
    .A(coeff_addr_a[8]),
    .B1(_206_),
    .B2(\u_scheduler.span_q [2]),
    .ZN(_211_)
  );
  INV_X1 _376_ (
    .A(rst_n),
    .ZN(_051_)
  );
  INV_X1 _377_ (
    .A(\u_scheduler.span_q [1]),
    .ZN(_069_)
  );
  OAI21_X1 _378_ (
    .A(_066_),
    .B1(_008_),
    .B2(_205_),
    .ZN(_212_)
  );
  OAI21_X1 _379_ (
    .A(_066_),
    .B1(\u_scheduler.span_q [0]),
    .B2(_008_),
    .ZN(_213_)
  );
  NAND2_X1 _380_ (
    .A1(_208_),
    .A2(_213_),
    .ZN(_214_)
  );
  OR3_X1 _381_ (
    .A1(_008_),
    .A2(_205_),
    .A3(_210_),
    .ZN(_215_)
  );
  NAND2_X1 _382_ (
    .A1(\u_scheduler.batch_index_q [5]),
    .A2(_215_),
    .ZN(_216_)
  );
  INV_X1 _383_ (
    .A(_216_),
    .ZN(coeff_addr_a[7])
  );
  OAI21_X1 _384_ (
    .A(_211_),
    .B1(coeff_addr_a[8]),
    .B2(_068_),
    .ZN(_217_)
  );
  NAND2_X1 _385_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_217_),
    .ZN(_218_)
  );
  INV_X1 _386_ (
    .A(_218_),
    .ZN(coeff_addr_a[1])
  );
  NAND2_X1 _387_ (
    .A1(coeff_addr_a[8]),
    .A2(_218_),
    .ZN(coeff_addr_a[9])
  );
  INV_X1 _388_ (
    .A(cfg_last_stage[1]),
    .ZN(_070_)
  );
  OAI21_X1 _389_ (
    .A(_216_),
    .B1(_209_),
    .B2(_066_),
    .ZN(coeff_addr_b[7])
  );
  OR4_X1 _390_ (
    .A1(zeroize),
    .A2(_060_),
    .A3(_016_),
    .A4(_159_),
    .ZN(_219_)
  );
  NAND4_X1 _391_ (
    .A1(scrub_done),
    .A2(_100_),
    .A3(scheduler_quiescent),
    .A4(_160_),
    .ZN(_220_)
  );
  NAND3_X1 _392_ (
    .A1(_144_),
    .A2(_219_),
    .A3(_220_),
    .ZN(_014_)
  );
  OAI21_X1 _393_ (
    .A(_177_),
    .B1(_174_),
    .B2(_173_),
    .ZN(_015_)
  );
  OAI21_X1 _394_ (
    .A(_218_),
    .B1(_206_),
    .B2(\u_scheduler.span_q [2]),
    .ZN(coeff_addr_b[1])
  );
  NAND2_X1 _395_ (
    .A1(\u_scheduler.batch_index_q [1]),
    .A2(_212_),
    .ZN(_221_)
  );
  OAI21_X1 _396_ (
    .A(_221_),
    .B1(_217_),
    .B2(_075_),
    .ZN(coeff_addr_a[2])
  );
  AOI21_X1 _397_ (
    .A(_213_),
    .B1(_210_),
    .B2(_008_),
    .ZN(_222_)
  );
  OAI22_X1 _398_ (
    .A1(_076_),
    .A2(_212_),
    .B1(_222_),
    .B2(_074_),
    .ZN(coeff_addr_a[3])
  );
  INV_X1 _399_ (
    .A(\u_controller.u_stage_counter.stage_count [0]),
    .ZN(_071_)
  );
  NAND2_X1 _400_ (
    .A1(\u_scheduler.batch_index_q [2]),
    .A2(_222_),
    .ZN(_223_)
  );
  OAI21_X1 _401_ (
    .A(_223_),
    .B1(_214_),
    .B2(_073_),
    .ZN(coeff_addr_a[4])
  );
  OAI22_X1 _402_ (
    .A1(_068_),
    .A2(_208_),
    .B1(_214_),
    .B2(_207_),
    .ZN(_224_)
  );
  AOI22_X1 _403_ (
    .A1(\u_scheduler.batch_index_q [3]),
    .A2(_214_),
    .B1(_224_),
    .B2(\u_scheduler.batch_index_q [4]),
    .ZN(_225_)
  );
  INV_X1 _404_ (
    .A(_225_),
    .ZN(coeff_addr_a[5])
  );
  OAI22_X1 _405_ (
    .A1(_063_),
    .A2(_215_),
    .B1(_224_),
    .B2(_077_),
    .ZN(coeff_addr_a[6])
  );
  XOR2_X1 _406_ (
    .A(first_span_q[0]),
    .B(_239_[0]),
    .Z(_226_)
  );
  OAI22_X1 _407_ (
    .A1(_068_),
    .A2(_194_),
    .B1(_226_),
    .B2(_181_),
    .ZN(_033_)
  );
  XNOR2_X1 _408_ (
    .A(_113_),
    .B(_114_),
    .ZN(_227_)
  );
  OAI22_X1 _409_ (
    .A1(_069_),
    .A2(_194_),
    .B1(_227_),
    .B2(_181_),
    .ZN(_032_)
  );
  INV_X1 _410_ (
    .A(\u_controller.u_stage_counter.stage_count [1]),
    .ZN(_072_)
  );
  OAI22_X1 _411_ (
    .A1(_071_),
    .A2(_181_),
    .B1(_194_),
    .B2(_081_),
    .ZN(_031_)
  );
  OAI22_X1 _412_ (
    .A1(_072_),
    .A2(_181_),
    .B1(_194_),
    .B2(_082_),
    .ZN(_030_)
  );
  NOR2_X1 _413_ (
    .A1(_238_[0]),
    .A2(_196_),
    .ZN(_228_)
  );
  AOI211_X1 _414_ (
    .A(_194_),
    .B(_228_),
    .C1(_196_),
    .C2(_075_),
    .ZN(_029_)
  );
  OAI211_X1 _415_ (
    .A(_181_),
    .B(_193_),
    .C1(_197_),
    .C2(\u_scheduler.batch_index_q [1]),
    .ZN(_229_)
  );
  AOI21_X1 _416_ (
    .A(_229_),
    .B1(_197_),
    .B2(\u_scheduler.batch_index_q [1]),
    .ZN(_028_)
  );
  AOI21_X1 _417_ (
    .A(\u_scheduler.batch_index_q [2]),
    .B1(\u_scheduler.batch_index_q [1]),
    .B2(_197_),
    .ZN(_230_)
  );
  AOI211_X1 _418_ (
    .A(_194_),
    .B(_230_),
    .C1(_198_),
    .C2(_197_),
    .ZN(_027_)
  );
  AOI21_X1 _419_ (
    .A(\u_scheduler.batch_index_q [3]),
    .B1(_197_),
    .B2(_198_),
    .ZN(_231_)
  );
  AOI211_X1 _420_ (
    .A(_194_),
    .B(_231_),
    .C1(_199_),
    .C2(_197_),
    .ZN(_026_)
  );
  INV_X1 _421_ (
    .A(\u_scheduler.batch_index_q [3]),
    .ZN(_073_)
  );
  AOI21_X1 _422_ (
    .A(\u_scheduler.batch_index_q [4]),
    .B1(_197_),
    .B2(_199_),
    .ZN(_232_)
  );
  NOR3_X1 _423_ (
    .A1(_194_),
    .A2(_201_),
    .A3(_232_),
    .ZN(_025_)
  );
  OAI21_X1 _424_ (
    .A(_097_),
    .B1(_147_),
    .B2(cfg_last_stage[0]),
    .ZN(_233_)
  );
  AOI21_X1 _425_ (
    .A(_233_),
    .B1(_147_),
    .B2(_062_),
    .ZN(_024_)
  );
  NOR2_X1 _426_ (
    .A1(\u_controller.u_stage_counter.last_stage_q [1]),
    .A2(_016_),
    .ZN(_234_)
  );
  AOI221_X1 _427_ (
    .A(_234_),
    .B1(_016_),
    .B2(_070_),
    .C1(_060_),
    .C2(_096_),
    .ZN(_023_)
  );
  MUX2_X1 _428_ (
    .A(_239_[0]),
    .B(\u_controller.u_stage_counter.stage_count [0]),
    .S(_171_),
    .Z(_235_)
  );
  AND2_X1 _429_ (
    .A1(_155_),
    .A2(_235_),
    .ZN(_022_)
  );
  OAI21_X1 _430_ (
    .A(_072_),
    .B1(_171_),
    .B2(_071_),
    .ZN(_236_)
  );
  AND3_X1 _431_ (
    .A1(_155_),
    .A2(_172_),
    .A3(_236_),
    .ZN(_021_)
  );
  INV_X1 _432_ (
    .A(\u_scheduler.batch_index_q [2]),
    .ZN(_074_)
  );
  OAI22_X1 _433_ (
    .A1(_079_),
    .A2(_147_),
    .B1(_154_),
    .B2(_057_),
    .ZN(_020_)
  );
  OAI22_X1 _434_ (
    .A1(_080_),
    .A2(_147_),
    .B1(_154_),
    .B2(_078_),
    .ZN(_019_)
  );
  NOR3_X1 _435_ (
    .A1(_092_),
    .A2(_126_),
    .A3(_192_),
    .ZN(\u_scheduler.next_state [1])
  );
  OR2_X1 _436_ (
    .A1(\u_scheduler.batch_index_q [0]),
    .A2(_211_),
    .ZN(coeff_addr_b[9])
  );
  OAI221_X1 _437_ (
    .A(_221_),
    .B1(_217_),
    .B2(_075_),
    .C1(\u_scheduler.span_q [2]),
    .C2(_204_),
    .ZN(coeff_addr_b[2])
  );
  OR2_X1 _438_ (
    .A1(_210_),
    .A2(coeff_addr_a[3]),
    .ZN(coeff_addr_b[3])
  );
  OAI211_X1 _439_ (
    .A(_208_),
    .B(_223_),
    .C1(_214_),
    .C2(_073_),
    .ZN(coeff_addr_b[4])
  );
  OAI21_X1 _440_ (
    .A(_225_),
    .B1(_206_),
    .B2(_066_),
    .ZN(coeff_addr_b[5])
  );
  OAI222_X1 _441_ (
    .A1(_066_),
    .A2(_204_),
    .B1(_224_),
    .B2(_077_),
    .C1(_215_),
    .C2(_063_),
    .ZN(coeff_addr_b[6])
  );
  INV_X1 _442_ (
    .A(\u_scheduler.batch_index_q [0]),
    .ZN(_075_)
  );
  INV_X1 _443_ (
    .A(\u_scheduler.batch_index_q [1]),
    .ZN(_076_)
  );
  INV_X1 _444_ (
    .A(\u_scheduler.batch_index_q [4]),
    .ZN(_077_)
  );
  INV_X1 _445_ (
    .A(first_span_q[1]),
    .ZN(_078_)
  );
  INV_X1 _446_ (
    .A(first_span_q[2]),
    .ZN(_052_)
  );
  INV_X1 _447_ (
    .A(cfg_first_span_log2[0]),
    .ZN(_079_)
  );
  INV_X1 _448_ (
    .A(cfg_first_span_log2[1]),
    .ZN(_080_)
  );
  INV_X1 _449_ (
    .A(\u_scheduler.stage_q [0]),
    .ZN(_081_)
  );
  INV_X1 _450_ (
    .A(\u_scheduler.stage_q [1]),
    .ZN(_082_)
  );
  NOR3_X1 _451_ (
    .A1(\u_scheduler.state [2]),
    .A2(_007_),
    .A3(_006_),
    .ZN(_083_)
  );
  NOR3_X1 _452_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(\u_scheduler.state [1]),
    .ZN(_084_)
  );
  OR3_X1 _453_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(\u_scheduler.state [1]),
    .ZN(_085_)
  );
  NOR2_X1 _454_ (
    .A1(_083_),
    .A2(_084_),
    .ZN(_086_)
  );
  NOR3_X1 _455_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_007_),
    .ZN(_087_)
  );
  OR3_X1 _456_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [0]),
    .A3(_007_),
    .ZN(_088_)
  );
  INV_X1 _457_ (
    .A(descending_q),
    .ZN(_053_)
  );
  NOR3_X1 _458_ (
    .A1(\u_scheduler.state [2]),
    .A2(\u_scheduler.state [1]),
    .A3(_006_),
    .ZN(_089_)
  );
  AOI221_X1 _459_ (
    .A(\u_scheduler.state [2]),
    .B1(_007_),
    .B2(\u_scheduler.state [1]),
    .C1(_006_),
    .C2(\u_scheduler.state [0]),
    .ZN(_090_)
  );
  NOR3_X1 _460_ (
    .A1(\u_scheduler.state [0]),
    .A2(\u_scheduler.state [1]),
    .A3(_001_),
    .ZN(_091_)
  );
  NOR2_X1 _461_ (
    .A1(_090_),
    .A2(_091_),
    .ZN(_092_)
  );
  OR3_X1 _462_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .A3(\u_controller.state [5]),
    .ZN(_093_)
  );
  NOR3_X1 _463_ (
    .A1(\u_controller.state [4]),
    .A2(\u_controller.state [2]),
    .A3(_093_),
    .ZN(_094_)
  );
  NAND2_X1 _464_ (
    .A1(rst_n),
    .A2(_061_),
    .ZN(_095_)
  );
  NOR4_X1 _465_ (
    .A1(\u_controller.state [6]),
    .A2(\u_controller.state [1]),
    .A3(\u_controller.state [4]),
    .A4(\u_controller.state [2]),
    .ZN(_096_)
  );
  NAND2_X1 _466_ (
    .A1(_060_),
    .A2(_096_),
    .ZN(_097_)
  );
  NOR3_X1 _467_ (
    .A1(\u_controller.state [5]),
    .A2(_095_),
    .A3(_097_),
    .ZN(transform_abort)
  );
  INV_X1 _468_ (
    .A(\u_controller.u_stage_counter.stage_count [2]),
    .ZN(_054_)
  );
  NOR4_X1 _469_ (
    .A1(\u_controller.state [3]),
    .A2(\u_controller.state [5]),
    .A3(_095_),
    .A4(_097_),
    .ZN(_098_)
  );
  OR3_X1 _470_ (
    .A1(ecc_uncorrectable),
    .A2(datapath_fault),
    .A3(\u_scheduler.fault_q ),
    .ZN(_099_)
  );
  NOR2_X1 _471_ (
    .A1(_098_),
    .A2(_099_),
    .ZN(_100_)
  );
  NOR3_X1 _472_ (
    .A1(abort_req),
    .A2(_098_),
    .A3(_099_),
    .ZN(_101_)
  );
  NOR4_X1 _473_ (
    .A1(abort_req),
    .A2(zeroize),
    .A3(_098_),
    .A4(_099_),
    .ZN(_102_)
  );
  NAND2_X1 _474_ (
    .A1(\u_controller.state [2]),
    .A2(_102_),
    .ZN(_103_)
  );
  AND3_X1 _475_ (
    .A1(rst_n),
    .A2(\u_controller.state [2]),
    .A3(_102_),
    .ZN(stage_start)
  );
  AND2_X1 _476_ (
    .A1(_239_[0]),
    .A2(_263_[1]),
    .ZN(_104_)
  );
  AOI21_X1 _477_ (
    .A(descending_q),
    .B1(_239_[0]),
    .B2(_263_[1]),
    .ZN(_105_)
  );
  AOI21_X1 _478_ (
    .A(descending_q),
    .B1(_263_[2]),
    .B2(_104_),
    .ZN(_106_)
  );
  INV_X1 _479_ (
    .A(batch_retired),
    .ZN(_055_)
  );
  OR2_X1 _480_ (
    .A1(_263_[2]),
    .A2(_104_),
    .ZN(_107_)
  );
  AOI22_X1 _481_ (
    .A1(descending_q),
    .A2(\u_controller.u_stage_counter.stage_count [2]),
    .B1(_106_),
    .B2(_107_),
    .ZN(_108_)
  );
  AND2_X1 _482_ (
    .A1(first_span_q[2]),
    .A2(_108_),
    .ZN(_109_)
  );
  OR2_X1 _483_ (
    .A1(_239_[0]),
    .A2(_263_[1]),
    .ZN(_110_)
  );
  AOI22_X1 _484_ (
    .A1(descending_q),
    .A2(\u_controller.u_stage_counter.stage_count [1]),
    .B1(_105_),
    .B2(_110_),
    .ZN(_111_)
  );
  NAND2_X1 _485_ (
    .A1(first_span_q[1]),
    .A2(_111_),
    .ZN(_112_)
  );
  NOR2_X1 _486_ (
    .A1(first_span_q[0]),
    .A2(_239_[0]),
    .ZN(_113_)
  );
  XNOR2_X1 _487_ (
    .A(first_span_q[1]),
    .B(_111_),
    .ZN(_114_)
  );
  OAI21_X1 _488_ (
    .A(_112_),
    .B1(_113_),
    .B2(_114_),
    .ZN(_115_)
  );
  XNOR2_X1 _489_ (
    .A(_052_),
    .B(_108_),
    .ZN(_116_)
  );
  INV_X1 _490_ (
    .A(cfg_first_span_log2[2]),
    .ZN(_056_)
  );
  AOI21_X1 _491_ (
    .A(_109_),
    .B1(_115_),
    .B2(_116_),
    .ZN(_117_)
  );
  XOR2_X1 _492_ (
    .A(_106_),
    .B(_117_),
    .Z(_118_)
  );
  OAI21_X1 _493_ (
    .A(stage_start),
    .B1(_118_),
    .B2(_085_),
    .ZN(_119_)
  );
  OAI21_X1 _494_ (
    .A(backend_flushed),
    .B1(_085_),
    .B2(stage_start),
    .ZN(_120_)
  );
  NAND2_X1 _495_ (
    .A1(batch_retired),
    .A2(_088_),
    .ZN(_121_)
  );
  AND2_X1 _496_ (
    .A1(_120_),
    .A2(_121_),
    .ZN(_122_)
  );
  NAND2_X1 _497_ (
    .A1(rst_n),
    .A2(\u_controller.state [7]),
    .ZN(_123_)
  );
  INV_X1 _498_ (
    .A(_123_),
    .ZN(zeroize_req)
  );
  AND2_X1 _499_ (
    .A1(_102_),
    .A2(_123_),
    .ZN(_124_)
  );
  NAND2_X1 _500_ (
    .A1(_090_),
    .A2(_124_),
    .ZN(_125_)
  );
  INV_X1 _501_ (
    .A(first_span_q[0]),
    .ZN(_057_)
  );
  AOI21_X1 _502_ (
    .A(_125_),
    .B1(_122_),
    .B2(_119_),
    .ZN(_126_)
  );
  NOR2_X1 _503_ (
    .A1(_092_),
    .A2(_126_),
    .ZN(_127_)
  );
  NAND2_X1 _504_ (
    .A1(rst_n),
    .A2(_000_),
    .ZN(_128_)
  );
  NAND2_X1 _505_ (
    .A1(_083_),
    .A2(_124_),
    .ZN(_129_)
  );
  NOR4_X1 _506_ (
    .A1(_092_),
    .A2(_126_),
    .A3(_128_),
    .A4(_129_),
    .ZN(stage_done)
  );
  AND2_X1 _507_ (
    .A1(\u_controller.state [6]),
    .A2(stage_done),
    .ZN(_011_)
  );
  NOR2_X1 _508_ (
    .A1(batch_retired),
    .A2(_088_),
    .ZN(_130_)
  );
  MUX2_X1 _509_ (
    .A(_058_),
    .B(\u_scheduler.state [2]),
    .S(_124_),
    .Z(_131_)
  );
  NAND3_X1 _510_ (
    .A1(\u_scheduler.state [2]),
    .A2(_058_),
    .A3(_091_),
    .ZN(_132_)
  );
  AOI21_X1 _511_ (
    .A(_132_),
    .B1(_000_),
    .B2(batch_retired),
    .ZN(_133_)
  );
  INV_X1 _512_ (
    .A(backend_flushed),
    .ZN(_058_)
  );
  AOI21_X1 _513_ (
    .A(_133_),
    .B1(_131_),
    .B2(_130_),
    .ZN(_134_)
  );
  NAND2_X1 _514_ (
    .A1(_127_),
    .A2(_134_),
    .ZN(\u_scheduler.next_state [2])
  );
  NOR4_X1 _515_ (
    .A1(_086_),
    .A2(_092_),
    .A3(_126_),
    .A4(_128_),
    .ZN(scheduler_quiescent)
  );
  NAND2_X1 _516_ (
    .A1(enable),
    .A2(_102_),
    .ZN(_135_)
  );
  OAI211_X1 _517_ (
    .A(_079_),
    .B(cfg_last_stage[0]),
    .C1(_080_),
    .C2(cfg_last_stage[1]),
    .ZN(_136_)
  );
  OAI221_X1 _518_ (
    .A(_136_),
    .B1(cfg_first_span_log2[1]),
    .B2(_070_),
    .C1(_049_),
    .C2(cfg_first_span_log2[2]),
    .ZN(_137_)
  );
  OAI211_X1 _519_ (
    .A(cfg_span_descending),
    .B(_137_),
    .C1(_056_),
    .C2(cfg_last_stage[2]),
    .ZN(_138_)
  );
  OAI211_X1 _520_ (
    .A(cfg_first_span_log2[0]),
    .B(cfg_last_stage[0]),
    .C1(cfg_first_span_log2[1]),
    .C2(cfg_last_stage[1]),
    .ZN(_139_)
  );
  OAI221_X1 _521_ (
    .A(_139_),
    .B1(_080_),
    .B2(_070_),
    .C1(_049_),
    .C2(_056_),
    .ZN(_140_)
  );
  OAI21_X1 _522_ (
    .A(_140_),
    .B1(cfg_first_span_log2[2]),
    .B2(cfg_last_stage[2]),
    .ZN(_141_)
  );
  DFFS_X1 _523_ (
    .CK(clk),
    .D(_014_),
    .Q(\u_controller.state [0]),
    .QN(_009_),
    .SN(rst_n)
  );
  DFFR_X1 _524_ (
    .CK(clk),
    .D(_011_),
    .Q(\u_controller.state [1]),
    .QN(_262_),
    .RN(rst_n)
  );
  DFFR_X1 _525_ (
    .CK(clk),
    .D(_015_),
    .Q(\u_controller.state [2]),
    .QN(_261_),
    .RN(rst_n)
  );
  DFFR_X1 _526_ (
    .CK(clk),
    .D(_012_),
    .Q(\u_controller.state [3]),
    .QN(_260_),
    .RN(rst_n)
  );
  DFFR_X1 _527_ (
    .CK(clk),
    .D(_016_),
    .Q(\u_controller.state [4]),
    .QN(_259_),
    .RN(rst_n)
  );
  DFFR_X1 _528_ (
    .CK(clk),
    .D(_013_),
    .Q(\u_controller.state [5]),
    .QN(_258_),
    .RN(rst_n)
  );
  DFFR_X1 _529_ (
    .CK(clk),
    .D(_017_),
    .Q(\u_controller.state [6]),
    .QN(_257_),
    .RN(rst_n)
  );
  DFFR_X1 _530_ (
    .CK(clk),
    .D(_018_),
    .Q(\u_controller.state [7]),
    .QN(_251_),
    .RN(rst_n)
  );
  DFFR_X1 _531_ (
    .CK(clk),
    .D(_034_),
    .Q(\u_scheduler.intt_q ),
    .QN(_250_),
    .RN(rst_n)
  );
  DFFR_X1 _532_ (
    .CK(clk),
    .D(_033_),
    .Q(\u_scheduler.span_q [0]),
    .QN(_008_),
    .RN(rst_n)
  );
  DFFR_X1 _533_ (
    .CK(clk),
    .D(_032_),
    .Q(\u_scheduler.span_q [1]),
    .QN(_252_),
    .RN(rst_n)
  );
  DFFR_X1 _534_ (
    .CK(clk),
    .D(_035_),
    .Q(\u_scheduler.span_q [2]),
    .QN(_249_),
    .RN(rst_n)
  );
  DFFR_X1 _535_ (
    .CK(clk),
    .D(_031_),
    .Q(\u_scheduler.stage_q [0]),
    .QN(_253_),
    .RN(rst_n)
  );
  DFFR_X1 _536_ (
    .CK(clk),
    .D(_030_),
    .Q(\u_scheduler.stage_q [1]),
    .QN(_254_),
    .RN(rst_n)
  );
  DFFR_X1 _537_ (
    .CK(clk),
    .D(_036_),
    .Q(\u_scheduler.stage_q [2]),
    .QN(_248_),
    .RN(rst_n)
  );
  DFFR_X1 _538_ (
    .CK(clk),
    .D(_029_),
    .Q(\u_scheduler.batch_index_q [0]),
    .QN(_238_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _539_ (
    .CK(clk),
    .D(_028_),
    .Q(\u_scheduler.batch_index_q [1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _540_ (
    .CK(clk),
    .D(_027_),
    .Q(\u_scheduler.batch_index_q [2]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _541_ (
    .CK(clk),
    .D(_026_),
    .Q(\u_scheduler.batch_index_q [3]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _542_ (
    .CK(clk),
    .D(_025_),
    .Q(\u_scheduler.batch_index_q [4]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _543_ (
    .CK(clk),
    .D(_037_),
    .Q(\u_scheduler.batch_index_q [5]),
    .QN(_010_),
    .RN(rst_n)
  );
  DFFR_X1 _544_ (
    .CK(clk),
    .D(_038_),
    .Q(\u_controller.intt_mode_q ),
    .QN(_247_),
    .RN(rst_n)
  );
  DFFR_X1 _545_ (
    .CK(clk),
    .D(_024_),
    .Q(\u_controller.u_stage_counter.last_stage_q [0]),
    .QN(_237_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _546_ (
    .CK(clk),
    .D(_023_),
    .Q(\u_controller.u_stage_counter.last_stage_q [1]),
    .QN(_237_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _547_ (
    .CK(clk),
    .D(_039_),
    .Q(\u_controller.u_stage_counter.last_stage_q [2]),
    .QN(_237_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _548_ (
    .CK(clk),
    .D(_022_),
    .Q(\u_controller.u_stage_counter.stage_count [0]),
    .QN(_239_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _549_ (
    .CK(clk),
    .D(_021_),
    .Q(\u_controller.u_stage_counter.stage_count [1]),
    .QN(_263_[1]),
    .RN(rst_n)
  );
  DFFR_X1 _550_ (
    .CK(clk),
    .D(_040_),
    .Q(\u_controller.u_stage_counter.stage_count [2]),
    .QN(_263_[2]),
    .RN(rst_n)
  );
  DFFR_X1 _551_ (
    .CK(clk),
    .D(_041_),
    .Q(descending_q),
    .QN(_246_),
    .RN(rst_n)
  );
  DFFR_X1 _552_ (
    .CK(clk),
    .D(_020_),
    .Q(first_span_q[0]),
    .QN(_255_),
    .RN(rst_n)
  );
  DFFR_X1 _553_ (
    .CK(clk),
    .D(_019_),
    .Q(first_span_q[1]),
    .QN(_256_),
    .RN(rst_n)
  );
  DFFR_X1 _554_ (
    .CK(clk),
    .D(_042_),
    .Q(first_span_q[2]),
    .QN(_245_),
    .RN(rst_n)
  );
  DFFR_X1 _555_ (
    .CK(clk),
    .D(_043_),
    .Q(error_controller),
    .QN(_244_),
    .RN(rst_n)
  );
  DFFR_X1 _556_ (
    .CK(clk),
    .D(_044_),
    .Q(error_scheduler),
    .QN(_243_),
    .RN(rst_n)
  );
  DFFR_X1 _557_ (
    .CK(clk),
    .D(_045_),
    .Q(error_datapath),
    .QN(_242_),
    .RN(rst_n)
  );
  DFFR_X1 _558_ (
    .CK(clk),
    .D(_046_),
    .Q(error_ecc),
    .QN(_241_),
    .RN(rst_n)
  );
  DFFR_X1 _559_ (
    .CK(clk),
    .D(_047_),
    .Q(error_config),
    .QN(_240_),
    .RN(rst_n)
  );
  DFFR_X1 _560_ (
    .CK(clk),
    .D(_048_),
    .Q(\u_scheduler.fault_q ),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _561_ (
    .CK(clk),
    .D(\u_scheduler.next_state [0]),
    .Q(\u_scheduler.state [0]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _562_ (
    .CK(clk),
    .D(\u_scheduler.next_state [1]),
    .Q(\u_scheduler.state [1]),
    .QN(_007_),
    .RN(rst_n)
  );
  DFFR_X1 _563_ (
    .CK(clk),
    .D(\u_scheduler.next_state [2]),
    .Q(\u_scheduler.state [2]),
    .QN(_001_),
    .RN(rst_n)
  );
  assign _263_[0] = _239_[0];
  assign \u_scheduler.decode_lanes.ordinal  = { 1'h0, \u_scheduler.batch_index_q , 1'h1 };
  assign \u_scheduler.range_valid  = 1'h1;
  assign \u_scheduler.distance_mask [0] = coeff_addr_b[0];
  assign \u_scheduler.low_mask [0] = coeff_addr_a[8];
  assign \u_scheduler.scheduler_fault  = \u_scheduler.fault_q ;
  assign \u_scheduler.scheduler_quiescent  = scheduler_quiescent;
  assign \u_scheduler.stage_done  = stage_done;
  assign \u_scheduler.backend_flushed  = backend_flushed;
  assign \u_scheduler.batch_retired  = batch_retired;
  assign \u_scheduler.batch_intt  = \u_scheduler.intt_q ;
  assign \u_scheduler.batch_span_log2  = \u_scheduler.span_q ;
  assign \u_scheduler.batch_stage  = \u_scheduler.stage_q ;
  assign \u_scheduler.butterfly_index  = { \u_scheduler.batch_index_q , 1'h1, \u_scheduler.batch_index_q , 1'h0 };
  assign \u_scheduler.coeff_addr_b  = { coeff_addr_b[7:2], coeff_addr_b[9], 1'h1, coeff_addr_b[7:0] };
  assign \u_scheduler.coeff_addr_a  = { coeff_addr_a[7:2], coeff_addr_a[9:1], 1'h0 };
  assign \u_scheduler.lane_valid  = { batch_valid, batch_valid };
  assign \u_scheduler.batch_ready  = batch_ready;
  assign \u_scheduler.batch_valid  = batch_valid;
  assign \u_scheduler.zeroize_req  = zeroize_req;
  assign \u_scheduler.zeroize  = zeroize;
  assign \u_scheduler.butterfly_enable  = butterfly_enable;
  assign \u_scheduler.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_scheduler.schedule_span_descending  = descending_q;
  assign \u_scheduler.schedule_first_span_log2  = first_span_q;
  assign \u_scheduler.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_scheduler.stage_start  = stage_start;
  assign \u_scheduler.rst_n  = rst_n;
  assign \u_scheduler.clk  = clk;
  assign \u_controller.u_stage_counter.cfg_valid  = 1'h1;
  assign _239_[2:1] = \u_controller.u_stage_counter.stage_count [2:1];
  assign \u_controller.u_stage_counter.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.u_stage_counter.rst_n  = rst_n;
  assign \u_controller.u_stage_counter.clk  = clk;
  assign \u_controller.cfg_valid  = 1'h1;
  assign \u_controller.next_state [3] = 1'h0;
  assign _238_[5:1] = \u_scheduler.batch_index_q [5:1];
  assign \u_controller.stage_count  = \u_controller.u_stage_counter.stage_count ;
  assign \u_controller.transform_intt  = \u_controller.intt_mode_q ;
  assign \u_controller.transform_abort  = transform_abort;
  assign \u_controller.transform_done  = done;
  assign \u_controller.zeroize_req  = zeroize_req;
  assign \u_controller.butterfly_enable  = butterfly_enable;
  assign \u_controller.stage_start  = stage_start;
  assign \u_controller.ntt_start  = load_start;
  assign \u_controller.ntt_active  = active;
  assign \u_controller.b2a_error_code  = 16'h0000;
  assign \u_controller.b2a_done  = done;
  assign \u_controller.b2a_busy  = busy;
  assign \u_controller.b2a_ready  = ready;
  assign \u_controller.stage_done  = stage_done;
  assign \u_controller.butterfly_done  = 1'h0;
  assign \u_controller.cfg_last_stage  = cfg_last_stage;
  assign \u_controller.intt_mode  = intt_mode;
  assign \u_controller.a2b_zeroize  = zeroize;
  assign \u_controller.a2b_start  = start;
  assign \u_controller.a2b_context_id  = 5'h00;
  assign \u_controller.a2b_profile_id  = 4'h0;
  assign \u_controller.a2b_cmd_opcode  = 6'h00;
  assign \u_controller.rst_n  = rst_n;
  assign \u_controller.clk  = clk;
  assign scheduler_fault = \u_scheduler.fault_q ;
  assign range_valid = 1'h1;
  assign batch_intt = \u_scheduler.intt_q ;
  assign batch_span_log2 = \u_scheduler.span_q ;
  assign batch_stage = \u_scheduler.stage_q ;
  assign butterfly_index = { \u_scheduler.batch_index_q , 1'h1, \u_scheduler.batch_index_q , 1'h0 };
  assign { coeff_addr_b[15:10], coeff_addr_b[8] } = { coeff_addr_b[7:2], 1'h1 };
  assign { coeff_addr_a[15:10], coeff_addr_a[0] } = { coeff_addr_a[7:2], 1'h0 };
  assign lane_valid = { batch_valid, batch_valid };
  assign stage_count = \u_controller.u_stage_counter.stage_count ;
  assign transform_intt = \u_controller.intt_mode_q ;
endmodule
